// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.1 (commit 6e4be41ffde5051d083f9aedd22d2dcc18e6ac63).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CallSessionCreateReducer from "./call_session_create_reducer";
import CallSessionEndReducer from "./call_session_end_reducer";
import CallSessionJoinReducer from "./call_session_join_reducer";
import CallSessionLeaveReducer from "./call_session_leave_reducer";
import CallSignalEmitReducer from "./call_signal_emit_reducer";
import IngestWabiEventReducer from "./ingest_wabi_event_reducer";
import SetIngestKeyReducer from "./set_ingest_key_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import IngestedEventRow from "./ingested_event_table";
import StateAlbumRow from "./state_album_table";
import StateAlbumItemRow from "./state_album_item_table";
import StateAppSettingRow from "./state_app_setting_table";
import StateBackendInstanceLeaseRow from "./state_backend_instance_lease_table";
import StateBanRow from "./state_ban_table";
import StateCallParticipantRow from "./state_call_participant_table";
import StateCallSessionRow from "./state_call_session_table";
import StateCallSignalRow from "./state_call_signal_table";
import StateChannelRow from "./state_channel_table";
import StateChannelMemberRow from "./state_channel_member_table";
import StateDeafenRow from "./state_deafen_table";
import StateDictionaryEntryRow from "./state_dictionary_entry_table";
import StateEmojiRoleRuleRow from "./state_emoji_role_rule_table";
import StateEmoteRow from "./state_emote_table";
import StateGuestCodeRow from "./state_guest_code_table";
import StateLayoutPreferencesRow from "./state_layout_preferences_table";
import StateManualSettlementRow from "./state_manual_settlement_table";
import StateMessageRow from "./state_message_table";
import StateMuteRow from "./state_mute_table";
import StateOfflineMessageRow from "./state_offline_message_table";
import StatePaymentAccountLinkRow from "./state_payment_account_link_table";
import StatePaymentEventRow from "./state_payment_event_table";
import StatePaymentIntentRow from "./state_payment_intent_table";
import StatePaymentPolicyRow from "./state_payment_policy_table";
import StatePaymentUserBlockRow from "./state_payment_user_block_table";
import StatePresenceLeaseRow from "./state_presence_lease_table";
import StateRbacAssignmentRow from "./state_rbac_assignment_table";
import StateReactionRow from "./state_reaction_table";
import StateRelayRow from "./state_relay_table";
import StateRoleDefinitionRow from "./state_role_definition_table";
import StateSessionRow from "./state_session_table";
import StateSocketLeaseRow from "./state_socket_lease_table";
import StateThemePreferencesRow from "./state_theme_preferences_table";
import StateUserRow from "./state_user_table";
import StateUserEncryptionKeyRow from "./state_user_encryption_key_table";
import StateUserHandleRow from "./state_user_handle_table";
import StateUserMetaRow from "./state_user_meta_table";
import StateUserSettingsRow from "./state_user_settings_table";
import StateUserUsernameRow from "./state_user_username_table";
import StateWebhookRow from "./state_webhook_table";
import StateWebhookDeliveryRow from "./state_webhook_delivery_table";
import StateWhiteboardRow from "./state_whiteboard_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  ingested_event: __table({
    name: 'ingested_event',
    indexes: [
      { accessor: 'event_id', name: 'ingested_event_event_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
      ] },
    ],
    constraints: [
      { name: 'ingested_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, IngestedEventRow),
  state_album: __table({
    name: 'state_album',
    indexes: [
      { accessor: 'album_id', name: 'state_album_album_id_idx_btree', algorithm: 'btree', columns: [
        'albumId',
      ] },
    ],
    constraints: [
      { name: 'state_album_album_id_key', constraint: 'unique', columns: ['albumId'] },
    ],
  }, StateAlbumRow),
  state_album_item: __table({
    name: 'state_album_item',
    indexes: [
      { accessor: 'item_id', name: 'state_album_item_item_id_idx_btree', algorithm: 'btree', columns: [
        'itemId',
      ] },
    ],
    constraints: [
      { name: 'state_album_item_item_id_key', constraint: 'unique', columns: ['itemId'] },
    ],
  }, StateAlbumItemRow),
  state_app_setting: __table({
    name: 'state_app_setting',
    indexes: [
      { accessor: 'setting_key', name: 'state_app_setting_setting_key_idx_btree', algorithm: 'btree', columns: [
        'settingKey',
      ] },
    ],
    constraints: [
      { name: 'state_app_setting_setting_key_key', constraint: 'unique', columns: ['settingKey'] },
    ],
  }, StateAppSettingRow),
  state_backend_instance_lease: __table({
    name: 'state_backend_instance_lease',
    indexes: [
      { accessor: 'instance_id', name: 'state_backend_instance_lease_instance_id_idx_btree', algorithm: 'btree', columns: [
        'instanceId',
      ] },
    ],
    constraints: [
      { name: 'state_backend_instance_lease_instance_id_key', constraint: 'unique', columns: ['instanceId'] },
    ],
  }, StateBackendInstanceLeaseRow),
  state_ban: __table({
    name: 'state_ban',
    indexes: [
      { accessor: 'user_id', name: 'state_ban_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'state_ban_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, StateBanRow),
  state_call_participant: __table({
    name: 'state_call_participant',
    indexes: [
      { accessor: 'participant_key', name: 'state_call_participant_participant_key_idx_btree', algorithm: 'btree', columns: [
        'participantKey',
      ] },
      { accessor: 'session_id', name: 'state_call_participant_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'state_call_participant_participant_key_key', constraint: 'unique', columns: ['participantKey'] },
    ],
  }, StateCallParticipantRow),
  state_call_session: __table({
    name: 'state_call_session',
    indexes: [
      { accessor: 'session_id', name: 'state_call_session_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'state_call_session_session_id_key', constraint: 'unique', columns: ['sessionId'] },
    ],
  }, StateCallSessionRow),
  state_call_signal: __table({
    name: 'state_call_signal',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, StateCallSignalRow),
  state_channel: __table({
    name: 'state_channel',
    indexes: [
      { accessor: 'channel_id', name: 'state_channel_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
    ],
    constraints: [
      { name: 'state_channel_channel_id_key', constraint: 'unique', columns: ['channelId'] },
    ],
  }, StateChannelRow),
  state_channel_member: __table({
    name: 'state_channel_member',
    indexes: [
      { accessor: 'member_key', name: 'state_channel_member_member_key_idx_btree', algorithm: 'btree', columns: [
        'memberKey',
      ] },
    ],
    constraints: [
      { name: 'state_channel_member_member_key_key', constraint: 'unique', columns: ['memberKey'] },
    ],
  }, StateChannelMemberRow),
  state_deafen: __table({
    name: 'state_deafen',
    indexes: [
      { accessor: 'deafen_key', name: 'state_deafen_deafen_key_idx_btree', algorithm: 'btree', columns: [
        'deafenKey',
      ] },
    ],
    constraints: [
      { name: 'state_deafen_deafen_key_key', constraint: 'unique', columns: ['deafenKey'] },
    ],
  }, StateDeafenRow),
  state_dictionary_entry: __table({
    name: 'state_dictionary_entry',
    indexes: [
      { accessor: 'entry_key', name: 'state_dictionary_entry_entry_key_idx_btree', algorithm: 'btree', columns: [
        'entryKey',
      ] },
    ],
    constraints: [
      { name: 'state_dictionary_entry_entry_key_key', constraint: 'unique', columns: ['entryKey'] },
    ],
  }, StateDictionaryEntryRow),
  state_emoji_role_rule: __table({
    name: 'state_emoji_role_rule',
    indexes: [
      { accessor: 'rule_id', name: 'state_emoji_role_rule_rule_id_idx_btree', algorithm: 'btree', columns: [
        'ruleId',
      ] },
    ],
    constraints: [
      { name: 'state_emoji_role_rule_rule_id_key', constraint: 'unique', columns: ['ruleId'] },
    ],
  }, StateEmojiRoleRuleRow),
  state_emote: __table({
    name: 'state_emote',
    indexes: [
      { accessor: 'emote_id', name: 'state_emote_emote_id_idx_btree', algorithm: 'btree', columns: [
        'emoteId',
      ] },
    ],
    constraints: [
      { name: 'state_emote_emote_id_key', constraint: 'unique', columns: ['emoteId'] },
    ],
  }, StateEmoteRow),
  state_guest_code: __table({
    name: 'state_guest_code',
    indexes: [
      { accessor: 'code', name: 'state_guest_code_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
    ],
    constraints: [
      { name: 'state_guest_code_code_key', constraint: 'unique', columns: ['code'] },
    ],
  }, StateGuestCodeRow),
  state_layout_preferences: __table({
    name: 'state_layout_preferences',
    indexes: [
      { accessor: 'user_id', name: 'state_layout_preferences_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'state_layout_preferences_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, StateLayoutPreferencesRow),
  state_manual_settlement: __table({
    name: 'state_manual_settlement',
    indexes: [
      { accessor: 'settlement_id', name: 'state_manual_settlement_settlement_id_idx_btree', algorithm: 'btree', columns: [
        'settlementId',
      ] },
    ],
    constraints: [
      { name: 'state_manual_settlement_settlement_id_key', constraint: 'unique', columns: ['settlementId'] },
    ],
  }, StateManualSettlementRow),
  state_message: __table({
    name: 'state_message',
    indexes: [
      { accessor: 'message_id', name: 'state_message_message_id_idx_btree', algorithm: 'btree', columns: [
        'messageId',
      ] },
    ],
    constraints: [
      { name: 'state_message_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, StateMessageRow),
  state_mute: __table({
    name: 'state_mute',
    indexes: [
      { accessor: 'mute_key', name: 'state_mute_mute_key_idx_btree', algorithm: 'btree', columns: [
        'muteKey',
      ] },
    ],
    constraints: [
      { name: 'state_mute_mute_key_key', constraint: 'unique', columns: ['muteKey'] },
    ],
  }, StateMuteRow),
  state_offline_message: __table({
    name: 'state_offline_message',
    indexes: [
      { accessor: 'message_id', name: 'state_offline_message_message_id_idx_btree', algorithm: 'btree', columns: [
        'messageId',
      ] },
    ],
    constraints: [
      { name: 'state_offline_message_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, StateOfflineMessageRow),
  state_payment_account_link: __table({
    name: 'state_payment_account_link',
    indexes: [
      { accessor: 'account_link_key', name: 'state_payment_account_link_account_link_key_idx_btree', algorithm: 'btree', columns: [
        'accountLinkKey',
      ] },
    ],
    constraints: [
      { name: 'state_payment_account_link_account_link_key_key', constraint: 'unique', columns: ['accountLinkKey'] },
    ],
  }, StatePaymentAccountLinkRow),
  state_payment_event: __table({
    name: 'state_payment_event',
    indexes: [
      { accessor: 'event_id', name: 'state_payment_event_event_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
      ] },
    ],
    constraints: [
      { name: 'state_payment_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, StatePaymentEventRow),
  state_payment_intent: __table({
    name: 'state_payment_intent',
    indexes: [
      { accessor: 'intent_id', name: 'state_payment_intent_intent_id_idx_btree', algorithm: 'btree', columns: [
        'intentId',
      ] },
    ],
    constraints: [
      { name: 'state_payment_intent_intent_id_key', constraint: 'unique', columns: ['intentId'] },
    ],
  }, StatePaymentIntentRow),
  state_payment_policy: __table({
    name: 'state_payment_policy',
    indexes: [
      { accessor: 'policy_key', name: 'state_payment_policy_policy_key_idx_btree', algorithm: 'btree', columns: [
        'policyKey',
      ] },
    ],
    constraints: [
      { name: 'state_payment_policy_policy_key_key', constraint: 'unique', columns: ['policyKey'] },
    ],
  }, StatePaymentPolicyRow),
  state_payment_user_block: __table({
    name: 'state_payment_user_block',
    indexes: [
      { accessor: 'block_key', name: 'state_payment_user_block_block_key_idx_btree', algorithm: 'btree', columns: [
        'blockKey',
      ] },
    ],
    constraints: [
      { name: 'state_payment_user_block_block_key_key', constraint: 'unique', columns: ['blockKey'] },
    ],
  }, StatePaymentUserBlockRow),
  state_presence_lease: __table({
    name: 'state_presence_lease',
    indexes: [
      { accessor: 'stable_user_id', name: 'state_presence_lease_stable_user_id_idx_btree', algorithm: 'btree', columns: [
        'stableUserId',
      ] },
    ],
    constraints: [
      { name: 'state_presence_lease_stable_user_id_key', constraint: 'unique', columns: ['stableUserId'] },
    ],
  }, StatePresenceLeaseRow),
  state_rbac_assignment: __table({
    name: 'state_rbac_assignment',
    indexes: [
      { accessor: 'assignment_key', name: 'state_rbac_assignment_assignment_key_idx_btree', algorithm: 'btree', columns: [
        'assignmentKey',
      ] },
    ],
    constraints: [
      { name: 'state_rbac_assignment_assignment_key_key', constraint: 'unique', columns: ['assignmentKey'] },
    ],
  }, StateRbacAssignmentRow),
  state_reaction: __table({
    name: 'state_reaction',
    indexes: [
      { accessor: 'reaction_id', name: 'state_reaction_reaction_id_idx_btree', algorithm: 'btree', columns: [
        'reactionId',
      ] },
    ],
    constraints: [
      { name: 'state_reaction_reaction_id_key', constraint: 'unique', columns: ['reactionId'] },
    ],
  }, StateReactionRow),
  state_relay: __table({
    name: 'state_relay',
    indexes: [
      { accessor: 'relay_id', name: 'state_relay_relay_id_idx_btree', algorithm: 'btree', columns: [
        'relayId',
      ] },
    ],
    constraints: [
      { name: 'state_relay_relay_id_key', constraint: 'unique', columns: ['relayId'] },
    ],
  }, StateRelayRow),
  state_role_definition: __table({
    name: 'state_role_definition',
    indexes: [
      { accessor: 'role_key', name: 'state_role_definition_role_key_idx_btree', algorithm: 'btree', columns: [
        'roleKey',
      ] },
    ],
    constraints: [
      { name: 'state_role_definition_role_key_key', constraint: 'unique', columns: ['roleKey'] },
    ],
  }, StateRoleDefinitionRow),
  state_session: __table({
    name: 'state_session',
    indexes: [
      { accessor: 'session_id', name: 'state_session_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'state_session_session_id_key', constraint: 'unique', columns: ['sessionId'] },
    ],
  }, StateSessionRow),
  state_socket_lease: __table({
    name: 'state_socket_lease',
    indexes: [
      { accessor: 'stable_user_id', name: 'state_socket_lease_stable_user_id_idx_btree', algorithm: 'btree', columns: [
        'stableUserId',
      ] },
    ],
    constraints: [
      { name: 'state_socket_lease_stable_user_id_key', constraint: 'unique', columns: ['stableUserId'] },
    ],
  }, StateSocketLeaseRow),
  state_theme_preferences: __table({
    name: 'state_theme_preferences',
    indexes: [
      { accessor: 'user_id', name: 'state_theme_preferences_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'state_theme_preferences_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, StateThemePreferencesRow),
  state_user: __table({
    name: 'state_user',
    indexes: [
      { accessor: 'user_id', name: 'state_user_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'state_user_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, StateUserRow),
  state_user_encryption_key: __table({
    name: 'state_user_encryption_key',
    indexes: [
      { accessor: 'user_id', name: 'state_user_encryption_key_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'state_user_encryption_key_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, StateUserEncryptionKeyRow),
  state_user_handle: __table({
    name: 'state_user_handle',
    indexes: [
      { accessor: 'handle_lc', name: 'state_user_handle_handle_lc_idx_btree', algorithm: 'btree', columns: [
        'handleLc',
      ] },
    ],
    constraints: [
      { name: 'state_user_handle_handle_lc_key', constraint: 'unique', columns: ['handleLc'] },
    ],
  }, StateUserHandleRow),
  state_user_meta: __table({
    name: 'state_user_meta',
    indexes: [
      { accessor: 'meta_key', name: 'state_user_meta_meta_key_idx_btree', algorithm: 'btree', columns: [
        'metaKey',
      ] },
    ],
    constraints: [
      { name: 'state_user_meta_meta_key_key', constraint: 'unique', columns: ['metaKey'] },
    ],
  }, StateUserMetaRow),
  state_user_settings: __table({
    name: 'state_user_settings',
    indexes: [
      { accessor: 'user_id', name: 'state_user_settings_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'state_user_settings_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, StateUserSettingsRow),
  state_user_username: __table({
    name: 'state_user_username',
    indexes: [
      { accessor: 'username_lc', name: 'state_user_username_username_lc_idx_btree', algorithm: 'btree', columns: [
        'usernameLc',
      ] },
    ],
    constraints: [
      { name: 'state_user_username_username_lc_key', constraint: 'unique', columns: ['usernameLc'] },
    ],
  }, StateUserUsernameRow),
  state_webhook: __table({
    name: 'state_webhook',
    indexes: [
      { accessor: 'webhook_id', name: 'state_webhook_webhook_id_idx_btree', algorithm: 'btree', columns: [
        'webhookId',
      ] },
    ],
    constraints: [
      { name: 'state_webhook_webhook_id_key', constraint: 'unique', columns: ['webhookId'] },
    ],
  }, StateWebhookRow),
  state_webhook_delivery: __table({
    name: 'state_webhook_delivery',
    indexes: [
      { accessor: 'delivery_id', name: 'state_webhook_delivery_delivery_id_idx_btree', algorithm: 'btree', columns: [
        'deliveryId',
      ] },
    ],
    constraints: [
      { name: 'state_webhook_delivery_delivery_id_key', constraint: 'unique', columns: ['deliveryId'] },
    ],
  }, StateWebhookDeliveryRow),
  state_whiteboard: __table({
    name: 'state_whiteboard',
    indexes: [
      { accessor: 'board_id', name: 'state_whiteboard_board_id_idx_btree', algorithm: 'btree', columns: [
        'boardId',
      ] },
    ],
    constraints: [
      { name: 'state_whiteboard_board_id_key', constraint: 'unique', columns: ['boardId'] },
    ],
  }, StateWhiteboardRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("call_session_create", CallSessionCreateReducer),
  __reducerSchema("call_session_end", CallSessionEndReducer),
  __reducerSchema("call_session_join", CallSessionJoinReducer),
  __reducerSchema("call_session_leave", CallSessionLeaveReducer),
  __reducerSchema("call_signal_emit", CallSignalEmitReducer),
  __reducerSchema("ingest_wabi_event", IngestWabiEventReducer),
  __reducerSchema("set_ingest_key", SetIngestKeyReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.2.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

