// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemId: __t.i64().primaryKey().name("item_id"),
  albumId: __t.i64().name("album_id"),
  attachmentUrl: __t.string().name("attachment_url"),
  attachmentName: __t.string().name("attachment_name"),
  attachmentSize: __t.option(__t.i64()).name("attachment_size"),
  attachmentMime: __t.option(__t.string()).name("attachment_mime"),
  messageId: __t.option(__t.string()).name("message_id"),
  caption: __t.option(__t.string()),
  sortOrder: __t.i64().name("sort_order"),
  uploadedBy: __t.i64().name("uploaded_by"),
  uploadedAt: __t.i64().name("uploaded_at"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
