// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  deliveryId: __t.i64().primaryKey().name("delivery_id"),
  webhookId: __t.i64().name("webhook_id"),
  eventType: __t.string().name("event_type"),
  payloadJson: __t.string().name("payload_json"),
  status: __t.string(),
  attemptCount: __t.i64().name("attempt_count"),
  lastError: __t.option(__t.string()).name("last_error"),
  responseCode: __t.option(__t.i64()).name("response_code"),
  createdAt: __t.i64().name("created_at"),
  updatedAt: __t.i64().name("updated_at"),
  deliveredAt: __t.option(__t.i64()).name("delivered_at"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
