// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  channelId: __t.string().name("channel_id"),
  callType: __t.string().name("call_type"),
  hostUserId: __t.option(__t.i64()).name("host_user_id"),
  startedAt: __t.i64().name("started_at"),
  endedAt: __t.option(__t.i64()).name("ended_at"),
  transport: __t.string(),
  maxParticipants: __t.i64().name("max_participants"),
  active: __t.bool(),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
