// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().name("session_id"),
  signalType: __t.string().name("signal_type"),
  targetUserId: __t.option(__t.i64()).name("target_user_id"),
  payload: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
