// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  stableUserId: __t.string().primaryKey().name("stable_user_id"),
  dbUserId: __t.option(__t.i64()).name("db_user_id"),
  instanceId: __t.string().name("instance_id"),
  status: __t.string(),
  connectedAt: __t.i64().name("connected_at"),
  leaseExpiresAt: __t.i64().name("lease_expires_at"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
