// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  blockKey: __t.string().primaryKey().name("block_key"),
  userId: __t.i64().name("user_id"),
  workspaceId: __t.string().name("workspace_id"),
  blockedByUserId: __t.option(__t.i64()).name("blocked_by_user_id"),
  blockedAt: __t.i64().name("blocked_at"),
  expiresAt: __t.option(__t.i64()).name("expires_at"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
