// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  messageId: __t.i64().primaryKey().name("message_id"),
  fromUserId: __t.option(__t.i64()).name("from_user_id"),
  fromUsername: __t.string().name("from_username"),
  toUserId: __t.i64().name("to_user_id"),
  channelId: __t.string().name("channel_id"),
  messageContent: __t.string().name("message_content"),
  messageType: __t.string().name("message_type"),
  gifUrl: __t.option(__t.string()).name("gif_url"),
  fileUrl: __t.option(__t.string()).name("file_url"),
  fileName: __t.option(__t.string()).name("file_name"),
  fileSize: __t.option(__t.i64()).name("file_size"),
  messagePayloadJson: __t.option(__t.string()).name("message_payload_json"),
  createdAt: __t.i64().name("created_at"),
  expiresAt: __t.option(__t.i64()).name("expires_at"),
  delivered: __t.bool(),
});
