// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.i64().primaryKey().name("user_id"),
  bannedBy: __t.i64().name("banned_by"),
  reason: __t.string(),
  active: __t.bool(),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
