// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  boardId: __t.string().primaryKey().name("board_id"),
  workspaceId: __t.string().name("workspace_id"),
  scopeType: __t.string().name("scope_type"),
  scopeId: __t.string().name("scope_id"),
  version: __t.i64(),
  documentJson: __t.string().name("document_json"),
  isPrivate: __t.bool().name("is_private"),
  createdBy: __t.option(__t.string()).name("created_by"),
  updatedBy: __t.option(__t.string()).name("updated_by"),
  createdAt: __t.i64().name("created_at"),
  updatedAt: __t.i64().name("updated_at"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
