// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const IngestAuthConfig = __t.object("IngestAuthConfig", {
  configKey: __t.string(),
  authKeyHash: __t.string(),
  updatedAt: __t.timestamp(),
});
export type IngestAuthConfig = __Infer<typeof IngestAuthConfig>;

export const IngestedEvent = __t.object("IngestedEvent", {
  eventId: __t.string(),
  eventTimestamp: __t.i64(),
  entity: __t.string(),
  operation: __t.string(),
  payloadJson: __t.string(),
  ingestedAt: __t.timestamp(),
});
export type IngestedEvent = __Infer<typeof IngestedEvent>;

export const StateAlbum = __t.object("StateAlbum", {
  albumId: __t.i64(),
  scopeType: __t.string(),
  scopeId: __t.string(),
  name: __t.string(),
  createdBy: __t.i64(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
  isArchived: __t.bool(),
  isFeatured: __t.bool(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateAlbum = __Infer<typeof StateAlbum>;

export const StateAlbumItem = __t.object("StateAlbumItem", {
  itemId: __t.i64(),
  albumId: __t.i64(),
  attachmentUrl: __t.string(),
  attachmentName: __t.string(),
  attachmentSize: __t.option(__t.i64()),
  attachmentMime: __t.option(__t.string()),
  messageId: __t.option(__t.string()),
  caption: __t.option(__t.string()),
  sortOrder: __t.i64(),
  uploadedBy: __t.i64(),
  uploadedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateAlbumItem = __Infer<typeof StateAlbumItem>;

export const StateAppSetting = __t.object("StateAppSetting", {
  settingKey: __t.string(),
  value: __t.string(),
  updatedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateAppSetting = __Infer<typeof StateAppSetting>;

export const StateBackendInstanceLease = __t.object("StateBackendInstanceLease", {
  instanceId: __t.string(),
  region: __t.string(),
  role: __t.string(),
  status: __t.string(),
  currentConnections: __t.i64(),
  currentRegisteredUsers: __t.i64(),
  currentGuestUsers: __t.i64(),
  heartbeatAt: __t.i64(),
  leaseExpiresAt: __t.i64(),
  startedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateBackendInstanceLease = __Infer<typeof StateBackendInstanceLease>;

export const StateBan = __t.object("StateBan", {
  userId: __t.i64(),
  bannedBy: __t.i64(),
  reason: __t.string(),
  active: __t.bool(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateBan = __Infer<typeof StateBan>;

export const StateCallParticipant = __t.object("StateCallParticipant", {
  participantKey: __t.string(),
  sessionId: __t.string(),
  userId: __t.i64(),
  stableUserId: __t.string(),
  joinedAt: __t.i64(),
  leftAt: __t.option(__t.i64()),
  isHost: __t.bool(),
  muted: __t.bool(),
  videoEnabled: __t.bool(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateCallParticipant = __Infer<typeof StateCallParticipant>;

export const StateCallSession = __t.object("StateCallSession", {
  sessionId: __t.string(),
  channelId: __t.string(),
  callType: __t.string(),
  hostUserId: __t.option(__t.i64()),
  startedAt: __t.i64(),
  endedAt: __t.option(__t.i64()),
  transport: __t.string(),
  maxParticipants: __t.i64(),
  active: __t.bool(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateCallSession = __Infer<typeof StateCallSession>;

export const StateCallSignal = __t.object("StateCallSignal", {
  sessionId: __t.string(),
  signalType: __t.string(),
  targetUserId: __t.option(__t.i64()),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type StateCallSignal = __Infer<typeof StateCallSignal>;

export const StateChannel = __t.object("StateChannel", {
  channelId: __t.string(),
  channelType: __t.string(),
  name: __t.string(),
  createdAt: __t.i64(),
  createdBy: __t.string(),
  archived: __t.bool(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateChannel = __Infer<typeof StateChannel>;

export const StateChannelMember = __t.object("StateChannelMember", {
  memberKey: __t.string(),
  channelId: __t.string(),
  userId: __t.string(),
  role: __t.string(),
  joinedAt: __t.i64(),
  active: __t.bool(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateChannelMember = __Infer<typeof StateChannelMember>;

export const StateDeafen = __t.object("StateDeafen", {
  deafenKey: __t.string(),
  userId: __t.i64(),
  channelId: __t.string(),
  deafenedBy: __t.i64(),
  active: __t.bool(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateDeafen = __Infer<typeof StateDeafen>;

export const StateDictionaryEntry = __t.object("StateDictionaryEntry", {
  entryKey: __t.string(),
  workspaceId: __t.string(),
  language: __t.string(),
  termNormalized: __t.string(),
  term: __t.string(),
  createdByUserId: __t.option(__t.i64()),
  createdByUsername: __t.option(__t.string()),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
  votes: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateDictionaryEntry = __Infer<typeof StateDictionaryEntry>;

export const StateEmojiRoleRule = __t.object("StateEmojiRoleRule", {
  ruleId: __t.i64(),
  channelId: __t.string(),
  messageId: __t.string(),
  emojiId: __t.string(),
  roleName: __t.string(),
  removeOnUnreact: __t.bool(),
  workspaceId: __t.string(),
  enabled: __t.bool(),
  createdAt: __t.i64(),
});
export type StateEmojiRoleRule = __Infer<typeof StateEmojiRoleRule>;

export const StateEmote = __t.object("StateEmote", {
  emoteId: __t.string(),
  name: __t.string(),
  url: __t.string(),
  emoteType: __t.string(),
  createdBy: __t.i64(),
  createdAt: __t.timestamp(),
});
export type StateEmote = __Infer<typeof StateEmote>;

export const StateGuestCode = __t.object("StateGuestCode", {
  code: __t.string(),
  description: __t.option(__t.string()),
  createdAt: __t.i64(),
  createdBy: __t.option(__t.i64()),
  isActive: __t.bool(),
});
export type StateGuestCode = __Infer<typeof StateGuestCode>;

export const StateLayoutPreferences = __t.object("StateLayoutPreferences", {
  userId: __t.i64(),
  layoutJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type StateLayoutPreferences = __Infer<typeof StateLayoutPreferences>;

export const StateManualSettlement = __t.object("StateManualSettlement", {
  settlementId: __t.string(),
  workspaceId: __t.string(),
  settlementKind: __t.string(),
  channelId: __t.option(__t.string()),
  createdByUserId: __t.i64(),
  counterpartyUserId: __t.option(__t.i64()),
  status: __t.string(),
  currency: __t.string(),
  amountMinor: __t.i64(),
  completedAt: __t.option(__t.i64()),
  voidedAt: __t.option(__t.i64()),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateManualSettlement = __Infer<typeof StateManualSettlement>;

export const StateMessage = __t.object("StateMessage", {
  messageId: __t.string(),
  channelId: __t.string(),
  senderId: __t.string(),
  createdAt: __t.i64(),
  deleted: __t.bool(),
  deletedAt: __t.option(__t.i64()),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateMessage = __Infer<typeof StateMessage>;

export const StateMute = __t.object("StateMute", {
  muteKey: __t.string(),
  userId: __t.i64(),
  channelId: __t.string(),
  mutedBy: __t.i64(),
  active: __t.bool(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateMute = __Infer<typeof StateMute>;

export const StateOfflineMessage = __t.object("StateOfflineMessage", {
  messageId: __t.i64(),
  fromUserId: __t.option(__t.i64()),
  fromUsername: __t.string(),
  toUserId: __t.i64(),
  channelId: __t.string(),
  messageContent: __t.string(),
  messageType: __t.string(),
  gifUrl: __t.option(__t.string()),
  fileUrl: __t.option(__t.string()),
  fileName: __t.option(__t.string()),
  fileSize: __t.option(__t.i64()),
  messagePayloadJson: __t.option(__t.string()),
  createdAt: __t.i64(),
  expiresAt: __t.option(__t.i64()),
  delivered: __t.bool(),
});
export type StateOfflineMessage = __Infer<typeof StateOfflineMessage>;

export const StatePaymentAccountLink = __t.object("StatePaymentAccountLink", {
  accountLinkKey: __t.string(),
  userId: __t.i64(),
  workspaceId: __t.string(),
  pluginId: __t.string(),
  updatedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StatePaymentAccountLink = __Infer<typeof StatePaymentAccountLink>;

export const StatePaymentEvent = __t.object("StatePaymentEvent", {
  eventId: __t.string(),
  intentId: __t.string(),
  eventType: __t.string(),
  status: __t.option(__t.string()),
  source: __t.string(),
  idempotencyKey: __t.option(__t.string()),
  createdAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StatePaymentEvent = __Infer<typeof StatePaymentEvent>;

export const StatePaymentIntent = __t.object("StatePaymentIntent", {
  intentId: __t.string(),
  workspaceId: __t.string(),
  createdByUserId: __t.option(__t.i64()),
  channelId: __t.option(__t.string()),
  pluginId: __t.string(),
  providerName: __t.string(),
  providerIntentId: __t.option(__t.string()),
  amountMinor: __t.i64(),
  currency: __t.string(),
  countryCode: __t.option(__t.string()),
  status: __t.string(),
  checkoutMode: __t.string(),
  idempotencyKey: __t.option(__t.string()),
  failureCode: __t.option(__t.string()),
  failureMessage: __t.option(__t.string()),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StatePaymentIntent = __Infer<typeof StatePaymentIntent>;

export const StatePaymentPolicy = __t.object("StatePaymentPolicy", {
  policyKey: __t.string(),
  updatedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StatePaymentPolicy = __Infer<typeof StatePaymentPolicy>;

export const StatePaymentUserBlock = __t.object("StatePaymentUserBlock", {
  blockKey: __t.string(),
  userId: __t.i64(),
  workspaceId: __t.string(),
  blockedByUserId: __t.option(__t.i64()),
  blockedAt: __t.i64(),
  expiresAt: __t.option(__t.i64()),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StatePaymentUserBlock = __Infer<typeof StatePaymentUserBlock>;

export const StatePresenceLease = __t.object("StatePresenceLease", {
  stableUserId: __t.string(),
  dbUserId: __t.option(__t.i64()),
  instanceId: __t.string(),
  username: __t.option(__t.string()),
  color: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  status: __t.string(),
  connectedAt: __t.i64(),
  leaseExpiresAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StatePresenceLease = __Infer<typeof StatePresenceLease>;

export const StateRbacAssignment = __t.object("StateRbacAssignment", {
  assignmentKey: __t.string(),
  workspaceId: __t.string(),
  userId: __t.i64(),
  role: __t.string(),
  assignedBy: __t.option(__t.i64()),
  active: __t.bool(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateRbacAssignment = __Infer<typeof StateRbacAssignment>;

export const StateReaction = __t.object("StateReaction", {
  reactionId: __t.string(),
  messageId: __t.string(),
  channelId: __t.string(),
  userId: __t.i64(),
  emojiId: __t.string(),
  createdAt: __t.timestamp(),
});
export type StateReaction = __Infer<typeof StateReaction>;

export const StateRelay = __t.object("StateRelay", {
  relayId: __t.i64(),
  url: __t.string(),
  name: __t.string(),
  region: __t.string(),
  apiKeyHash: __t.string(),
  status: __t.string(),
  lastHealthPing: __t.option(__t.i64()),
  registeredAt: __t.i64(),
  approved: __t.bool(),
  latitude: __t.option(__t.f64()),
  longitude: __t.option(__t.f64()),
  bandwidthMbps: __t.option(__t.i64()),
  storageGb: __t.option(__t.i64()),
  syncthingDeviceId: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateRelay = __Infer<typeof StateRelay>;

export const StateRoleDefinition = __t.object("StateRoleDefinition", {
  roleKey: __t.string(),
  workspaceId: __t.string(),
  roleName: __t.string(),
  displayName: __t.string(),
  priority: __t.i64(),
  color: __t.option(__t.string()),
  isHoisted: __t.bool(),
  active: __t.bool(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateRoleDefinition = __Infer<typeof StateRoleDefinition>;

export const StateSession = __t.object("StateSession", {
  sessionId: __t.string(),
  userId: __t.option(__t.i64()),
  expiresAt: __t.option(__t.i64()),
  isTemporary: __t.bool(),
  deleted: __t.bool(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateSession = __Infer<typeof StateSession>;

export const StateSocketLease = __t.object("StateSocketLease", {
  stableUserId: __t.string(),
  dbUserId: __t.option(__t.i64()),
  instanceId: __t.string(),
  status: __t.string(),
  connectedAt: __t.i64(),
  leaseExpiresAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateSocketLease = __Infer<typeof StateSocketLease>;

export const StateThemePreferences = __t.object("StateThemePreferences", {
  userId: __t.i64(),
  themeId: __t.string(),
  customTheme: __t.option(__t.string()),
  uniformFontEnabled: __t.bool(),
  uniformFontFamily: __t.string(),
  uniformFontSize: __t.string(),
  uniformFontWeight: __t.string(),
  uniformFontStyle: __t.string(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateThemePreferences = __Infer<typeof StateThemePreferences>;

export const StateUser = __t.object("StateUser", {
  userId: __t.i64(),
  username: __t.option(__t.string()),
  usernameLc: __t.option(__t.string()),
  handle: __t.option(__t.string()),
  handleLc: __t.option(__t.string()),
  active: __t.bool(),
  deleted: __t.bool(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateUser = __Infer<typeof StateUser>;

export const StateUserEncryptionKey = __t.object("StateUserEncryptionKey", {
  userId: __t.i64(),
  publicKey: __t.string(),
  privateKeyEncrypted: __t.string(),
  createdAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateUserEncryptionKey = __Infer<typeof StateUserEncryptionKey>;

export const StateUserHandle = __t.object("StateUserHandle", {
  handleLc: __t.string(),
  userId: __t.i64(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateUserHandle = __Infer<typeof StateUserHandle>;

export const StateUserMeta = __t.object("StateUserMeta", {
  metaKey: __t.string(),
  nextUserId: __t.i64(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateUserMeta = __Infer<typeof StateUserMeta>;

export const StateUserSettings = __t.object("StateUserSettings", {
  userId: __t.i64(),
  offlineMessageRetention: __t.string(),
  allowTempUserMessages: __t.bool(),
  businessPrivateMode: __t.bool(),
  homeExperience: __t.string(),
  requirePasswordChange: __t.bool(),
  paymentPreferredRoute: __t.option(__t.string()),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateUserSettings = __Infer<typeof StateUserSettings>;

export const StateUserUsername = __t.object("StateUserUsername", {
  usernameLc: __t.string(),
  userId: __t.i64(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateUserUsername = __Infer<typeof StateUserUsername>;

export const StateWebhook = __t.object("StateWebhook", {
  webhookId: __t.i64(),
  userId: __t.i64(),
  name: __t.string(),
  targetUrl: __t.string(),
  secret: __t.string(),
  eventFilters: __t.string(),
  enabled: __t.bool(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateWebhook = __Infer<typeof StateWebhook>;

export const StateWebhookDelivery = __t.object("StateWebhookDelivery", {
  deliveryId: __t.i64(),
  webhookId: __t.i64(),
  eventType: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  attemptCount: __t.i64(),
  lastError: __t.option(__t.string()),
  responseCode: __t.option(__t.i64()),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
  deliveredAt: __t.option(__t.i64()),
  rowJson: __t.string(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateWebhookDelivery = __Infer<typeof StateWebhookDelivery>;

export const StateWhiteboard = __t.object("StateWhiteboard", {
  boardId: __t.string(),
  workspaceId: __t.string(),
  scopeType: __t.string(),
  scopeId: __t.string(),
  version: __t.i64(),
  documentJson: __t.string(),
  isPrivate: __t.bool(),
  createdBy: __t.option(__t.string()),
  updatedBy: __t.option(__t.string()),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
  lastUpdatedAt: __t.timestamp(),
});
export type StateWhiteboard = __Infer<typeof StateWhiteboard>;

