name: wabi
services:
- name: wabi
  source_dir: ./
  github:
    repo: AzureFoxStudios/wabi
    branch: main
    deploy_on_push: true
  build_command: ""
  dockerfile_path: Dockerfile
  http_port: 3000
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "3000"
    scope: RUN_AND_BUILD_TIME
  - key: FRONTEND_URL
    value: ${APP_DOMAIN}
    scope: RUN_AND_BUILD_TIME
  - key: PUBLIC_URL
    value: ${APP_DOMAIN}
    scope: RUN_AND_BUILD_TIME
