name: wabi
region: sgp

# Routes configuration - defines which service handles which paths
routes:
- path: /socket.io
  component:
    name: backend
- path: /api
  component:
    name: backend
- path: /uploads
  component:
    name: backend
- path: /emotes
  component:
    name: backend
- path: /
  component:
    name: web

services:

# Backend API and WebSocket server
- name: backend
  github:
    repo: AzureFoxStudios/wabi
    branch: main
    deploy_on_push: true
  source_dir: backend
  dockerfile_path: Dockerfile
  build_command: "npm install && npm run build"
  run_command: "node build"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs

  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "8080"
    scope: RUN_AND_BUILD_TIME
  - key: FRONTEND_URL
    value: https://${APP_DOMAIN}
    scope: RUN_AND_BUILD_TIME
  - key: PUBLIC_URL
    value: https://${APP_DOMAIN}
    scope: RUN_AND_BUILD_TIME
  - key: STATIC_DIR
    value: /app
    scope: RUN_AND_BUILD_TIME

# Frontend Nginx reverse proxy and static file server
- name: web
  github:
    repo: AzureFoxStudios/wabi
    branch: main
    deploy_on_push: true
  source_dir: frontend
  dockerfile_path: Dockerfile
  build_command: "npm install && npm run build"
  run_command: "npm run start"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs

  health_check:
    http_path: /
  envs:
  - key: VITE_SOCKET_URL
    value: https://${APP_DOMAIN}
    scope: BUILD_TIME
