export const QUEUE_ACTION = {
	SEND_MESSAGE: 'send-message',
	EDIT_MESSAGE: 'edit-message',
	DELETE_MESSAGE: 'delete-message',
	TOGGLE_PIN_MESSAGE: 'toggle-pin-message',
	ADD_REACTION: 'add-reaction',
	REMOVE_REACTION: 'remove-reaction',
	VOICE_CHANNEL_SUBSCRIBE: 'voice-channel-subscribe',
	VOICE_CHANNEL_LEAVE: 'voice-channel-leave',
	SET_VOICE_TRANSMIT_MODE: 'set-voice-transmit-mode',
	ASSIGN_ROLE: 'assign-role',
	REMOVE_ROLE: 'remove-role',
	BAN_USER: 'ban-user',
	CREATE_GROUP: 'create-group',
	LEAVE_GROUP: 'leave-group',
	KICK_GROUP_MEMBER: 'kick-group-member',
	ADD_GROUP_MEMBER: 'add-group-member',
	UPDATE_GROUP_AVATAR: 'update-group-avatar',
	PIN_CHANNEL: 'pin-channel',
	UNPIN_CHANNEL: 'unpin-channel',
	UPDATE_PROFILE: 'update-profile',
	DELETE_DM: 'delete-dm',
	MESSAGE: 'message',
	DELETE_EMOJI: 'delete-emoji',
	DELETE_EMOJI_ROLE_RULE: 'delete-emoji-role-rule',
	CLEAR_CHANNEL_MESSAGES: 'clear-channel-messages',
	RECEPTION_TOGGLE: 'reception-toggle',
} as const;

export type QueueAction = (typeof QUEUE_ACTION)[keyof typeof QUEUE_ACTION];
