/// <reference lib="webworker" />
import { calculate,columnName,cellKey,heads,renderFormula,literal,type WorkbookSnapshot,type Scalar } from './formula';
export interface ImportedCell{r:number;c:number;input:string;literal?:Scalar;cached?:Scalar;}
export interface ImportedSheet{name:string;rows:number;columns:number;cells:ImportedCell[];}
export interface ImportedWorkbook{sheets:ImportedSheet[];warnings:string[];}
function zipLimits(buffer:ArrayBuffer){const view=new DataView(buffer);let end=-1;for(let i=buffer.byteLength-22;i>=Math.max(0,buffer.byteLength-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw new Error('Invalid or unsupported Office archive.');const count=view.getUint16(end+10,true),offset=view.getUint32(end+16,true);if(count===65535||count>4096||offset>=buffer.byteLength)throw new Error('Office archive has too many entries or uses unsupported ZIP64.');let at=offset,total=0;for(let i=0;i<count;i++){if(at+46>buffer.byteLength||view.getUint32(at,true)!==0x02014b50)throw new Error('Invalid Office archive directory.');const flags=view.getUint16(at+8,true),compressed=view.getUint32(at+20,true),size=view.getUint32(at+24,true),name=view.getUint16(at+28,true),extra=view.getUint16(at+30,true),comment=view.getUint16(at+32,true);if(flags&1||size===0xffffffff||size>24*1024*1024||size>Math.max(1,compressed)*250)throw new Error('Encrypted or over-expanded Office archive is not supported.');total+=size;if(total>64*1024*1024)throw new Error('Office archive expands beyond the safe import limit.');at+=46+name+extra+comment;if(at>buffer.byteLength)throw new Error('Invalid Office archive entry.');}}
async function importBook(buffer:ArrayBuffer,name:string,delimiter?:string):Promise<ImportedWorkbook>{if(buffer.byteLength>12*1024*1024)throw new Error('Spreadsheet import is limited to 12 MB.');const ext=name.split('.').pop()?.toLowerCase();if(!['csv','tsv','xlsx','ods'].includes(ext||''))throw new Error('Supported imports are CSV, TSV, XLSX, and ODS.');if(ext==='xlsx'||ext==='ods')zipLimits(buffer);const XLSX=await import('xlsx');const text=ext==='csv'||ext==='tsv';const book=XLSX.read(text?new TextDecoder().decode(buffer):buffer,{type:text?'string':'array',raw:text,cellFormula:true,cellDates:false,cellNF:true,bookVBA:false,bookFiles:false,FS:delimiter||(ext==='tsv'?'\t':','),sheetRows:10001});if(book.SheetNames.length>20)throw new Error('This release supports up to 20 sheets.');let count=0;const warnings=['Imported copy: advanced formatting, external connections, macros, and embedded objects are not executed or preserved in the native model.','CSV/TSV columns remain text unless entered as numbers in Wabi.'];const sheets:ImportedSheet[]=book.SheetNames.map(sheetName=>{const sheet=book.Sheets[sheetName];const range=XLSX.utils.decode_range(sheet['!fullref']||sheet['!ref']||'A1');if(range.e.r>=10000||range.e.c>=256)throw new Error(`${sheetName} exceeds the supported 10,000-row / 256-column grid.`);const cells:ImportedCell[]=[];for(const address of Object.keys(sheet)){if(address.startsWith('!'))continue;const position=XLSX.utils.decode_cell(address),cell=sheet[address];if(++count>50000)throw new Error('Import is limited to 50,000 populated cells.');const value:Scalar=typeof cell.v==='number'||typeof cell.v==='boolean'||typeof cell.v==='string'?cell.v:null;const formula=typeof cell.f==='string'?cell.f:null;cells.push({r:position.r,c:position.c,input:formula?'='+formula:value===null?'':String(value),...(formula?{cached:value}:{literal:value})});}if(sheet['!merges']?.length)warnings.push(`${sheetName}: merged-cell layout was not imported; values are retained.`);return{name:sheetName,rows:Math.max(100,range.e.r+1),columns:Math.max(20,range.e.c+1),cells};});return{sheets,warnings};}
function safeText(value:Scalar){if(value===null)return '';const text=String(value);return typeof value==='string'&&/^[\s]*[=+@\-]/.test(text)?"'"+text:text;}
async function exportBook(book:WorkbookSnapshot,format:string,activeId:string){const XLSX=await import('xlsx');const calculated=calculate(book),output=XLSX.utils.book_new();for(const sheet of book.sheets){if((format==='csv'||format==='tsv')&&sheet.id!==activeId)continue;const ws:XLSX.WorkSheet={};for(let r=0;r<sheet.rows.length;r++)for(let c=0;c<sheet.columns.length;c++){const id=cellKey(sheet.rows[r].id,sheet.columns[c].id),versions=heads(sheet.cells[id]||[]);if(!versions.length)continue;if(versions.length>1)throw new Error('Resolve conflicting cells before exporting a workbook.');const v=versions[0],calcId=`${sheet.id}/${id}`,error=calculated.errors[calcId],value=calculated.values[calcId]??null;const address=columnName(c)+(r+1);if(format==='csv'||format==='tsv'){ws[address]={t:'s',v:safeText(error||value)};}else if(v.expression||v.input.startsWith('=')){ws[address]={t:typeof value==='string'?'s':typeof value==='boolean'?'b':'n',f:(v.expression?renderFormula(v.expression,book,sheet.id):v.input).slice(1),...(!error&&value!==null?{v:value}:{})};}else{const val=v.literal!==undefined?v.literal:literal(v.input);ws[address]={t:typeof val==='number'?'n':typeof val==='boolean'?'b':'s',v:val??''};}}
    ws['!ref']=`A1:${columnName(sheet.columns.length-1)}${sheet.rows.length}`;const name=sheet.name.replace(/[\\/?*\[\]:]/g,' ').slice(0,31)||'Sheet';let safe=name,suffix=1;while(output.SheetNames.includes(safe))safe=name.slice(0,26)+' '+suffix++;XLSX.utils.book_append_sheet(output,ws,safe);
}if(format==='csv'||format==='tsv'){return{type:'text/plain;charset=utf-8',bytes:new TextEncoder().encode(XLSX.utils.sheet_to_csv(output.Sheets[output.SheetNames[0]],{FS:format==='tsv'?'\t':',',blankrows:false})).buffer};}if(!['xlsx','ods'].includes(format))throw new Error('Unsupported export format');return{type:'application/octet-stream',bytes:XLSX.write(output,{type:'array',bookType:format as 'xlsx'|'ods',compression:true}) as ArrayBuffer};}
self.onmessage=async(event:MessageEvent)=>{const{id,type,payload}=event.data;try{const result=type==='calculate'?calculate(payload):type==='import'?await importBook(payload.buffer,payload.name,payload.delimiter):type==='export'?await exportBook(payload.book,payload.format,payload.activeId):(()=>{throw new Error('Unknown spreadsheet operation');})();postMessage({id,result},type==='export'?[(result as {bytes:ArrayBuffer}).bytes]:[]);}catch(error){postMessage({id,error:error instanceof Error?error.message:String(error)});}};
