import * as Y from 'yjs';
import { cellKey,heads,literal,parseFormula,renderFormula,shiftFormula,type Axis,type CellVersion,type Expr,type WorkbookSnapshot,type SheetSnapshot,type Scalar } from './formula';
export interface CellStyle{bold?:boolean;italic?:boolean;format?:'general'|'number'|'percent'|'currency'|'text';align?:'left'|'center'|'right';fill?:string;wrap?:boolean;}
export type YSheet=Y.Map<unknown>;
const uid=()=>crypto.randomUUID();
function map<T>(parent:Y.Map<unknown>,name:string):Y.Map<T>{const value=parent.get(name);if(!(value instanceof Y.Map))throw new Error(`Workbook is missing ${name}`);return value as Y.Map<T>;}
export function sheets(data:Y.Map<unknown>){return map<YSheet>(data,'sheets');}
export function axes(sheet:YSheet,kind:'rows'|'columns'):Axis[]{return Array.from(map<Axis>(sheet,kind),([id,v])=>({...v,id})).filter(v=>!v.removed).sort((a,b)=>a.position-b.position||a.id.localeCompare(b.id));}
export function orderedSheets(data:Y.Map<unknown>){return Array.from(sheets(data),([id,value])=>({id,value})).filter(v=>!v.value.get('removed')).sort((a,b)=>Number(a.value.get('position'))-Number(b.value.get('position'))||a.id.localeCompare(b.id));}
export function initialize(data:Y.Map<unknown>){data.set('schema',1);data.set('sheets',new Y.Map<YSheet>());addSheet(data,'Sheet 1',100,20);}
export function addSheet(data:Y.Map<unknown>,name:string,rows=100,columns=20){const collection=sheets(data);if(collection.size>=20)throw new Error('This release supports up to 20 sheets.');if(rows>10000||columns>256||rows<1||columns<1)throw new Error('Sheet exceeds the supported grid dimensions.');const sheet=new Y.Map<unknown>(),id=uid();collection.set(id,sheet);sheet.set('name',name.slice(0,100));sheet.set('position',collection.size);sheet.set('rows',new Y.Map());sheet.set('columns',new Y.Map());sheet.set('ops',new Y.Map());sheet.set('styles',new Y.Map());sheet.set('structureEdits',new Y.Map());for(let i=0;i<rows;i++){const id=uid();map<Axis>(sheet,'rows').set(id,{id,position:i});}for(let i=0;i<columns;i++){const id=uid();map<Axis>(sheet,'columns').set(id,{id,position:i});}return{id,sheet};}
export function snapshot(data:Y.Map<unknown>):WorkbookSnapshot{return{sheets:orderedSheets(data).map(({id,value})=>{const cells:Record<string,CellVersion[]>={};for(const[opId,op]of map<CellVersion>(value,'ops'))(cells[op.cell]||=[]).push({...op,id:opId});return{id,name:String(value.get('name')||'Sheet'),rows:axes(value,'rows'),columns:axes(value,'columns'),cells};})};}
export function versions(sheet:YSheet,row:string,column:string){const cell=cellKey(row,column);return heads(Array.from(map<CellVersion>(sheet,'ops'),([id,v])=>({...v,id})).filter(v=>v.cell===cell));}
export function inputOf(version:CellVersion|undefined,book:WorkbookSnapshot,sheetId:string){return version?.expression?renderFormula(version.expression,book,sheetId):version?.input||'';}
export function setCell(data:Y.Map<unknown>,sheetId:string,row:string,column:string,input:string,origin:unknown,prepared?:{expression?:Expr;literal?:Scalar;cached?:Scalar;imported?:boolean}){
    if(input.length>8192)throw new Error('A cell may contain at most 8,192 characters.');const sheet=sheets(data).get(sheetId);if(!sheet)throw new Error('Sheet was deleted.');if(!axes(sheet,'rows').some(r=>r.id===row)||!axes(sheet,'columns').some(c=>c.id===column))throw new Error('The target row or column was removed. Your entry has not been moved to another cell.');
    const ops=map<CellVersion>(sheet,'ops');if(ops.size>=200000)throw new Error('Workbook edit history has reached its supported limit. Export a copy before continuing.');const old=versions(sheet,row,column);let expression=prepared?.expression,parseError:string|undefined;
    if(input.startsWith('=')&&!expression){try{expression=parseFormula(input,snapshot(data),sheetId);}catch(error){parseError=error instanceof Error?error.message:'#UNSUPPORTED!';}}
    const id=uid(),version:CellVersion={id,cell:cellKey(row,column),input,parents:old.map(v=>v.id),...(expression?{expression}:{}),...(parseError?{parseError}:{}),...(prepared||{})};
    data.doc!.transact(()=>ops.set(id,version),origin);
}
export function paste(data:Y.Map<unknown>,sheetId:string,startRow:number,startColumn:number,values:string[][],origin:unknown){const sheet=sheets(data).get(sheetId);if(!sheet)throw new Error('Sheet unavailable');const rows=axes(sheet,'rows'),columns=axes(sheet,'columns');if(values.length>10000||values.reduce((n,row)=>n+row.length,0)>20000)throw new Error('Paste is limited to 20,000 cells per operation.');if(startRow+values.length>rows.length||values.some(row=>startColumn+row.length>columns.length))throw new Error('Add enough rows and columns before pasting; nothing was changed.');for(const row of values)for(const value of row)if(value.length>8192)throw new Error('Pasted cell exceeds the text limit.');data.doc!.transact(()=>{for(let r=0;r<values.length;r++)for(let c=0;c<values[r].length;c++)setCell(data,sheetId,rows[startRow+r].id,columns[startColumn+c].id,values[r][c],origin);},origin);}
export function insertAxis(data:Y.Map<unknown>,sheetId:string,kind:'rows'|'columns',index:number,origin:unknown){const sheet=sheets(data).get(sheetId);if(!sheet)throw new Error('Sheet unavailable');const list=axes(sheet,kind);if(list.length>=(kind==='rows'?10000:256))throw new Error('Grid dimension limit reached');const previous=list[index-1]?.position??((list[0]?.position||0)-2),next=list[index]?.position??previous+2;const position=(previous+next)/2;if(position===previous||position===next)throw new Error('This insertion position is exhausted; export and reimport a normalized copy.');const id=uid();data.doc!.transact(()=>{map<Axis>(sheet,kind).set(id,{id,position});map<string>(sheet,'structureEdits').set(uid(),'insert');},origin);return id;}
export function removeAxis(data:Y.Map<unknown>,sheetId:string,kind:'rows'|'columns',id:string,origin:unknown){const sheet=sheets(data).get(sheetId);if(!sheet)throw new Error('Sheet unavailable');if(axes(sheet,kind).length<=1)throw new Error('A sheet needs at least one row and column.');const target=map<Axis>(sheet,kind),before=target.get(id);if(!before)return;data.doc!.transact(()=>{target.set(id,{...before,removed:true});map<string>(sheet,'structureEdits').set(uid(),'remove');},origin);}
export function styleOf(sheet:YSheet,row:string,column:string):CellStyle{return map<CellStyle>(sheet,'styles').get(cellKey(row,column))||{};}
export function setStyle(data:Y.Map<unknown>,sheetId:string,cells:{row:string;column:string}[],patch:CellStyle,origin:unknown){const sheet=sheets(data).get(sheetId);if(!sheet)return;const styles=map<CellStyle>(sheet,'styles');data.doc!.transact(()=>{for(const cell of cells){const key=cellKey(cell.row,cell.column);styles.set(key,{...(styles.get(key)||{}),...patch});}},origin);}
export function fill(data:Y.Map<unknown>,sheetId:string,from:{r:number;c:number},to:{r:number;c:number},origin:unknown){const book=snapshot(data),ss=book.sheets.find(s=>s.id===sheetId);if(!ss)return;const source=heads(ss.cells[cellKey(ss.rows[from.r].id,ss.columns[from.c].id)]||[]);if(source.length!==1)throw new Error('Choose one non-conflicting source cell.');const v=source[0];const expression=v.expression?shiftFormula(v.expression,book,to.r-from.r,to.c-from.c):undefined;setCell(data,sheetId,ss.rows[to.r].id,ss.columns[to.c].id,expression?renderFormula(expression,book,sheetId):v.input,origin,expression?{expression}:undefined);}
export function cachedResultIsStale(data:Y.Map<unknown>){for(const {value}of orderedSheets(data)){if(map<string>(value,'structureEdits').size)return true;for(const op of map<CellVersion>(value,'ops').values())if(!op.imported)return true;}return false;}
export function recoverRemoved(sheet:YSheet){const rows=new Set(axes(sheet,'rows').map(r=>r.id)),cols=new Set(axes(sheet,'columns').map(c=>c.id));return Array.from(map<CellVersion>(sheet,'ops').values()).filter(v=>{const[r,c]=v.cell.split('|');return !rows.has(r)||!cols.has(c);});}
export function formatValue(value:Scalar,style:CellStyle){if(value===null)return '';if(typeof value!=='number')return String(value);switch(style.format){case'number':return value.toLocaleString('en-US',{maximumFractionDigits:4});case'percent':return value.toLocaleString('en-US',{style:'percent',maximumFractionDigits:2});case'currency':return value.toLocaleString('en-US',{style:'currency',currency:'USD'});default:return String(value);}}
export {Y,cellKey,heads,literal};
