<script lang="ts">
    import { onMount,onDestroy } from 'svelte';
    import ArtifactShell from '../ArtifactShell.svelte';
    import ArtifactLibrary from '../ArtifactLibrary.svelte';
    import SheetsGrid from './SheetsGrid.svelte';
    import { ArtifactSession,createArtifact,openArtifact,download,from64,Y } from '../session';
    import { captureScope,targets,type Scope } from '../bridge';
    import { initialize,snapshot,addSheet,axes,sheets } from './model';
    import { parseFormula,type CellVersion } from './formula';
    import { SheetWorker } from './workerClient';
    import type { ImportedWorkbook } from './engine.worker';
    import '../workspace.css';
    let scope=$state<Scope|null>(null),active=$state<ArtifactSession|null>(null);let busy=$state(false),error=$state('');let format=$state('xlsx');let importData=$state<ImportedWorkbook|null>(null),importFile=$state<File|null>(null);let dialog:HTMLDialogElement;let delimiter=$state(',');let previousTarget:unknown;let stopped=false;const worker=new SheetWorker();
    async function run(fn:()=>Promise<void>){error='';busy=true;try{await fn();}catch(e){error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
    async function use(session:ArtifactSession){if(stopped||!scope?.isCurrent()){await session.close();return;}if(active&&active!==session&&!(await active.close()))throw new Error('Save or export recovery before closing the current spreadsheet.');active=session;}
    async function create(){if(scope)await use(await createArtifact(scope,'sheets','Untitled spreadsheet',doc=>initialize(doc.getMap('data'))));}
    async function open(id:string){if(scope)await use(await openArtifact(scope,id,'sheets'));}
    async function library(){if(active&&!(await active.close())){error='Local save failed. Export recovery before leaving.';return;}active=null;}
    async function loadFile(file:File){if(!scope)return;if(file.name.endsWith('.wabi.json')){if(file.size>24*1024*1024)throw new Error('Backup exceeds the supported import size.');const value=JSON.parse(await file.text());if(value.schema!==1||value.kind!=='sheets'||typeof value.update!=='string')throw new Error('Not a Wabi spreadsheet backup.');const source=new Y.Doc();try{Y.applyUpdate(source,from64(value.update));const data=source.getMap('data');if(data.get('schema')!==1||!(data.get('sheets') instanceof Y.Map))throw new Error('Unsupported workbook schema.');await use(await createArtifact(scope,'sheets',source.getText('title').toString(),doc=>{const target=doc.getMap('data');for(const[key,item]of data)target.set(key,item instanceof Y.AbstractType?item.clone():item);},'native',undefined,{name:file.name,type:file.type,blob:file}));}finally{source.destroy();}return;}
        importFile=file;importData=await worker.run<ImportedWorkbook>('import',{buffer:await file.arrayBuffer(),name:file.name,delimiter:file.name.toLowerCase().endsWith('.tsv')?'\t':delimiter});dialog.showModal();}
    async function confirmImport(){if(!scope||!importData||!importFile)return;const data=importData,file=importFile;const session=await createArtifact(scope,'sheets',file.name,doc=>{
        const root=doc.getMap('data');root.set('schema',1);root.set('sheets',new Y.Map());const created=data.sheets.map(sheet=>addSheet(root,sheet.name,sheet.rows,sheet.columns));const book=snapshot(root);
        doc.transact(()=>{data.sheets.forEach((source,index)=>{const target=created[index],rows=axes(target.sheet,'rows'),columns=axes(target.sheet,'columns'),ops=target.sheet.get('ops') as Y.Map<CellVersion>;
            for(const cell of source.cells){const id=crypto.randomUUID();const version:CellVersion={id,cell:`${rows[cell.r].id}|${columns[cell.c].id}`,input:cell.input,parents:[],imported:true,...(cell.literal!==undefined?{literal:cell.literal}:{}),...(cell.cached!==undefined?{cached:cell.cached}:{})};if(cell.input.startsWith('=')&&cell.literal===undefined){try{version.expression=parseFormula(cell.input,book,target.id);}catch(e){version.parseError=e instanceof Error?e.message:'#UNSUPPORTED!';}}ops.set(id,version);}
        });});
    },'native',undefined,{name:file.name,type:file.type,blob:file});await use(session);importData=null;importFile=null;dialog.close();worker.close();}
    async function exportFile(){if(!active)return;await active.flush();const book=snapshot(active.data);if(!book.sheets.length)throw new Error('Workbook is empty.');const result=await worker.run<{bytes:ArrayBuffer;type:string}>('export',{book,format,activeId:book.sheets[0].id});download(`${active.title}.${format}`,new Blob([result.bytes],{type:result.type}));worker.close();}
    onMount(()=>{let unsubscribe=()=>{};void run(async()=>{scope=await captureScope();unsubscribe=targets.subscribe(value=>{if(value.sheets&&value.sheets!==previousTarget){previousTarget=value.sheets;if(value.sheets.id)void run(()=>open(value.sheets!.id!));}});});return()=>unsubscribe();});
    onDestroy(()=>{stopped=true;worker.close();if(active)void active.close();});
</script>
{#if scope&&active}{#key active.id}<ArtifactShell session={active} onlibrary={()=>void library()}><div class="workspace-toolbar exports"><select aria-label="Spreadsheet export format" bind:value={format}><option value="xlsx">XLSX supported subset</option><option value="ods">ODS supported subset</option><option value="csv">CSV — first sheet</option><option value="tsv">TSV — first sheet</option></select><button disabled={busy} onclick={()=>void run(exportFile)}>Export spreadsheet</button><small>Exports preserve supported values and formulas; advanced Office layout is not a lossless round trip.</small></div><div class="grid-host"><SheetsGrid session={active}/></div></ArtifactShell>{/key}
{:else if scope}<section class="wabi-workspace"><ArtifactLibrary {scope} kind="sheets" label="Sheets" onopen={id=>void run(()=>open(id))} onnew={()=>void run(create)} onimport={file=>void run(()=>loadFile(file))} accept=".csv,.tsv,.xlsx,.ods,.wabi.json"/><label class="workspace-home-note">CSV delimiter <select bind:value={delimiter}><option value=",">Comma</option><option value=";">Semicolon</option><option value="\t">Tab</option></select></label></section>{/if}
{#if busy}<div class="workspace-home-note" role="status">Working on this device… <button onclick={()=>worker.close()}>Cancel file operation</button></div>{/if}{#if error}<div class="workspace-home-note" role="alert">{error}</div>{/if}
<dialog class="workspace-dialog" bind:this={dialog}><h2>Import preview</h2><p>The original is retained. Confirming creates a private editable Wabi copy; it does not upload the file.</p>{#if importData}{#each importData.warnings as warning}<p>{warning}</p>{/each}{#each importData.sheets as sheet}<h3>{sheet.name}</h3><p>{sheet.rows} rows · {sheet.columns} columns · {sheet.cells.length} populated cells</p><table><tbody>{#each [0,1,2,3,4] as r}<tr>{#each [0,1,2,3,4] as c}<td>{sheet.cells.find(cell=>cell.r===r&&cell.c===c)?.input||''}</td>{/each}</tr>{/each}</tbody></table>{/each}{/if}<div class="workspace-toolbar"><button disabled={busy} onclick={()=>{dialog.close();importData=null;importFile=null;worker.close();}}>Cancel</button><button class="primary" disabled={busy} onclick={()=>void run(confirmImport)}>Create private spreadsheet</button></div>{#if error}<p role="alert">{error}</p>{/if}</dialog>
<style>.exports{padding:.5rem;font-size:.8rem}.exports small{color:var(--text-secondary,#b5bad0)}.grid-host{height:calc(100% - 52px);min-height:300px}dialog table{border-collapse:collapse;max-width:100%}dialog td{border:1px solid var(--border-subtle,#444);padding:.3rem;max-width:90px;overflow:hidden;white-space:nowrap}</style>
