<script lang="ts">
    import { onDestroy } from 'svelte';
    import type { ArtifactSession } from '../session';
    import { download } from '../session';
    import { orderedSheets,snapshot,sheets,axes,setCell,setStyle,styleOf,formatValue,addSheet,insertAxis,removeAxis,fill,recoverRemoved,cachedResultIsStale,cellKey,heads,inputOf,type CellStyle } from './model';
    import { columnName,type Calculation,type Scalar } from './formula';
    import { SheetWorker } from './workerClient';
    let {session}:{session:ArtifactSession}=$props();const sessionState=session.state;
    let sheetId=$state('');let selectedRow=$state('');let selectedColumn=$state('');let endRow=$state('');let endColumn=$state('');let filter=$state('');let sort=$state<'none'|'asc'|'desc'>('none');let scrollTop=$state(0);let viewportHeight=$state(600);let grid:HTMLDivElement;let formulaInput:HTMLInputElement;
    let draft=$state('');let editing=$state(false);let editingTarget:{sheet:string;row:string;column:string;parents:string[]}|null=null;let error=$state('');let chart=$state<'none'|'bar'|'line'|'pie'>('none');let calculations=$state<Calculation>({values:{},errors:{}});let calculating=$state(false);let calculationId=0;let calculationTimer:ReturnType<typeof setTimeout>|undefined;
    const engine=new SheetWorker();const available=$derived(($sessionState.tick,orderedSheets(session.data)));const book=$derived(($sessionState.tick,snapshot(session.data)));const current=$derived(book.sheets.find(s=>s.id===sheetId)||book.sheets[0]);const ysheet=$derived(current?sheets(session.data).get(current.id):undefined);const editable=$derived(($sessionState.meta,session.editable));
    const rows=$derived.by(()=>{if(!current)return[];let rows=current.rows;if(filter){const q=filter.toLocaleLowerCase();rows=rows.filter(row=>current.columns.some(col=>value(row.id,col.id).toLocaleLowerCase().includes(q)));}if(sort!=='none'&&selectedColumn){rows=[...rows].sort((a,b)=>value(a.id,selectedColumn).localeCompare(value(b.id,selectedColumn),undefined,{numeric:true})*(sort==='asc'?1:-1));}return rows;});
    const first=$derived(Math.max(0,Math.floor(scrollTop/32)-5));const last=$derived(Math.min(rows.length,first+Math.ceil(viewportHeight/32)+12));const visible=$derived(rows.slice(first,last));
    const selectedVersions=$derived(current?heads(current.cells[cellKey(selectedRow,selectedColumn)]||[]):[]);
    const selection=$derived.by(()=>{if(!current)return[];const a=rows.findIndex(r=>r.id===selectedRow),b=rows.findIndex(r=>r.id===(endRow||selectedRow)),c=current.columns.findIndex(c=>c.id===selectedColumn),d=current.columns.findIndex(c=>c.id===(endColumn||selectedColumn));if(Math.min(a,b,c,d)<0)return[];const selected:{row:string;column:string}[]=[];for(let r=Math.min(a,b);r<=Math.max(a,b);r++)for(let x=Math.min(c,d);x<=Math.max(c,d);x++)selected.push({row:rows[r].id,column:current.columns[x].id});return selected;});
    const selectedSet=$derived(new Set(selection.map(v=>cellKey(v.row,v.column))));
    $effect(()=>{if(current&&!current.rows.some(r=>r.id===selectedRow)){selectedRow=current.rows[0]?.id||'';endRow='';}if(current&&!current.columns.some(c=>c.id===selectedColumn)){selectedColumn=current.columns[0]?.id||'';endColumn='';}});
    $effect(()=>{if(!editing&&current)draft=selectedVersions.length===1?inputOf(selectedVersions[0],book,current.id):'';});
    $effect(()=>{const source=book;const id=++calculationId;if(calculationTimer)clearTimeout(calculationTimer);calculating=true;calculationTimer=setTimeout(()=>{void engine.run<Calculation>('calculate',source).then(result=>{if(id===calculationId){calculations=result;calculating=false;}}).catch(e=>{if(id===calculationId){error=e.message;calculating=false;}});},180);});
    onDestroy(()=>{calculationId++;if(calculationTimer)clearTimeout(calculationTimer);engine.close();});
    function attempt(fn:()=>void){error='';try{fn();}catch(e){error=e instanceof Error?e.message:String(e);}}
    function value(row:string,column:string):string{if(!current||!ysheet)return'';const key=`${current.id}/${cellKey(row,column)}`,v=heads(current.cells[cellKey(row,column)]||[]);if(v.length>1)return '#CONFLICT!';if(calculations.errors[key])return v[0]?.cached!==undefined?`${String(v[0].cached??'')} ${cachedResultIsStale(session.data)?'STALE':'†'}`:calculations.errors[key];return formatValue(calculations.values[key]??(v[0]?.literal??null),styleOf(ysheet,row,column));}
    function choose(row:string,column:string,extend=false){if(editing&&!commit())return;grid?.focus();if(extend){endRow=row;endColumn=column;}else{selectedRow=row;selectedColumn=column;endRow='';endColumn='';}editing=false;}
    function commit():boolean{if(!editing)return true;if(!editingTarget||!editable){error='Editing permission changed. Copy the unsent cell text before leaving.';return false;}try{const target=editingTarget;setCell(session.data,target.sheet,target.row,target.column,draft,session.origin,undefined,target.parents);editing=false;editingTarget=null;error='';return true;}catch(e){error=e instanceof Error?e.message:String(e);return false;}}
    function beginEdit(){if(!editable||!current)return;if(!editingTarget)editingTarget={sheet:current.id,row:selectedRow,column:selectedColumn,parents:selectedVersions.map(v=>v.id)};editing=true;}
    function startEdit(){if(!editable)return;beginEdit();formulaInput?.focus();formulaInput?.select();}
    function style(patch:CellStyle){if(current&&editable)attempt(()=>setStyle(session.data,current.id,selection,patch,session.origin));}
    async function copy(){if(!current)return;const rowIds=[...new Set(selection.map(v=>v.row))],colIds=[...new Set(selection.map(v=>v.column))];const escape=(s:string)=>/[\t\r\n"]/.test(s)?`"${s.replaceAll('"','""')}"`:s;const text=rowIds.map(r=>colIds.map(c=>escape(value(r,c))).join('\t')).join('\n');try{await navigator.clipboard.writeText(text);}catch(e){error='Clipboard access was denied. Use the export controls instead.';}}
    function parseTsv(text:string){const rows:string[][]=[[]];let field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&(quoted||field==='')){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c==='\t'||c==='\n')){rows[rows.length-1].push(field.replace(/\r$/,''));field='';if(c==='\n')rows.push([]);}else field+=c;}rows[rows.length-1].push(field.replace(/\r$/,''));if(rows.length>1&&rows[rows.length-1].length===1&&rows[rows.length-1][0]==='')rows.pop();if(quoted)throw new Error('Pasted table has an unclosed quote.');return rows;}
    function paste(event:ClipboardEvent){if(!editable||!current||event.target===formulaInput)return;event.preventDefault();attempt(()=>{const cells=parseTsv(event.clipboardData?.getData('text/plain')||'');if(cells.reduce((n,r)=>n+r.length,0)>2000)throw new Error('Paste up to 2,000 cells at once; use file import for larger tables.');const ri=rows.findIndex(r=>r.id===selectedRow),ci=current!.columns.findIndex(c=>c.id===selectedColumn);if(ri+cells.length>rows.length||cells.some(r=>ci+r.length>current!.columns.length))throw new Error('Add rows or columns before pasting. Nothing was changed.');for(const r of cells)for(const v of r)if(v.length>8192)throw new Error('A pasted cell exceeds the text limit.');session.doc.transact(()=>{for(let r=0;r<cells.length;r++)for(let c=0;c<cells[r].length;c++)setCell(session.data,current!.id,rows[ri+r].id,current!.columns[ci+c].id,cells[r][c],session.origin);},session.origin);});}
    function keydown(event:KeyboardEvent){if(event.target===formulaInput)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='c'){event.preventDefault();void copy();return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'){event.preventDefault();if(current&&rows.length){selectedRow=rows[0].id;selectedColumn=current.columns[0].id;endRow=rows.at(-1)!.id;endColumn=current.columns.at(-1)!.id;}return;}if(event.key==='F2'||event.key==='Enter'){event.preventDefault();startEdit();return;}if(!current)return;let r=rows.findIndex(v=>v.id===selectedRow),c=current.columns.findIndex(v=>v.id===selectedColumn);const direction:Record<string,[number,number]>={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1],Tab:[0,event.shiftKey?-1:1]};if(direction[event.key]){event.preventDefault();r=Math.max(0,Math.min(rows.length-1,r+direction[event.key][0]));c=Math.max(0,Math.min(current.columns.length-1,c+direction[event.key][1]));if(rows[r])choose(rows[r].id,current.columns[c].id,event.shiftKey&&event.key!=='Tab');if(r*32<grid.scrollTop)grid.scrollTop=r*32;else if(r*32>grid.scrollTop+grid.clientHeight-96)grid.scrollTop=r*32-grid.clientHeight+96;return;}if(editable&&(event.key==='Delete'||event.key==='Backspace')){event.preventDefault();attempt(()=>{if(selection.length>2000)throw new Error('Clear up to 2,000 cells at once.');session.doc.transact(()=>{for(const cell of selection)setCell(session.data,current!.id,cell.row,cell.column,'',session.origin);},session.origin);});return;}if(editable&&event.key.length===1&&!event.ctrlKey&&!event.metaKey&&!event.altKey){event.preventDefault();beginEdit();draft=event.key;formulaInput.focus();}}
    function axis(kind:'rows'|'columns',remove=false){if(!current)return;attempt(()=>{if(remove)removeAxis(session.data,current!.id,kind,kind==='rows'?selectedRow:selectedColumn,session.origin);else insertAxis(session.data,current!.id,kind,(kind==='rows'?current!.rows:current!.columns).findIndex(v=>v.id===(kind==='rows'?selectedRow:selectedColumn))+1,session.origin);});}
    function fillDown(){if(!current)return;attempt(()=>{const r=current!.rows.findIndex(v=>v.id===selectedRow),c=current!.columns.findIndex(v=>v.id===selectedColumn);if(r>=current!.rows.length-1)throw new Error('Add a row before filling down.');fill(session.data,current!.id,{r,c},{r:r+1,c},session.origin);});}
    const chartData=$derived.by(()=>{if(!current)return[];const rs=[...new Set(selection.map(v=>v.row))].slice(0,30),cs=[...new Set(selection.map(v=>v.column))];if(cs.length<2)return[];return rs.map(r=>({label:value(r,cs[0]),value:calculations.values[`${current.id}/${cellKey(r,cs[1])}`]})).filter((v):v is {label:string;value:number}=>typeof v.value==='number'&&Number.isFinite(v.value));});
    const maxValue=$derived(Math.max(1,...chartData.map(v=>Math.abs(v.value))));
    function piePath(index:number){const positive=chartData.map(v=>Math.max(0,v.value)),total=positive.reduce((a,b)=>a+b,0);if(!total)return'';const begin=positive.slice(0,index).reduce((a,b)=>a+b,0)/total*Math.PI*2-Math.PI/2,end=begin+positive[index]/total*Math.PI*2;const x=(a:number)=>200+110*Math.cos(a),y=(a:number)=>140+110*Math.sin(a);return `M200 140 L${x(begin)} ${y(begin)} A110 110 0 ${end-begin>Math.PI?1:0} 1 ${x(end)} ${y(end)} Z`;}
</script>
<div class="sheets-editor">
    <div class="workspace-toolbar sheet-tools"><select aria-label="Active sheet" value={current?.id} onchange={event=>{if(!commit()){event.currentTarget.value=current?.id||'';return;}sheetId=event.currentTarget.value;scrollTop=0;filter='';sort='none';}}>{#each available as item(item.id)}<option value={item.id}>{String(item.value.get('name'))}</option>{/each}</select>
        <button disabled={!editable} onclick={()=>attempt(()=>{session.doc.transact(()=>{const made=addSheet(session.data,`Sheet ${available.length+1}`);sheetId=made.id;},session.origin);})}>+ Sheet</button>
        {#if ysheet}<input aria-label="Sheet name" value={String(ysheet.get('name'))} disabled={!editable} maxlength="100" onchange={event=>{const name=event.currentTarget.value.trim();if(name&&ysheet)session.doc.transact(()=>ysheet!.set('name',name),session.origin);}}/>{/if}
        <button disabled={!editable} onclick={()=>style({bold:true})}>Bold</button><button disabled={!editable} onclick={()=>style({bold:false,italic:false})}>Plain</button><button disabled={!editable} onclick={()=>style({italic:true})}>Italic</button>
        <select aria-label="Cell number format" disabled={!editable} onchange={event=>style({format:event.currentTarget.value as CellStyle['format']})}><option value="general">General</option><option value="number">Number</option><option value="currency">USD currency</option><option value="percent">Percent</option><option value="text">Text</option></select>
        <select aria-label="Cell alignment" disabled={!editable} onchange={event=>style({align:event.currentTarget.value as CellStyle['align']})}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select>
        <button disabled={!editable} onclick={()=>axis('rows')}>Insert row</button><button disabled={!editable} onclick={()=>axis('columns')}>Insert column</button><button disabled={!editable} onclick={()=>axis('rows',true)}>Delete row</button><button disabled={!editable} onclick={()=>axis('columns',true)}>Delete column</button><button disabled={!editable} onclick={fillDown}>Fill down</button><button onclick={()=>void copy()}>Copy range</button>
    </div>
    <div class="workspace-toolbar sheet-tools"><input aria-label="Filter my view" placeholder="Filter my view…" bind:value={filter}/><select aria-label="Sort my view by selected column" bind:value={sort}><option value="none">Original row order</option><option value="asc">Selected column: ascending</option><option value="desc">Selected column: descending</option></select><select aria-label="Chart selected range" bind:value={chart}><option value="none">No chart</option><option value="bar">Bar chart</option><option value="line">Line chart</option><option value="pie">Pie chart</option></select><span>{selection.length} selected · {calculating?'Calculating…':'Calculated'} · † Imported cached result; STALE means the workbook changed and that result must not be trusted</span></div>
    <form class="formula-bar" onsubmit={event=>{event.preventDefault();commit();grid?.focus();}}><span>{current?`${columnName(current.columns.findIndex(c=>c.id===selectedColumn))}${current.rows.findIndex(r=>r.id===selectedRow)+1}`:''}</span><input aria-label="Cell value or formula" bind:this={formulaInput} bind:value={draft} disabled={!editable} onfocus={beginEdit} onblur={commit} onkeydown={event=>{if(event.key==='Escape'){editing=false;editingTarget=null;draft=selectedVersions.length===1&&current?inputOf(selectedVersions[0],book,current.id):'';grid.focus();}}}/><button disabled={!editable}>Apply</button></form>
    {#if error}<p class="workspace-notice" role="alert">{error}</p>{/if}
    {#if selectedVersions.length>1}<div class="workspace-notice" role="alert"><span>This cell has competing edits. Choose one, or enter a replacement; every alternative remains in the saved history.</span>{#each selectedVersions as version(version.id)}<button disabled={!editable} onclick={()=>attempt(()=>{if(current)setCell(session.data,current.id,selectedRow,selectedColumn,version.input,session.origin,version.expression?{expression:version.expression}:undefined);})}>{version.input||'(empty)'}</button>{/each}</div>{/if}
    {#if chart!=='none'}<section class="sheet-chart" aria-label="Selected range chart">{#if chartData.length}<svg viewBox="0 0 600 300" role="img" aria-label={`${chart} chart of the selected two-column range`}>
        {#if chart==='bar'}{#each chartData as item,i}<rect x={30+i*540/chartData.length} y={250-Math.max(0,item.value)/maxValue*210} width={Math.max(2,450/chartData.length)} height={Math.abs(item.value)/maxValue*210} fill="currentColor"><title>{item.label}: {item.value}</title></rect>{/each}
        {:else if chart==='line'}<polyline points={chartData.map((v,i)=>`${30+i*540/Math.max(1,chartData.length-1)},${250-v.value/maxValue*210}`).join(' ')} fill="none" stroke="currentColor" stroke-width="3"/>
        {:else}{#each chartData as item,i}<path d={piePath(i)} fill={`hsl(${i*61} 55% 55%)`} stroke="var(--surface-base,#161826)"><title>{item.label}: {item.value}</title></path>{/each}{/if}
    </svg><div>{#each chartData as item}<span>{item.label}: {item.value} </span>{/each}</div>{:else}<p>Select a label column and a numeric column, then choose a chart.</p>{/if}</section>{/if}
    <div class="sheet-grid" bind:this={grid} tabindex="0" role="region" aria-label="Spreadsheet grid" onkeydown={keydown} onpaste={paste} onscroll={()=>{scrollTop=grid.scrollTop;viewportHeight=grid.clientHeight;}}>
        {#if current}<table role="grid" aria-rowcount={rows.length+1} aria-colcount={current.columns.length+1}><thead><tr><th class="row-label">#</th>{#each current.columns as col,i(col.id)}<th scope="col">{columnName(i)}</th>{/each}</tr></thead><tbody>
            {#if first>0}<tr aria-hidden="true"><td colspan={current.columns.length+1} style:height={`${first*32}px`} class="spacer"></td></tr>{/if}
            {#each visible as row(row.id)}<tr aria-rowindex={current.rows.findIndex(r=>r.id===row.id)+2}><th class="row-label" scope="row">{current.rows.findIndex(r=>r.id===row.id)+1}</th>{#each current.columns as col(col.id)}{@const style=ysheet?styleOf(ysheet,row.id,col.id):{}}<td role="gridcell" aria-selected={selectedSet.has(cellKey(row.id,col.id))} class:selected={selectedSet.has(cellKey(row.id,col.id))} class:active={row.id===selectedRow&&col.id===selectedColumn} style:font-weight={style.bold?'700':'400'} style:font-style={style.italic?'italic':'normal'} style:text-align={style.align||'left'} title={value(row.id,col.id)} onclick={event=>choose(row.id,col.id,event.shiftKey)} ondblclick={()=>{choose(row.id,col.id);startEdit();}}>{value(row.id,col.id)||'\u00a0'}</td>{/each}</tr>{/each}
            {#if last<rows.length}<tr aria-hidden="true"><td colspan={current.columns.length+1} style:height={`${(rows.length-last)*32}px`} class="spacer"></td></tr>{/if}
        </tbody></table>{/if}
    </div>
    {#if ysheet&&recoverRemoved(ysheet).length}<div class="sheet-tools"><span>Content in removed rows or columns remains recoverable.</span><button onclick={()=>download('removed-sheet-content.json',JSON.stringify(recoverRemoved(ysheet!),null,2))}>Export removed content</button></div>{/if}
</div>
<style>
.sheets-editor{height:100%;display:flex;flex-direction:column;min-height:0}.sheet-tools{padding:.5rem;border-bottom:1px solid var(--border-subtle,#35384c);font-size:.8rem}.sheet-tools input{max-width:180px}.sheet-tools span{color:var(--text-secondary,#b5bad0)}.formula-bar{display:flex;align-items:center;gap:.5rem;padding:.5rem}.formula-bar span{min-width:64px;text-align:center;font-variant-numeric:tabular-nums}.formula-bar input{flex:1;min-width:0;font-family:monospace}.sheet-grid{overflow:auto;flex:1;min-height:260px;background:var(--surface-base,#161826);outline:none}.sheet-grid:focus-visible{outline:2px solid var(--accent-primary,#aaa4ff);outline-offset:-2px}table{border-collapse:separate;border-spacing:0;table-layout:fixed;font-size:13px;font-variant-numeric:tabular-nums}th,td{box-sizing:border-box;min-width:140px;max-width:140px;width:140px;height:32px;padding:3px 7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;border-right:1px solid var(--border-subtle,#35384c);border-bottom:1px solid var(--border-subtle,#35384c)}thead th{position:sticky;top:0;z-index:3;background:var(--surface-raised,#25293f)}.row-label{min-width:52px;max-width:52px;width:52px;position:sticky;left:0;z-index:2;background:var(--surface-raised,#25293f)}thead .row-label{z-index:4}.selected{background:color-mix(in srgb,var(--accent-primary,#8d80dc) 25%,transparent)}.active{outline:2px solid var(--accent-primary,#aa9ff6);outline-offset:-2px}.spacer{padding:0;border:0}.sheet-chart{height:220px;min-height:220px;display:flex;overflow:auto;padding:.5rem;color:var(--accent-primary,#9e96eb)}.sheet-chart svg{height:100%;min-width:350px}.sheet-chart div{display:flex;flex-direction:column;color:var(--text-secondary,#b5bad0);font-size:.8rem}
</style>
