// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CallSessionCreateReducer from "../call_session_create_reducer";
import CallSessionEndReducer from "../call_session_end_reducer";
import CallSessionJoinReducer from "../call_session_join_reducer";
import CallSessionLeaveReducer from "../call_session_leave_reducer";
import CallSignalEmitReducer from "../call_signal_emit_reducer";
import IngestWabiEventReducer from "../ingest_wabi_event_reducer";
import SetIngestKeyReducer from "../set_ingest_key_reducer";

export type CallSessionCreateParams = __Infer<typeof CallSessionCreateReducer>;
export type CallSessionEndParams = __Infer<typeof CallSessionEndReducer>;
export type CallSessionJoinParams = __Infer<typeof CallSessionJoinReducer>;
export type CallSessionLeaveParams = __Infer<typeof CallSessionLeaveReducer>;
export type CallSignalEmitParams = __Infer<typeof CallSignalEmitReducer>;
export type IngestWabiEventParams = __Infer<typeof IngestWabiEventReducer>;
export type SetIngestKeyParams = __Infer<typeof SetIngestKeyReducer>;

