import { test } from 'node:test';
import assert from 'node:assert/strict';
import { emptyState, parseState, planChanges, stageChange, stageStillMatches, publishStaged, isIgnored, safePath } from '../src/lib/loreLocalChanges.ts';
const local = (path, hash = 'A') => ({path, hash, size: 5});
const remote = (path, etag = 'A') => ({path, etag, size: 5});
const state = () => emptyState('server/account/project');
const tracked = (l = 'A', r = 'A') => { const s = state(); s.baselines['f.txt'] = {localHash:l, remoteEtag:r}; return s; };
const change = (ls, rs, s=state(), ignore='') => planChanges(ls, rs, s, ignore).changes;
test('an empty linked folder does not delete remote files', () => assert.equal(change([], [remote('f.txt')])[0].kind, 'incoming'));
test('new local file is added', () => assert.equal(change([local('f.txt')], [])[0].kind, 'added'));
test('equal existing files establish a baseline', () => assert.deepEqual(planChanges([local('f.txt')], [remote('f.txt')], state()).reconciled['f.txt'], {localHash:'A',remoteEtag:'A'}));
test('different untracked files are a conflict, not a silent overwrite', () => assert.equal(change([local('f.txt', 'B')], [remote('f.txt')])[0].kind, 'conflict'));
test('tracked local modification is outgoing', () => assert.equal(change([local('f.txt','B')], [remote('f.txt')], tracked())[0].kind, 'modified'));
test('tracked local deletion is outgoing', () => assert.equal(change([], [remote('f.txt')], tracked())[0].kind, 'deleted'));
test('remote modification is incoming', () => assert.equal(change([local('f.txt')], [remote('f.txt','B')], tracked())[0].kind, 'incoming'));
test('remote deletion is incoming', () => assert.equal(change([local('f.txt')], [], tracked())[0].kind, 'incoming'));
test('two-sided edits conflict', () => assert.equal(change([local('f.txt','B')], [remote('f.txt','C')], tracked())[0].kind, 'conflict'));
test('local deletion and remote edit conflict', () => assert.equal(change([], [remote('f.txt','B')], tracked())[0].kind, 'conflict'));
test('remote deletion and local edit conflict', () => assert.equal(change([local('f.txt','B')], [], tracked())[0].kind, 'conflict'));
test('matching independent changes reconcile', () => assert.equal(change([local('f.txt','B')], [remote('f.txt','B')], tracked()).length, 0));
test('opaque sampled remote ETags use separate baselines', () => assert.equal(change([local('f.txt','full-sha')], [remote('f.txt','q-sampled')], tracked('full-sha','q-sampled')).length, 0));
test('unknown sampled remote ETag is not assumed to match', () => assert.equal(change([local('f.txt','full-sha')], [remote('f.txt','q-sampled')])[0].kind, 'conflict'));
test('ignored tracked files are not interpreted as deletions', () => assert.equal(change([], [remote('f.txt')], tracked(), '*.txt').length, 0));
test('internal files and secrets are excluded even after negation', () => { for(const p of ['.env', 'nested/.env.local', '.git/config', '.wabi-workspace/state.json', '.ssh/id_rsa', 'target/bin']) assert.equal(isIgnored(p, '!**'), true); });
test('ordered ignore negation and ** work', () => { assert.ok(isIgnored('art/a.tmp','**/*.tmp')); assert.ok(!isIgnored('keep.tmp','**/*.tmp\n!keep.tmp')); assert.ok(isIgnored('cache/sub/a','cache')); });
test('literal regex characters in ignore rules are escaped', () => { assert.ok(isIgnored('art/[draft].png','art/[draft].png')); assert.ok(!isIgnored('art/d.png','art/[draft].png')); });
test('unsafe paths are rejected', () => { for(const p of ['../x','/x','a//b','a/../b','a\\b','C:x','CON.txt','file.','a\u0000b']) assert.ok(!safePath(p), p); });
test('duplicate manifest paths are rejected', () => assert.throws(() => change([], [remote('f.txt'),remote('f.txt')]), /Duplicate/));
test('case collisions are rejected across local and remote', () => assert.throws(() => change([local('File.txt')], [remote('file.txt')]), /collision/));
test('missing remote ETag stops comparison', () => assert.throws(() => change([], [remote('f.txt',null)]), /ETag/));
test('incoming/conflicted files cannot be staged', () => { for (const c of [change([], [remote('f.txt')])[0],change([local('f.txt','B')],[remote('f.txt')])[0]]) assert.throws(()=>stageChange(c)); });
test('stage becomes stale when local bytes change', () => { const c=change([local('f.txt')],[])[0]; assert.ok(!stageStillMatches(stageChange(c), {...c,localHash:'B'})); });
test('stage becomes stale when remote ETag changes', () => { const c=change([local('f.txt')],[])[0]; assert.ok(!stageStillMatches(stageChange(c), {...c,remoteEtag:'B'})); });
test('workspace identity is account/server/project scoped', () => assert.throws(()=>parseState(state(),'other-account'), /different/));
test('corrupt state fails closed', () => assert.throws(()=>parseState({version:1,identity:state().identity,baselines:null,staged:{}},state().identity)));
test('JSON prototype-like filenames remain ordinary index entries', () => { const s=parseState(JSON.parse('{"version":1,"identity":"server/account/project","baselines":{"__proto__":{"localHash":"A","remoteEtag":"A"}},"staged":{}}'),state().identity); assert.equal(Object.getPrototypeOf(s.baselines),null); assert.equal(s.baselines['__proto__'].localHash,'A'); });
test('partial success persists each accepted file and retains failures', async () => { const s=state(); const cs=change([local('a'),local('b')],[]); cs.forEach(c=>s.staged[c.path]=stageChange(c)); const saved=[]; await assert.rejects(publishStaged(s,cs,'update',{active:()=>true,save:async s=>saved.push(JSON.stringify(s)),publish:async c=>{if(c.path==='b')throw Error('offline');return {...c,pendingReview:false,remoteEtag:'new'};}}),/offline/); assert.equal(saved.length,1);assert.ok(!s.staged.a);assert.ok(s.staged.b);assert.equal(s.baselines.a.remoteEtag,'new'); });
test('blank summary never publishes', async () => { let calls=0; await assert.rejects(publishStaged(state(),[],' ',{active:()=>true,save:async()=>{},publish:async()=>calls++}),/summary/);assert.equal(calls,0); });
test('stale selection preflights all files before any publish', async () => { const s=state(); const cs=change([local('a'),local('b')],[]);cs.forEach(c=>s.staged[c.path]=stageChange(c));cs[1].localHash='new';let calls=0;await assert.rejects(publishStaged(s,cs,'update',{active:()=>true,save:async()=>{},publish:async()=>calls++}),/after staging/);assert.equal(calls,0); });
test('account switch stops publishing', async () => { const s=state(),cs=change([local('a')],[]);s.staged.a=stageChange(cs[0]);let calls=0;await assert.rejects(publishStaged(s,cs,'update',{active:()=>false,save:async()=>{},publish:async()=>calls++}),/account or project/);assert.equal(calls,0); });
test('review response does not falsely advance official baseline', async () => { const s=state(),cs=change([local('a')],[]);s.staged.a=stageChange(cs[0]);await assert.rejects(publishStaged(s,cs,'update',{active:()=>true,save:async()=>{},publish:async()=>({localHash:'A',remoteEtag:'R',pendingReview:true})}),/review/);assert.ok(!s.baselines.a);assert.ok(s.staged.a); });
test('review-pending stages remain blocked after state reload', async () => { const s=state(),cs=change([local('a')],[]);s.staged.a={...stageChange(cs[0]),pendingReview:true};const loaded=parseState(JSON.parse(JSON.stringify(s)),s.identity);assert.ok(!stageStillMatches(loaded.staged.a,cs[0])); });
test('explicit keep-local resolution stages against the observed server version', async () => { const {keepLocal}=await import('../src/lib/loreLocalChanges.ts');const s=tracked();const cs=change([local('f.txt','B')],[remote('f.txt','C')],s);s.staged['f.txt']=keepLocal(s,cs[0]);const next=change([local('f.txt','B')],[remote('f.txt','C')],s);assert.ok(stageStillMatches(s.staged['f.txt'],next[0]));assert.equal(s.staged['f.txt'].remoteEtag,'C'); });
test('keep-local still conflicts when server moves again', async () => { const {keepLocal}=await import('../src/lib/loreLocalChanges.ts');const s=tracked();keepLocal(s,change([local('f.txt','B')],[remote('f.txt','C')],s)[0]);assert.equal(change([local('f.txt','B')],[remote('f.txt','D')],s)[0].kind,'conflict'); });
test('no selection never publishes', async () => {let calls=0;await assert.rejects(publishStaged(state(),[],'update',{active:()=>true,save:async()=>{},publish:async()=>calls++}),/at least one/);assert.equal(calls,0);});
test('state persistence failure halts before the next file', async () => {const s=state(),cs=change([local('a'),local('b')],[]);cs.forEach(c=>s.staged[c.path]=stageChange(c));let calls=0;await assert.rejects(publishStaged(s,cs,'update',{active:()=>true,save:async()=>{throw Error('disk full');},publish:async c=>{calls++;return {...c,remoteEtag:'R',pendingReview:false};}}),/disk full/);assert.equal(calls,1);assert.ok(s.staged.b);});
