//! Media room registry for helper-node voice/video offloading.
//!
//! Phase 4: primary owns room lifecycle + permissions. Helper nodes with
//! `MediaRelay` capability can be assigned as the host for a room.
//! Clients ask primary "where do I connect?"; primary returns the helper
//! endpoint or falls back to itself.
//!
//! Shared media nodes may serve multiple independent Authorities. `tenant_namespace`
//! and `external_room_name` therefore travel with every room so backend room names
//! remain isolated even when unrelated Wabi servers use the same physical SFU.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, path::PathBuf, sync::Arc};
use tokio::sync::RwLock;
use uuid::Uuid;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MediaRoomStatus {
    Pending,
    Assigned,
    Active,
    Closed,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaRoom {
    pub room_id: String,
    pub channel_id: String,
    /// Opaque Authority-owned tenant namespace. A shared Media Node must scope
    /// every backend room and credential to this tenant.
    #[serde(default)]
    pub tenant_namespace: String,
    /// Backend-facing room name. Do not replace this with a human channel name.
    /// The value is tenant-scoped so multiple Authorities can safely share one SFU.
    #[serde(default)]
    pub external_room_name: String,
    pub created_at: DateTime<Utc>,
    pub assigned_node_id: Option<String>,
    pub assigned_at: Option<DateTime<Utc>>,
    pub status: MediaRoomStatus,
    pub sfu_endpoint: Option<String>,
    pub max_participants: u32,
    pub current_participants: u32,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
struct MediaRoomRegistryData {
    /// Stable opaque namespace generated by this Authority's media registry.
    /// It is intentionally separate from human-configurable server/instance names.
    #[serde(default)]
    tenant_namespace: Option<String>,
    rooms: HashMap<String, MediaRoom>,
}

#[derive(Clone, Debug)]
pub struct MediaRoomRegistry {
    data_path: PathBuf,
    inner: Arc<RwLock<MediaRoomRegistryData>>,
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[allow(dead_code)]
pub enum MediaRoomError {
    #[error("room not found")]
    NotFound,
    #[error("room already exists")]
    AlreadyExists,
    #[error("room is not in a state that allows this action")]
    InvalidState,
    #[error("node is not suitable for media relay")]
    InvalidNode,
    #[error("io error: {0}")]
    Io(String),
}

#[allow(dead_code)]
impl MediaRoomRegistry {
    pub fn new_persistent(data_dir: impl Into<PathBuf>) -> Self {
        let data_dir: PathBuf = data_dir.into();
        let data_path = data_dir.join("media_rooms.json");
        let data = std::fs::read_to_string(&data_path)
            .ok()
            .and_then(|s| serde_json::from_str::<MediaRoomRegistryData>(&s).ok())
            .unwrap_or_default();
        Self {
            data_path,
            inner: Arc::new(RwLock::new(data)),
        }
    }

    /// Create a new media room for a channel. Returns existing if
    /// a room for this channel is already open.
    ///
    /// The registry owns a random, persisted tenant namespace. Shared Media
    /// Nodes see this opaque namespace instead of a human server/channel name.
    pub async fn create_room(
        &self,
        channel_id: String,
        max_participants: u32,
    ) -> Result<MediaRoom, MediaRoomError> {
        let mut guard = self.inner.write().await;
        let mut registry_changed = false;
        let tenant_namespace = match guard.tenant_namespace.clone() {
            Some(namespace) if !namespace.trim().is_empty() => namespace,
            _ => {
                let namespace = new_tenant_namespace();
                guard.tenant_namespace = Some(namespace.clone());
                registry_changed = true;
                namespace
            }
        };

        // Upgrade old persisted open rooms in place. The fields were added with
        // serde defaults so a pre-shared-node media_rooms.json remains readable.
        let existing_id = guard
            .rooms
            .iter()
            .find(|(_, r)| {
                r.channel_id == channel_id
                    && matches!(
                        r.status,
                        MediaRoomStatus::Pending | MediaRoomStatus::Assigned | MediaRoomStatus::Active
                    )
            })
            .map(|(id, _)| id.clone());
        if let Some(existing_id) = existing_id {
            let mut changed = registry_changed;
            let existing = guard.rooms.get_mut(&existing_id).expect("existing room disappeared");
            if existing.tenant_namespace.is_empty() {
                existing.tenant_namespace = tenant_namespace.clone();
                changed = true;
            }
            if existing.external_room_name.is_empty() {
                existing.external_room_name = tenant_room_name(&existing.tenant_namespace, &existing.room_id);
                changed = true;
            }
            let cloned = existing.clone();
            if changed {
                self.persist_locked(&guard).await;
            }
            return Ok(cloned);
        }

        let room_id = new_room_id();
        let room = MediaRoom {
            external_room_name: tenant_room_name(&tenant_namespace, &room_id),
            room_id,
            channel_id,
            tenant_namespace,
            created_at: Utc::now(),
            assigned_node_id: None,
            assigned_at: None,
            status: MediaRoomStatus::Pending,
            sfu_endpoint: None,
            max_participants,
            current_participants: 0,
        };
        guard.rooms.insert(room.room_id.clone(), room.clone());
        self.persist_locked(&guard).await;
        Ok(room)
    }

    pub async fn assign_room(
        &self,
        room_id: &str,
        node_id: &str,
        sfu_endpoint: Option<String>,
    ) -> Result<MediaRoom, MediaRoomError> {
        let mut guard = self.inner.write().await;
        let room = guard
            .rooms
            .get_mut(room_id)
            .ok_or(MediaRoomError::NotFound)?;
        if matches!(room.status, MediaRoomStatus::Closed) {
            return Err(MediaRoomError::InvalidState);
        }
        room.assigned_node_id = Some(node_id.to_string());
        room.assigned_at = Some(Utc::now());
        room.sfu_endpoint = sfu_endpoint;
        room.status = MediaRoomStatus::Assigned;
        let cloned = room.clone();
        self.persist_locked(&guard).await;
        Ok(cloned)
    }

    pub async fn mark_active(
        &self,
        room_id: &str,
        node_id: &str,
        sfu_endpoint: String,
    ) -> Result<MediaRoom, MediaRoomError> {
        let mut guard = self.inner.write().await;
        let room = guard
            .rooms
            .get_mut(room_id)
            .ok_or(MediaRoomError::NotFound)?;
        if room.assigned_node_id.as_deref() != Some(node_id) {
            return Err(MediaRoomError::InvalidNode);
        }
        room.status = MediaRoomStatus::Active;
        room.sfu_endpoint = Some(sfu_endpoint);
        let cloned = room.clone();
        self.persist_locked(&guard).await;
        Ok(cloned)
    }

    pub async fn update_participants(
        &self,
        room_id: &str,
        count: u32,
    ) -> Result<MediaRoom, MediaRoomError> {
        let mut guard = self.inner.write().await;
        let room = guard
            .rooms
            .get_mut(room_id)
            .ok_or(MediaRoomError::NotFound)?;
        room.current_participants = count;
        let cloned = room.clone();
        self.persist_locked(&guard).await;
        Ok(cloned)
    }

    pub async fn close_room(&self, room_id: &str) -> Result<MediaRoom, MediaRoomError> {
        let mut guard = self.inner.write().await;
        let room = guard
            .rooms
            .get_mut(room_id)
            .ok_or(MediaRoomError::NotFound)?;
        room.status = MediaRoomStatus::Closed;
        room.assigned_node_id = None;
        room.sfu_endpoint = None;
        let cloned = room.clone();
        self.persist_locked(&guard).await;
        Ok(cloned)
    }

    pub async fn get_room(&self, room_id: &str) -> Option<MediaRoom> {
        let guard = self.inner.read().await;
        guard.rooms.get(room_id).cloned()
    }

    pub async fn find_by_channel(&self, channel_id: &str) -> Option<MediaRoom> {
        let guard = self.inner.read().await;
        guard
            .rooms
            .values()
            .find(|r| r.channel_id == channel_id && !matches!(r.status, MediaRoomStatus::Closed))
            .cloned()
    }

    pub async fn list_rooms(&self) -> Vec<MediaRoom> {
        let guard = self.inner.read().await;
        guard
            .rooms
            .values()
            .filter(|r| !matches!(r.status, MediaRoomStatus::Closed))
            .cloned()
            .collect()
    }

    pub async fn active_endpoint(&self, room_id: &str) -> Option<String> {
        let guard = self.inner.read().await;
        let room = guard.rooms.get(room_id)?;
        if room.status != MediaRoomStatus::Active {
            return None;
        }
        room.sfu_endpoint.clone()
    }

    async fn persist_locked(&self, data: &MediaRoomRegistryData) {
        if let Some(parent) = self.data_path.parent() {
            let _ = tokio::fs::create_dir_all(parent).await;
        }
        if let Ok(content) = serde_json::to_string_pretty(data) {
            let _ = tokio::fs::write(&self.data_path, content).await;
        }
    }
}

fn new_room_id() -> String {
    format!("room-{}", Uuid::new_v4())
}

fn new_tenant_namespace() -> String {
    format!("tenant-{}", Uuid::new_v4().simple())
}

/// Keep backend-visible tenant identifiers opaque and safe for common SFU room
/// name restrictions. Registry-generated tenant IDs already satisfy this; this
/// also protects restored/legacy data from unsafe punctuation.
fn normalize_tenant_namespace(value: &str) -> String {
    let normalized: String = value
        .trim()
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else if c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .take(48)
        .collect();
    let normalized = normalized.trim_matches('-').to_string();
    if normalized.is_empty() {
        "tenant".to_string()
    } else {
        normalized
    }
}

/// Build the room name passed to a shared SFU. Never use channel/user display
/// names here: shared nodes must only see opaque tenant + random room identity.
pub fn tenant_room_name(tenant_namespace: &str, room_id: &str) -> String {
    format!(
        "wabi-{}-{}",
        normalize_tenant_namespace(tenant_namespace),
        room_id
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn create_assign_active_close() {
        let tmp = std::env::temp_dir().join(format!("wabi-media-test-{}", Uuid::new_v4()));
        let reg = MediaRoomRegistry::new_persistent(&tmp);

        let room = reg.create_room("ch1".into(), 8).await.unwrap();
        assert_eq!(room.channel_id, "ch1");
        assert!(room.tenant_namespace.starts_with("tenant-"));
        assert!(room.external_room_name.starts_with("wabi-tenant-"));
        assert_eq!(room.status, MediaRoomStatus::Pending);

        let assigned = reg
            .assign_room(
                &room.room_id,
                "node-a",
                Some("wss://helper.local/roomA".into()),
            )
            .await
            .unwrap();
        assert_eq!(assigned.status, MediaRoomStatus::Assigned);

        let active = reg
            .mark_active(&room.room_id, "node-a", "wss://helper.local/roomA".into())
            .await
            .unwrap();
        assert_eq!(active.status, MediaRoomStatus::Active);

        let ep = reg.active_endpoint(&room.room_id).await;
        assert_eq!(ep, Some("wss://helper.local/roomA".to_string()));

        let closed = reg.close_room(&room.room_id).await.unwrap();
        assert_eq!(closed.status, MediaRoomStatus::Closed);
        assert!(reg.active_endpoint(&room.room_id).await.is_none());

        let _ = tokio::fs::remove_dir_all(&tmp).await;
    }

    #[tokio::test]
    async fn tenant_namespace_is_stable_for_one_registry() {
        let tmp = std::env::temp_dir().join(format!("wabi-media-tenant-{}", Uuid::new_v4()));
        let reg = MediaRoomRegistry::new_persistent(&tmp);

        let first = reg.create_room("one".into(), 50).await.unwrap();
        reg.close_room(&first.room_id).await.unwrap();
        let second = reg.create_room("two".into(), 50).await.unwrap();

        assert_eq!(first.tenant_namespace, second.tenant_namespace);
        assert_ne!(first.external_room_name, second.external_room_name);

        // Prove the namespace survives a registry/process reconstruction.
        drop(reg);
        let reopened = MediaRoomRegistry::new_persistent(&tmp);
        reopened.close_room(&second.room_id).await.unwrap();
        let third = reopened.create_room("three".into(), 50).await.unwrap();
        assert_eq!(first.tenant_namespace, third.tenant_namespace);

        let _ = tokio::fs::remove_dir_all(&tmp).await;
    }

    #[tokio::test]
    async fn independent_authorities_get_distinct_tenant_namespaces() {
        let tmp_a = std::env::temp_dir().join(format!("wabi-media-a-{}", Uuid::new_v4()));
        let tmp_b = std::env::temp_dir().join(format!("wabi-media-b-{}", Uuid::new_v4()));
        let reg_a = MediaRoomRegistry::new_persistent(&tmp_a);
        let reg_b = MediaRoomRegistry::new_persistent(&tmp_b);

        let a = reg_a.create_room("general".into(), 50).await.unwrap();
        let b = reg_b.create_room("general".into(), 50).await.unwrap();

        assert_ne!(a.tenant_namespace, b.tenant_namespace);
        assert_ne!(a.external_room_name, b.external_room_name);

        let _ = tokio::fs::remove_dir_all(&tmp_a).await;
        let _ = tokio::fs::remove_dir_all(&tmp_b).await;
    }

    #[test]
    fn tenant_room_names_strip_unsafe_punctuation() {
        let name = tenant_room_name("tenant @ 01", "room-123");
        assert_eq!(name, "wabi-tenant---01-room-123");
        assert!(!name.contains('@'));
        assert!(!name.contains('/'));
    }
}
