// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  assignmentKey: __t.string().primaryKey().name("assignment_key"),
  workspaceId: __t.string().name("workspace_id"),
  userId: __t.i64().name("user_id"),
  role: __t.string(),
  assignedBy: __t.option(__t.i64()).name("assigned_by"),
  active: __t.bool(),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
