// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  reactionId: __t.string().primaryKey().name("reaction_id"),
  messageId: __t.string().name("message_id"),
  channelId: __t.string().name("channel_id"),
  userId: __t.i64().name("user_id"),
  emojiId: __t.string().name("emoji_id"),
  createdAt: __t.timestamp().name("created_at"),
});
