// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  relayId: __t.i64().primaryKey().name("relay_id"),
  url: __t.string(),
  name: __t.string(),
  region: __t.string(),
  apiKeyHash: __t.string().name("api_key_hash"),
  status: __t.string(),
  lastHealthPing: __t.option(__t.i64()).name("last_health_ping"),
  registeredAt: __t.i64().name("registered_at"),
  approved: __t.bool(),
  latitude: __t.option(__t.f64()),
  longitude: __t.option(__t.f64()),
  bandwidthMbps: __t.option(__t.i64()).name("bandwidth_mbps"),
  storageGb: __t.option(__t.i64()).name("storage_gb"),
  syncthingDeviceId: __t.option(__t.string()).name("syncthing_device_id"),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
