// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entryKey: __t.string().primaryKey().name("entry_key"),
  workspaceId: __t.string().name("workspace_id"),
  language: __t.string(),
  termNormalized: __t.string().name("term_normalized"),
  term: __t.string(),
  createdByUserId: __t.option(__t.i64()).name("created_by_user_id"),
  createdByUsername: __t.option(__t.string()).name("created_by_username"),
  createdAt: __t.i64().name("created_at"),
  updatedAt: __t.i64().name("updated_at"),
  votes: __t.i64(),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
