// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ruleId: __t.i64().primaryKey().name("rule_id"),
  channelId: __t.string().name("channel_id"),
  messageId: __t.string().name("message_id"),
  emojiId: __t.string().name("emoji_id"),
  roleName: __t.string().name("role_name"),
  removeOnUnreact: __t.bool().name("remove_on_unreact"),
  workspaceId: __t.string().name("workspace_id"),
  enabled: __t.bool(),
  createdAt: __t.i64().name("created_at"),
});
