// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  settlementId: __t.string().primaryKey().name("settlement_id"),
  workspaceId: __t.string().name("workspace_id"),
  settlementKind: __t.string().name("settlement_kind"),
  channelId: __t.option(__t.string()).name("channel_id"),
  createdByUserId: __t.i64().name("created_by_user_id"),
  counterpartyUserId: __t.option(__t.i64()).name("counterparty_user_id"),
  status: __t.string(),
  currency: __t.string(),
  amountMinor: __t.i64().name("amount_minor"),
  completedAt: __t.option(__t.i64()).name("completed_at"),
  voidedAt: __t.option(__t.i64()).name("voided_at"),
  createdAt: __t.i64().name("created_at"),
  updatedAt: __t.i64().name("updated_at"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
