// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  instanceId: __t.string().primaryKey().name("instance_id"),
  region: __t.string(),
  role: __t.string(),
  status: __t.string(),
  currentConnections: __t.i64().name("current_connections"),
  currentRegisteredUsers: __t.i64().name("current_registered_users"),
  currentGuestUsers: __t.i64().name("current_guest_users"),
  heartbeatAt: __t.i64().name("heartbeat_at"),
  leaseExpiresAt: __t.i64().name("lease_expires_at"),
  startedAt: __t.i64().name("started_at"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
