// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  intentId: __t.string().primaryKey().name("intent_id"),
  workspaceId: __t.string().name("workspace_id"),
  createdByUserId: __t.option(__t.i64()).name("created_by_user_id"),
  channelId: __t.option(__t.string()).name("channel_id"),
  pluginId: __t.string().name("plugin_id"),
  providerName: __t.string().name("provider_name"),
  providerIntentId: __t.option(__t.string()).name("provider_intent_id"),
  amountMinor: __t.i64().name("amount_minor"),
  currency: __t.string(),
  countryCode: __t.option(__t.string()).name("country_code"),
  status: __t.string(),
  checkoutMode: __t.string().name("checkout_mode"),
  idempotencyKey: __t.option(__t.string()).name("idempotency_key"),
  failureCode: __t.option(__t.string()).name("failure_code"),
  failureMessage: __t.option(__t.string()).name("failure_message"),
  createdAt: __t.i64().name("created_at"),
  updatedAt: __t.i64().name("updated_at"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
