// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.i64().primaryKey().name("user_id"),
  themeId: __t.string().name("theme_id"),
  customTheme: __t.option(__t.string()).name("custom_theme"),
  uniformFontEnabled: __t.bool().name("uniform_font_enabled"),
  uniformFontFamily: __t.string().name("uniform_font_family"),
  uniformFontSize: __t.string().name("uniform_font_size"),
  uniformFontWeight: __t.string().name("uniform_font_weight"),
  uniformFontStyle: __t.string().name("uniform_font_style"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
