// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.i64().primaryKey().name("user_id"),
  offlineMessageRetention: __t.string().name("offline_message_retention"),
  allowTempUserMessages: __t.bool().name("allow_temp_user_messages"),
  businessPrivateMode: __t.bool().name("business_private_mode"),
  homeExperience: __t.string().name("home_experience"),
  requirePasswordChange: __t.bool().name("require_password_change"),
  paymentPreferredRoute: __t.option(__t.string()).name("payment_preferred_route"),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
