// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  channelId: __t.string().primaryKey().name("channel_id"),
  channelType: __t.string().name("channel_type"),
  name: __t.string(),
  createdAt: __t.i64().name("created_at"),
  createdBy: __t.string().name("created_by"),
  archived: __t.bool(),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
