// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  participantKey: __t.string().primaryKey().name("participant_key"),
  sessionId: __t.string().name("session_id"),
  userId: __t.i64().name("user_id"),
  stableUserId: __t.string().name("stable_user_id"),
  joinedAt: __t.i64().name("joined_at"),
  leftAt: __t.option(__t.i64()).name("left_at"),
  isHost: __t.bool().name("is_host"),
  muted: __t.bool(),
  videoEnabled: __t.bool().name("video_enabled"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
