// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roleKey: __t.string().primaryKey().name("role_key"),
  workspaceId: __t.string().name("workspace_id"),
  roleName: __t.string().name("role_name"),
  displayName: __t.string().name("display_name"),
  priority: __t.i64(),
  color: __t.option(__t.string()),
  isHoisted: __t.bool().name("is_hoisted"),
  active: __t.bool(),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
