// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.i64().primaryKey().name("user_id"),
  username: __t.option(__t.string()),
  usernameLc: __t.option(__t.string()).name("username_lc"),
  handle: __t.option(__t.string()),
  handleLc: __t.option(__t.string()).name("handle_lc"),
  active: __t.bool(),
  deleted: __t.bool(),
  rowJson: __t.string().name("row_json"),
  lastUpdatedAt: __t.timestamp().name("last_updated_at"),
});
