import type { AudienceSlide } from '../bridge';
export interface SlideImport{aspect:number;slides:Omit<AudienceSlide,'id'>[];warnings:string[];}
export async function rasterImage(file:File,signal:AbortSignal):Promise<string>{if(file.size>12*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Choose a PNG, JPEG, or WebP image under 12 MB.');signal.throwIfAborted();const image=await createImageBitmap(file);try{signal.throwIfAborted();if(image.width*image.height>32_000_000)throw new Error('Image dimensions exceed the supported limit.');const scale=Math.min(1,1400/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');if(!context)throw new Error('Image rendering unavailable');context.drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');if(data.length<=2*1024*1024)return data;const smaller=canvas.toDataURL('image/jpeg',.8);if(smaller.length>2*1024*1024)throw new Error('Image remains too large after resizing.');return smaller;}finally{image.close();}}
export async function importSlides(file:File,signal:AbortSignal,onprogress:(text:string)=>void):Promise<SlideImport>{
    if(file.size>12*1024*1024)throw new Error('Presentation import is limited to 12 MB.');
    if(/\.(pptx?|odp)$/i.test(file.name))throw new Error('PowerPoint/ODP conversion is not installed in this build. Export a PDF from the source application, then open that PDF here. The original file has not been uploaded.');
    if(file.type.startsWith('image/'))return{aspect:16/9,slides:[{title:file.name,body:'',layout:'image',image:await rasterImage(file,signal)}],warnings:['The image is resized and copied into a private native deck.']};
    if(!/\.pdf$/i.test(file.name))throw new Error('Supported imports are PDF, PNG, JPEG, WebP, and native Wabi decks.');
    const pdfjs=await import('pdfjs-dist');const workerUrl=(await import('pdfjs-dist/build/pdf.worker.min.mjs?url')).default;pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
    signal.throwIfAborted();const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),enableXfa:false,useWasm:false,disableFontFace:true,useSystemFonts:false,useWorkerFetch:false,maxImageSize:4_000_000,disableAutoFetch:true,disableStream:true,stopAtErrors:true});
    const cancel=()=>{void task.destroy();};signal.addEventListener('abort',cancel,{once:true});const timeout=setTimeout(cancel,45000);
    try{const pdf=await task.promise;if(pdf.numPages>40)throw new Error('PDF import is currently limited to 40 pages. Split a longer presentation first.');const slides:Omit<AudienceSlide,'id'>[]=[];let total=0,aspect=16/9;
        for(let i=1;i<=pdf.numPages;i++){signal.throwIfAborted();onprogress(`Rendering page ${i} of ${pdf.numPages}`);const page=await pdf.getPage(i);const original=page.getViewport({scale:1});if(i===1)aspect=original.width/original.height;const viewport=page.getViewport({scale:Math.min(2,1200/Math.max(original.width,original.height))});const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.floor(viewport.width));canvas.height=Math.max(1,Math.floor(viewport.height));const context=canvas.getContext('2d');if(!context)throw new Error('Canvas rendering unavailable');const rendering=page.render({canvas,canvasContext:context,viewport});const stopRender=()=>rendering.cancel();signal.addEventListener('abort',stopRender,{once:true});try{await rendering.promise;}finally{signal.removeEventListener('abort',stopRender);}const image=canvas.toDataURL('image/jpeg',.82);total+=image.length;if(image.length>2*1024*1024||total>9*1024*1024)throw new Error('Rendered PDF exceeds the native deck size limit. Use fewer pages.');slides.push({title:`${file.name} · ${i}`,body:'',layout:'image',image});canvas.width=canvas.height=1;page.cleanup();}
        return{aspect,slides,warnings:['PDF pages are static images, not editable PowerPoint objects.','Fonts, animations, links, and interactive media may differ. Review each slide before presenting.']};
    }finally{clearTimeout(timeout);signal.removeEventListener('abort',cancel);await task.destroy();}
}
export async function exportPptx(title:string,slides:AudienceSlide[],aspect:number):Promise<void>{if(!slides.length)throw new Error('There are no visible slides to export.');const{default:PptxGenJS}=await import('pptxgenjs');const pptx=new PptxGenJS();const width=10,height=width/Math.max(.5,Math.min(3,aspect));pptx.defineLayout({name:'WABI',width,height});pptx.layout='WABI';pptx.author='Wabi';pptx.subject='Audience-safe static native deck export';pptx.title=title;
    for(const item of slides){const slide=pptx.addSlide();slide.background={color:'F4F1E9'};const image=item.image&&/^data:image\/(png|jpeg|webp);base64,/.test(item.image)?item.image:null;if(image&&item.layout==='image'){slide.addImage({data:image,x:0,y:0,w:width,h:height});continue;}const split=item.layout==='split'&&image;slide.addText(item.title,{x:.5,y:.5,w:split?4.4:9,h:Math.min(1.2,height*.22),fontFace:'Arial',fontSize:28,bold:true,color:'242836',breakLine:false,margin:0});if(item.body)slide.addText(item.body,{x:.5,y:1.7,w:split?4.4:9,h:Math.max(.5,height-2.2),fontFace:'Arial',fontSize:18,color:'242836',margin:0,fit:'shrink',valign:'top'});if(image)slide.addImage({data:image,x:split?5.1:.5,y:split ? .6 : height*.48,w:split?4.4:9,h:split?height-1.2:height*.44});}
    await pptx.writeFile({fileName:`${title.replace(/[\\/:*?"<>|]/g,'_')||'Presentation'}.pptx`,compression:true});
}
export function printAudience(title:string,slides:AudienceSlide[],aspect:number){const child=window.open('','_blank');if(!child)throw new Error('The browser blocked the print window. Allow this window to export an audience PDF.');child.opener=null;const doc=child.document;doc.title=title;const style=doc.createElement('style');const height=10/Math.max(.5,Math.min(3,aspect));style.textContent=`@page{size:10in ${height}in;margin:0}body{margin:0;font-family:Arial,sans-serif}.slide{box-sizing:border-box;width:10in;height:${height}in;page-break-after:always;position:relative;background:#f4f1e9;color:#242836;padding:.5in;overflow:hidden}.slide:last-child{page-break-after:auto}h1{font-size:32pt}p{white-space:pre-wrap;font-size:20pt;line-height:1.45}img{max-width:100%;max-height:70%;object-fit:contain}.image{padding:0;display:flex;align-items:center;justify-content:center}.image img{width:100%;height:100%;max-height:100%}@media screen{.slide{margin:10px;border:1px solid #bbb}}`;doc.head.append(style);const images:Promise<void>[]=[];for(const item of slides){const section=doc.createElement('section');section.className='slide'+(item.layout==='image'?' image':'');if(item.layout!=='image'||!item.image){const h=doc.createElement('h1');h.textContent=item.title;const p=doc.createElement('p');p.textContent=item.body;section.append(h,p);}if(item.image&&/^data:image\/(png|jpeg|webp);base64,/.test(item.image)){const image=doc.createElement('img');image.alt=item.title;image.src=item.image;images.push(image.decode().catch(()=>{}));section.append(image);}doc.body.append(section);}void Promise.all(images).then(()=>{child.focus();child.print();});}
