import * as Y from 'yjs';
import type { AudienceSlide } from '../bridge';
export interface DeckSlide extends AudienceSlide{position:number;hidden:boolean;}
export function collection(data:Y.Map<unknown>):Y.Map<Y.Map<unknown>>{const slides=data.get('slides');if(!(slides instanceof Y.Map))throw new Error('Unsupported deck data');return slides;}
export function readSlides(data:Y.Map<unknown>,audienceOnly=false):DeckSlide[]{return Array.from(collection(data),([id,s])=>({id,title:s.get('title') instanceof Y.Text?(s.get('title') as Y.Text).toString():String(s.get('title')||''),body:s.get('body') instanceof Y.Text?(s.get('body') as Y.Text).toString():String(s.get('body')||''),layout:String(s.get('layout')||'text'),image:typeof s.get('image')==='string'?s.get('image') as string:null,position:Number(s.get('position')||0),hidden:s.get('hidden')===true,removed:s.get('removed')===true})).filter(s=>!s.removed&&(!audienceOnly||!s.hidden)).sort((a,b)=>a.position-b.position||a.id.localeCompare(b.id));}
export function initialize(data:Y.Map<unknown>,title='New presentation'){data.set('schema',1);data.set('aspect',16/9);data.set('slides',new Y.Map());addSlide(data,{title,body:'Start with the idea you want to share.',layout:'title'});}
export function addSlide(data:Y.Map<unknown>,seed:Partial<DeckSlide>={},after?:string){const slides=collection(data);if(slides.size>=200)throw new Error('This release supports 200 stored slides, including removed slides.');const ordered=readSlides(data),at=after?ordered.findIndex(s=>s.id===after):ordered.length-1;const before=ordered[at]?.position??-1,next=ordered[at+1]?.position??before+2,position=(before+next)/2;if(position===before||position===next)throw new Error('Slide ordering precision exhausted; export a normalized copy.');const id=crypto.randomUUID(),slide=new Y.Map<unknown>();slides.set(id,slide);slide.set('title',new Y.Text(seed.title||'Untitled slide'));slide.set('body',new Y.Text(seed.body||''));slide.set('layout',seed.layout||'text');slide.set('position',position);slide.set('hidden',!!seed.hidden);if(seed.image)slide.set('image',seed.image);return id;}
export function moveSlide(data:Y.Map<unknown>,id:string,direction:number){const slides=readSlides(data),index=slides.findIndex(s=>s.id===id),target=index+direction;if(index<0||target<0||target>=slides.length)return;const ordered=slides.filter(s=>s.id!==id);ordered.splice(target,0,slides[index]);const at=ordered.findIndex(s=>s.id===id),before=ordered[at-1]?.position??(ordered[at+1]?.position??0)-2,next=ordered[at+1]?.position??before+2;const position=(before+next)/2;if(position===before||position===next)throw new Error('Slide ordering precision exhausted');collection(data).get(id)!.set('position',position);}
export function audienceSlides(data:Y.Map<unknown>):AudienceSlide[]{return readSlides(data,true).map(s=>({id:s.id,title:s.title,body:s.body,layout:s.layout,image:s.image}));}
export function fromMarkdown(source:string,title:string):{title:string;body:string;layout:string}[]{const sections=source.split(/^\s*---\s*$|^(?=#{1,2}\s)/m).map(s=>s.trim()).filter(Boolean);if(sections.length>100)throw new Error('This source proposes more than 100 slides. Add fewer explicit sections.');return sections.map((section,index)=>{const lines=section.split('\n'),heading=/^#{1,6}\s+(.+)$/.exec(lines[0]);return{title:heading?heading[1]:index===0?title:`Slide ${index+1}`,body:heading?lines.slice(1).join('\n').trim():section,layout:index===0?'title':'text'};});}
export function validateNative(data:Y.Map<unknown>){if(data.get('schema')!==1)throw new Error('Unsupported deck version');for(const key of data.keys())if(!['schema','aspect','slides'].includes(key))throw new Error('Deck contains unsupported data. Private notes must be imported separately.');const slides=collection(data);if(slides.size>200)throw new Error('Deck exceeds the slide limit');for(const [id,slide]of slides){if(!/^[0-9a-f-]{36}$/i.test(id)||!(slide instanceof Y.Map))throw new Error('Invalid slide');for(const key of slide.keys())if(!['title','body','layout','image','position','hidden','removed'].includes(key))throw new Error('Deck has an unsupported or private slide field');}for(const slide of readSlides(data)){if(slide.title.length>2000||slide.body.length>16000)throw new Error('Slide text exceeds limits');if(slide.image&&(!/^data:image\/(png|jpeg|webp);base64,/.test(slide.image)||slide.image.length>2*1024*1024))throw new Error('Unsupported image in deck');}}
