<script lang="ts">
    import PresentedVersion from './PresentedVersion.svelte';
    import OfficeConversion from './OfficeConversion.svelte';
    import {editionFingerprint} from './versionPreview';
    import {slideAnchor} from '../anchors';
    import {onMount,onDestroy} from 'svelte';
    import {channels} from '$lib/channelStore';
    import ArtifactShell from '../ArtifactShell.svelte';import ArtifactLibrary from '../ArtifactLibrary.svelte';import AudienceSlideView from '../AudienceSlide.svelte';
    import {ArtifactSession,createArtifact,openArtifact,editText,download,readPrivateNotes,savePrivateNote,from64,Y} from '../session';
    import {captureScope,request,targets,openWorkspace,presentationLink,registerWorkspaceDisposer,type Scope,type AudienceState,type AudienceSlide} from '../bridge';
    import {initialize,readSlides,collection,addSlide,moveSlide,audienceSlides,validateNative,fromMarkdown} from './model';
    import '../workspace.css';
    let scope=$state<Scope|null>(null),active=$state<ArtifactSession|null>(null);let tick=$state(0),busy=$state(false),error=$state(''),progress=$state('');let selectedId=$state('');let note=$state(''),noteStatus=$state('Private notes · this device');let notes=$state<Record<string,string>>({});let noteChain:Promise<void>=Promise.resolve();let stop=()=>{},unregisterNotes=()=>{};let disposed=false;let epoch=0;let previous:unknown;let importAbort=new AbortController();let imageInput:HTMLInputElement;let previewDialog:HTMLDialogElement;let startDialog:HTMLDialogElement;let localDialog:HTMLDialogElement;let localSurface:HTMLDivElement;
    let pendingOffice=$state<File|null>(null);
    let proposed=$state<{title:string;aspect:number;slides:Omit<AudienceSlide,'id'>[];warnings:string[];source?:File}|null>(null);let channelId=$state('');let localIndex=$state(0);let localBlank=$state(false);let pinnedLocal=$state<AudienceSlide[]>([]);let startedLink=$state('');let roomId=$state('');
    const slides=$derived.by(()=>{tick;return active?readSlides(active.data):[];});const current=$derived(slides.find(s=>s.id===selectedId)||slides[0]||null);const aspect=$derived.by(()=>{tick;return active?Number(active.data.get('aspect')||16/9):16/9;});const editable=$derived.by(()=>{tick;return active?.editable||false;});const liveTitle=$derived.by(()=>{tick;return active?.title||'';});
    $effect(()=>{if(current&&current.id!==selectedId)selectedId=current.id;});
    function select(id:string){selectedId=id;note=notes[id]||'';noteStatus='Private notes · this device';}
    async function run(fn:()=>Promise<void>){busy=true;error='';try{await fn();}catch(e){error=e instanceof Error?e.message:String(e);}finally{busy=false;progress='';}}
    async function use(session:ArtifactSession){const ticket=++epoch;const valid=()=>!disposed&&!!scope?.isCurrent()&&ticket===epoch;if(!valid()){await session.close();return;}await noteChain;if(!valid()){await session.close();return;}const savedNotes=await readPrivateNotes(session.scope,session.id);if(!valid()){await session.close();return;}const prior=active;if(prior&&prior!==session&&!(await prior.close())){await session.close();throw new Error('Save or export the current deck before closing it.');}if(!valid()){await session.close();return;}stop();active=session;stop=session.state.subscribe(v=>{tick=v.tick;});notes=savedNotes;const first=readSlides(session.data)[0];if(first)select(first.id);roomId=session.record.presentationSession||'';startedLink=roomId?presentationLink(session.scope.server,roomId):'';}
    async function create(){if(scope)await use(await createArtifact(scope,'present','Untitled presentation',doc=>initialize(doc.getMap('data'))));}
    async function open(id:string){if(scope)await use(await openArtifact(scope,id,'present'));}
    async function library(){await noteChain;if(active&&!(await active.close()))throw new Error('Local save failed. Export recovery before leaving.');stop();active=null;}
    function changeText(field:'title'|'body',text:string){if(!active||!current||!editable)return;const value=collection(active.data).get(current.id)?.get(field);if(value instanceof Y.Text)editText(value,text,active.origin);else{error='This imported text field is not editable in the native format.';}}
    function set(field:string,value:unknown){if(!active||!current||!editable)return;const session=active,id=current.id;session.doc.transact(()=>collection(session.data).get(id)?.set(field,value),session.origin);}
    function newSlide(duplicate=false){if(!active||!editable)return;const session=active;session.doc.transact(()=>{select(addSlide(session.data,duplicate&&current?current:{title:'New slide',body:'',layout:'text'},current?.id));},session.origin);}
    function move(direction:number){if(!active||!current)return;const session=active,id=current.id;session.doc.transact(()=>moveSlide(session.data,id,direction),session.origin);}
    function remove(){if(!active||!current)return;if(slides.length<=1){error='Keep at least one slide.';return;}set('removed',true);const next=readSlides(active.data)[0];if(next)select(next.id);}
    function saveNote(value:string){if(!scope||!active||!current)return;const capturedScope=scope,id=active.id,slide=current.id;notes={...notes,[slide]:value};noteStatus='Saving private note…';noteChain=noteChain.catch(()=>{}).then(()=>savePrivateNote(capturedScope,id,slide,value));void noteChain.then(()=>{if(active?.id===id&&selectedId===slide)noteStatus='Private note saved on this device';}).catch(e=>{noteStatus='Private note save failed';error=e instanceof Error?e.message:String(e);});}
    async function image(file:File){if(!active||!current)return;const session=active,id=current.id;const value=await(await import('./files')).rasterImage(file,importAbort.signal);if(active!==session||!scope?.isCurrent())return;session.doc.transact(()=>collection(session.data).get(id)?.set('image',value),session.origin);}
    async function loadFile(file:File){if(!scope)return;if(/\.(pptx|odp)$/i.test(file.name)){if(file.size>12*1024*1024)throw new Error('Presentation import is limited to 12 MB.');pendingOffice=file;return;}if(file.name.endsWith('.wabi.json')){if(file.size>24*1024*1024)throw new Error('Backup exceeds supported size');const value=JSON.parse(await file.text());if(value.schema!==1||value.kind!=='present'||typeof value.update!=='string')throw new Error('Not a native Wabi presentation backup');const source=new Y.Doc();try{Y.applyUpdate(source,from64(value.update));const data=source.getMap('data');validateNative(data);await use(await createArtifact(scope,'present',source.getText('title').toString(),doc=>{const target=doc.getMap('data');target.set('schema',1);target.set('aspect',data.get('aspect')||16/9);target.set('slides',collection(data).clone());},'native',undefined,{name:file.name,type:file.type,blob:file}));if(value.privateNotes&&typeof value.privateNotes==='object'&&active){for(const[id,text]of Object.entries(value.privateNotes))if(typeof text==='string'&&readSlides(active.data).some(s=>s.id===id))await savePrivateNote(scope,active.id,id,text);notes=await readPrivateNotes(scope,active.id);select(selectedId);}}finally{source.destroy();}return;}
        importAbort.abort();importAbort=new AbortController();const sourceScope=scope;const signal=importAbort.signal;const result=await(await import('./files')).importSlides(file,signal,text=>{if(!disposed&&sourceScope?.isCurrent())progress=text;});if(disposed||!sourceScope?.isCurrent()||signal.aborted)return;proposed={title:file.name,...result,source:file};previewDialog.showModal();}
    async function convertedOffice(pdf:File,warnings:string[],original:File){const sourceScope=scope;importAbort.abort();importAbort=new AbortController();const signal=importAbort.signal;const result=await(await import('./files')).importSlides(pdf,signal,text=>{if(!disposed&&sourceScope?.isCurrent())progress=text;});if(disposed||!sourceScope?.isCurrent()||signal.aborted)return;proposed={title:original.name,...result,warnings:[...warnings,...result.warnings],source:original};pendingOffice=null;previewDialog.showModal();}
    async function confirmImport(){if(!scope||!proposed)return;const value=proposed;await use(await createArtifact(scope,'present',value.title,doc=>{const root=doc.getMap('data');root.set('schema',1);root.set('aspect',value.aspect);root.set('slides',new Y.Map());for(const slide of value.slides)addSlide(root,slide);},'native',undefined,value.source?{name:value.source.name,type:value.source.type,blob:value.source}:undefined));previewDialog.close();proposed=null;}
    function previewSource(source:{title:string;content:string}){const generated=fromMarkdown(source.content,source.title);proposed={title:source.title,aspect:16/9,slides:generated.map(s=>({...s,image:null})),warnings:['Headings and explicit breaks proposed these slides. Your Reader document is unchanged.','Review text length and slide boundaries before creating the deck.']};previewDialog.showModal();}
    function presentLocal(){if(!active)return;pinnedLocal=audienceSlides(active.data);if(!pinnedLocal.length){error='Unhide at least one slide before presenting.';return;}localIndex=0;localBlank=false;localDialog.showModal();}
    async function startRoom(){if(!scope||!active)return;const session=active,targetChannel=channelId,approved=editionFingerprint(audienceSlides(session.data),aspect);const valid=()=>!disposed&&active===session&&session.scope.isCurrent();await session.flush();if(!valid())return;await session.publish(session.record.meta?.mode||'snapshot');if(!valid())return;if(approved!==editionFingerprint(audienceSlides(session.data),Number(session.data.get('aspect')||16/9)))throw new Error('The deck changed while preparing the presentation. Review the new preview and start again.');const state=await request<AudienceState>(session.scope,'/presentations',{id:crypto.randomUUID(),artifactId:session.id,channelId:targetChannel||null,sourceSequence:session.record.meta!.sequence});if(!valid())return;roomId=state.id;startedLink=presentationLink(session.scope.server,state.id);await session.rememberPresentation(state.id);if(!valid())return;startDialog.close();openWorkspace('audience',{sessionId:state.id});}
    function exportPrivate(){if(!active)return;const data=JSON.parse(active.recovery());data.privateNotes=notes;download(`${active.title}.private.wabi.json`,JSON.stringify(data,null,2));}
    onMount(()=>{let unsubscribe=()=>{};unregisterNotes=registerWorkspaceDisposer('present',()=>noteChain);void run(async()=>{scope=await captureScope();unsubscribe=targets.subscribe(value=>{if(value.present&&value.present!==previous){previous=value.present;const target=value.present;if(target.id)void run(()=>open(target.id!));else if(target.source)previewSource(target.source);}});});return()=>unsubscribe();});
    onDestroy(()=>{disposed=true;epoch++;stop();unregisterNotes();importAbort.abort();if(active)void active.close();});
</script>
{#if scope&&pendingOffice}<OfficeConversion {scope} file={pendingOffice} onconverted={convertedOffice} oncancel={()=>{importAbort.abort();pendingOffice=null;}}/>{/if}
{#if scope&&active}{#key active.id}<ArtifactShell session={active} selectionAnchor={current?slideAnchor(current.id,current.title):null} onlibrary={()=>void run(library)}>
    <div class="workspace-toolbar deck-tools"><button onclick={presentLocal}>Present locally</button><button disabled={busy} onclick={()=>{channelId='';startDialog.showModal();}}>Present to channel…</button><button disabled={busy} onclick={()=>void run(async()=>{if(active)await(await import('./files')).exportPptx(active.title,audienceSlides(active.data),aspect);})}>Export PPTX subset</button><button onclick={()=>{if(active)void import('./files').then(m=>m.printAudience(active!.title,audienceSlides(active!.data),aspect)).catch(e=>error=e.message);}}>Print / Save audience PDF</button><button onclick={exportPrivate}>Export private notes backup</button>{#if roomId}<PresentedVersion session={active} {roomId}/>{/if}</div>
    {#if startedLink}<p class="deck-note">Presentation link: <input readonly value={startedLink} aria-label="Presentation link"/><button onclick={()=>void navigator.clipboard.writeText(startedLink)}>Copy</button><button onclick={()=>openWorkspace('audience',{sessionId:roomId})}>Open room view</button></p>{/if}
    <div class="deck-layout"><aside class="slide-list" aria-label="Slides"><div class="workspace-toolbar"><button disabled={!editable} onclick={()=>void run(async()=>newSlide())}>Add</button><button disabled={!editable} onclick={()=>void run(async()=>newSlide(true))}>Duplicate</button></div>{#each slides as slide,i(slide.id)}<button class:chosen={slide.id===current?.id} onclick={()=>select(slide.id)}><small>{i+1}{slide.hidden?' · Hidden':''}</small><strong>{slide.title||'Untitled'}</strong></button>{/each}<div class="workspace-toolbar"><button disabled={!editable} onclick={()=>void run(async()=>move(-1))}>Move up</button><button disabled={!editable} onclick={()=>void run(async()=>move(1))}>Move down</button><button disabled={!editable} onclick={remove}>Remove</button></div></aside>
    <main class="deck-canvas"><AudienceSlideView slide={current} {aspect}/>{#if current}<div class="workspace-toolbar"><select aria-label="Slide layout" disabled={!editable} value={current.layout} onchange={event=>set('layout',event.currentTarget.value)}><option value="title">Title</option><option value="text">Text</option><option value="split">Text and image</option><option value="image">Full image</option><option value="quote">Quotation</option></select><button disabled={!editable} onclick={()=>imageInput.click()}>Add / replace image</button>{#if current.image}<button disabled={!editable} onclick={()=>set('image',null)}>Remove image</button>{/if}<button disabled={!editable} onclick={()=>set('hidden',!current.hidden)}>{current.hidden?'Include in audience':'Hide from audience'}</button><label>Ratio <select disabled={!editable} value={aspect} onchange={event=>{const session=active!;session.doc.transact(()=>session.data.set('aspect',Number(event.currentTarget.value)),session.origin);}}><option value={16/9}>16:9</option><option value={4/3}>4:3</option><option value={1}>Square</option></select></label></div>
        <label>Slide title<input aria-label="Slide title" value={current.title} maxlength="2000" disabled={!editable} oninput={event=>changeText('title',event.currentTarget.value)}/></label><label>Slide text<textarea aria-label="Slide text" value={current.body} maxlength="16000" disabled={!editable} oninput={event=>changeText('body',event.currentTarget.value)}></textarea></label>
        <label>Private speaker notes<textarea aria-label="Private speaker notes" bind:value={note} maxlength="32000" oninput={event=>saveNote(event.currentTarget.value)}></textarea></label><small role="status">{noteStatus}. Notes are never included in the audience rendition, shared deck, or ordinary PPTX/PDF export.</small>
    {/if}</main></div>
    <input class="workspace-file-input" type="file" accept="image/png,image/jpeg,image/webp" bind:this={imageInput} onchange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(file)void run(()=>image(file));}}/>
</ArtifactShell>{/key}
{:else if scope}<section class="wabi-workspace"><ArtifactLibrary {scope} kind="present" label="Present" onopen={id=>void run(()=>open(id))} onnew={()=>void run(create)} onimport={file=>void run(()=>loadFile(file))} accept=".pdf,.png,.jpg,.jpeg,.webp,.pptx,.odp,.wabi.json"/></section>{/if}
{#if busy}<div class="workspace-home-note" role="status">{progress||'Saving presentation…'}<button onclick={()=>importAbort.abort()}>Cancel import</button></div>{/if}{#if error}<div class="workspace-home-note" role="alert">{error}</div>{/if}
<dialog class="workspace-dialog" bind:this={previewDialog}><h2>Create a private presentation</h2>{#if proposed}<label>Deck title<input aria-label="Proposed deck title" bind:value={proposed.title} maxlength="200" disabled={busy}/></label><p>{proposed.slides.length} proposed slides · edit text and order before creating a separate private deck.</p>{#each proposed.warnings as warning}<p>{warning}</p>{/each}<div class="import-preview">{#each proposed.slides as slide,i}<h3>Slide {i+1}</h3><label>Title<input aria-label={`Proposed slide ${i+1} title`} bind:value={slide.title} maxlength="2000" disabled={busy}/></label><label>Text<textarea aria-label={`Proposed slide ${i+1} text`} bind:value={slide.body} maxlength="16000" disabled={busy}></textarea></label><div class="workspace-toolbar"><button disabled={busy||i===0} onclick={()=>{if(proposed){const item=proposed.slides.splice(i,1)[0];proposed.slides.splice(i-1,0,item);}}}>Move earlier</button><button disabled={busy||i===proposed.slides.length-1} onclick={()=>{if(proposed){const item=proposed.slides.splice(i,1)[0];proposed.slides.splice(i+1,0,item);}}}>Move later</button><button disabled={busy||proposed.slides.length<=1} onclick={()=>proposed?.slides.splice(i,1)}>Remove proposed slide</button></div><AudienceSlideView slide={{...slide,id:String(i)}} aspect={proposed.aspect}/>{/each}</div>{/if}<div class="workspace-toolbar"><button disabled={busy} onclick={()=>{previewDialog.close();proposed=null;}}>Cancel</button><button disabled={busy} onclick={()=>void run(confirmImport)}>Create private deck</button></div>{#if error}<p role="alert">{error}</p>{/if}</dialog>
<dialog class="workspace-dialog" bind:this={startDialog}><h2>Present {liveTitle}</h2><p>This uploads the native deck to your Wabi server under its existing access rules, then publishes only visible slides to the audience. The server operator can read uploaded slides. Speaker notes stay on this device.</p><label>Audience channel<select bind:value={channelId}><option value="">Only people already allowed to read the deck</option>{#each $channels as channel(channel.id)}<option value={channel.id}>{channel.name}</option>{/each}</select></label>{#if active}<p>{audienceSlides(active.data).length} visible slides will be published. Hidden slides are excluded from the audience payload.</p><div class="import-preview">{#each audienceSlides(active.data) as slide(slide.id)}<AudienceSlideView {slide} {aspect}/>{/each}</div>{/if}<div class="workspace-toolbar"><button disabled={busy} onclick={()=>startDialog.close()}>Cancel</button><button disabled={busy} onclick={()=>void run(startRoom)}>Start approved presentation</button></div>{#if error}<p role="alert">{error}</p>{/if}</dialog>
<dialog class="local-presentation" bind:this={localDialog}><div bind:this={localSurface} class="local-audience"><AudienceSlideView slide={pinnedLocal[localIndex]||null} {aspect} blank={localBlank}/></div><div class="workspace-toolbar"><button disabled={localIndex<=0} onclick={()=>localIndex--}>Previous</button><span>{localIndex+1} / {pinnedLocal.length}</span><button disabled={localIndex>=pinnedLocal.length-1} onclick={()=>localIndex++}>Next</button><button onclick={()=>localBlank=!localBlank}>{localBlank?'Show slides':'Blank screen'}</button><button onclick={()=>void localSurface.requestFullscreen().catch(()=>error='Fullscreen unavailable')}>Audience fullscreen</button><button onclick={()=>localDialog.close()}>End local presentation</button></div><p class="local-notes">Private notes: {notes[pinnedLocal[localIndex]?.id]||'No notes for this slide'}</p></dialog>
<style>.deck-tools{padding:.6rem;font-size:.8rem}.deck-layout{height:calc(100% - 60px);display:flex;min-height:0}.slide-list{width:180px;flex-shrink:0;padding:.5rem;overflow:auto;border-right:1px solid var(--border-subtle,#444)}.slide-list>button{display:flex;flex-direction:column;gap:.35rem;width:100%;margin:.45rem 0;text-align:left;min-height:65px}.slide-list .chosen{outline:2px solid var(--accent-primary,#aea4ff)}.deck-canvas{padding:1rem;flex:1;min-width:0;overflow:auto}.deck-canvas :global(.audience-slide){max-width:900px;margin:auto}.deck-canvas>label{display:grid;gap:.4rem;margin:.65rem 0}.deck-canvas textarea{min-height:100px}.deck-canvas small{color:var(--text-secondary,#bbb)}.deck-note{margin:.3rem 1rem;font-size:.8rem}.deck-note input{max-width:55%}.import-preview{display:grid;gap:1rem;max-height:45vh;overflow:auto;margin:1rem 0}.local-presentation{width:min(95vw,1200px);background:#111622;color:#eee;border:1px solid #444;border-radius:8px}.local-presentation::backdrop{background:#000c}.local-audience{max-height:72vh;display:flex;justify-content:center}.local-audience:fullscreen{background:#000;display:flex;align-items:center;max-height:none}.local-audience:fullscreen :global(.audience-slide){height:100%;max-height:100vh}.local-presentation .workspace-toolbar{padding:1rem}.local-presentation button{padding:.5rem .8rem}.local-notes{white-space:pre-wrap;margin:.5rem 1rem;max-height:15vh;overflow:auto}@media(max-width:650px){.slide-list{width:110px}.deck-canvas{padding:.5rem}.deck-tools{gap:.3rem}.deck-layout{height:calc(100% - 100px)}}
</style>
