import { test, expect } from 'bun:test';
import * as Y from 'yjs';
import { initialize, addSlide, readSlides, collection, audienceSlides, moveSlide, validateNative, fromMarkdown } from './model';
function deck(){const doc=new Y.Doc();initialize(doc.getMap('data'),'Opening');return doc;}
test('audience views contain visible slide fields only',()=>{const d=deck(),data=d.getMap('data');addSlide(data,{title:'Do not publish',body:'Secret',hidden:true});const result=audienceSlides(data);expect(result.length).toBe(1);expect(Object.keys(result[0]).sort()).toEqual(['body','id','image','layout','title']);expect(JSON.stringify(result)).not.toContain('Secret');d.destroy();});
test('a notes field is rejected rather than hidden with CSS',()=>{const d=deck(),data=d.getMap('data'),id=readSlides(data)[0].id;collection(data).get(id)!.set('notes','PRIVATE');expect(()=>validateNative(data)).toThrow();d.destroy();});
test('slide reordering keeps the same IDs',()=>{const d=deck(),data=d.getMap('data');const first=readSlides(data)[0].id,second=addSlide(data,{title:'Second'});moveSlide(data,second,-1);expect(readSlides(data).map(s=>s.id)).toEqual([second,first]);d.destroy();});
test('independent edits to slide text merge through Y.Text',()=>{const seed=deck(),update=Y.encodeStateAsUpdate(seed),a=new Y.Doc(),b=new Y.Doc();Y.applyUpdate(a,update);Y.applyUpdate(b,update);const id=readSlides(a.getMap('data'))[0].id;const at=collection(a.getMap('data')).get(id)!.get('body') as Y.Text,bt=collection(b.getMap('data')).get(id)!.get('body') as Y.Text;at.insert(0,'A: ');bt.insert(bt.length,' :B');const au=Y.encodeStateAsUpdate(a),bu=Y.encodeStateAsUpdate(b);Y.applyUpdate(a,bu);Y.applyUpdate(b,au);expect(at.toString()).toBe(bt.toString());expect(at.toString()).toContain('A: ');expect(at.toString()).toContain(' :B');seed.destroy();a.destroy();b.destroy();});
test('Markdown conversion proposes slides without changing the source',()=>{const source='# Welcome\n\nIntroduction\n\n---\n\n## Practice\n\nTry it.';const before=source;const result=fromMarkdown(source,'Lesson');expect(result.map(s=>s.title)).toEqual(['Welcome','Practice']);expect(source).toBe(before);});
test('native deck import rejects external images',()=>{const d=deck(),data=d.getMap('data'),id=readSlides(data)[0].id;collection(data).get(id)!.set('image','https://example.invalid/tracker');expect(()=>validateNative(data)).toThrow();d.destroy();});
