import type {Fields,Json} from '../../workspaceArtifacts/model';
import {xml,all,children,first,text,local,escape as x,partPath,type XNode} from '../../workspaceArtifacts/formats/xml';
import {readZip,zipText,writeZip,type ZipEntry} from '../../workspaceArtifacts/formats/zip';
import {audiencePages,key,slideIds,slide,asJson} from './model';
import type {Page} from '../../workspaceArtifacts/presentation';

export interface DeckImport {fields:Fields;warnings:string[]}
export interface DeckExport {name:string;bytes:Uint8Array;mime:string;warnings:string[]}
const DEC='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships',PKG='http://schemas.openxmlformats.org/package/2006/relationships';
const ODF='xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:xlink="http://www.w3.org/1999/xlink"';
const safeName=(value:unknown,ext:string)=>String(value||'presentation').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,100)+'.'+ext;
const color=(node:XNode|undefined,fallback:string)=>{const v=node&&first(node,'srgbClr')?.attrs.val;return v&&/^[0-9a-f]{6}$/i.test(v)?'#'+v:fallback;};
function dataImage(value:string):{bytes:Uint8Array;extension:string;mime:string}{const match=value.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match)throw new Error('Only embedded raster images may be exported');const raw=atob(match[2]);if(raw.length>4*1024*1024)throw new Error('Image exceeds its limit');return {bytes:Uint8Array.from(raw,c=>c.charCodeAt(0)),extension:match[1]==='jpeg'?'jpg':match[1],mime:'image/'+match[1]};}
async function imagePart(zip:Map<string,ZipEntry>,path:string):Promise<ImageBitmap>{
  const entry=zip.get(path);if(!entry||entry.size>12*1024*1024||!/(?:\.png|\.jpe?g|\.webp)$/i.test(path))throw new Error('Unsupported or oversized slide image');
  const bytes=await entry.read();const bitmap=await createImageBitmap(new Blob([bytes as Uint8Array<ArrayBuffer>]));if(bitmap.width*bitmap.height>40_000_000){bitmap.close();throw new Error('Slide image dimensions exceed the limit');}return bitmap;
}
async function dataUrl(canvas:OffscreenCanvas):Promise<string>{const blob=await canvas.convertToBlob({type:'image/png'});if(blob.size>3*1024*1024)throw new Error('Flattened slide exceeds the 3 MiB raster limit');const bytes=new Uint8Array(await blob.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=16384)raw+=String.fromCharCode(...bytes.subarray(i,i+16384));return 'data:image/png;base64,'+btoa(raw);}
function wrap(context:OffscreenCanvasRenderingContext2D,value:string,width:number):string[]{
  const out:string[]=[];for(const paragraph of value.split('\n')){let line='';for(const char of paragraph){const next=line+char;if(line&&context.measureText(next).width>width){out.push(line);line=char;}else line=next;}out.push(line);}return out;
}
function drawText(context:OffscreenCanvasRenderingContext2D,value:string,left:number,top:number,width:number,height:number,size:number,fill:string,bold=false){
  if(!value||width<=0||height<=0)return;context.save();context.beginPath();context.rect(left,top,width,height);context.clip();context.fillStyle=fill;context.textBaseline='top';context.font=`${bold?'bold ':''}${Math.max(8,Math.min(180,size))}px sans-serif`;let y=top;for(const line of wrap(context,value,width)){if(y>top+height)break;context.fillText(line,left,y);y+=size*1.25;}context.restore();
}
function addPage(fields:Fields,page:Page,hidden=false){const id=crypto.randomUUID();(fields.slides as Json[]).push(id);fields[key(id)]={title:page.title,body:page.body,layout:page.layout,image:page.image,hidden};}
/** Imports create explicitly flattened review pages. No macros, links, embedded
 * media, notes, or scripts are executed or placed in the audience document. */
export async function importDeckBytes(bytes:ArrayBuffer,name:string):Promise<DeckImport>{
  if(typeof OffscreenCanvas==='undefined')throw new Error('This browser lacks isolated slide rendering. Import images/PDF or use a current desktop browser.');
  const zip=await readZip(bytes),warnings=['Office slides are reconstructed as static images, not editable Office objects. Fonts use this device’s sans-serif fallback. Masters, animations, transitions, charts, grouped shapes, rotations, shadows, and embedded media may differ or be omitted. Review every page before presenting; the original file is preserved.'],fields:Fields={title:name.replace(/\.(pptx|odp)$/i,''),slides:[],theme:'paper',aspect:16/9};
  if(/\.pptx$/i.test(name)){
    const root=xml(await zipText(zip,'ppt/presentation.xml')),size=first(root,'sldSz'),cx=Number(size?.attrs.cx)||12192000,cy=Number(size?.attrs.cy)||6858000;
    if(!Number.isFinite(cx)||!Number.isFinite(cy)||cx<=0||cy<=0||cx/cy<.5||cx/cy>3)throw new Error('Unsupported slide dimensions');fields.aspect=cx/cy;
    const rels=all(xml(await zipText(zip,'ppt/_rels/presentation.xml.rels')),'Relationship'),map=new Map(rels.filter(n=>n.attrs.TargetMode!=='External').map(n=>[n.attrs.Id,partPath('ppt/presentation.xml',n.attrs.Target)]));
    const ids=all(root,'sldId');if(!ids.length||ids.length>300)throw new Error('A deck must contain 1–300 slides');
    for(let index=0;index<ids.length;index++){
      const path=map.get(ids[index].attrs['r:id']);if(!path)throw new Error('Missing slide relationship');const doc=xml(await zipText(zip,path)),relpath=path.replace(/([^/]+)$/,'_rels/$1.rels');
      const references=zip.has(relpath)?all(xml(await zipText(zip,relpath)),'Relationship'):[],assets=new Map(references.filter(n=>n.attrs.TargetMode!=='External').map(n=>[n.attrs.Id,partPath(path,n.attrs.Target)]));
      const scale=1200/cx,canvas=new OffscreenCanvas(1200,Math.round(cy*scale)),context=canvas.getContext('2d');if(!context)throw new Error('Slide rendering is unavailable');context.fillStyle=color(first(doc,'bgPr'),'#ffffff');context.fillRect(0,0,canvas.width,canvas.height);
      const tree=first(doc,'spTree');let textual='',fallbackY=60;
      for(const shape of tree?children(tree):[]){
        const type=local(shape.name);if(!['sp','pic'].includes(type))continue;
        const transform=first(shape,'xfrm'),offset=transform&&first(transform,'off'),extent=transform&&first(transform,'ext');
        const left=offset?Number(offset.attrs.x)*scale:60,top=offset?Number(offset.attrs.y)*scale:fallbackY,width=extent?Number(extent.attrs.cx)*scale:1080,height=extent?Number(extent.attrs.cy)*scale:200;
        if(![left,top,width,height].every(Number.isFinite)||width<0||height<0||width>10000||height>10000)throw new Error('Invalid shape geometry');
        if(type==='pic'){const ref=first(shape,'blip')?.attrs['r:embed'],asset=ref&&assets.get(ref);if(asset){try{const bitmap=await imagePart(zip,asset);try{context.drawImage(bitmap,left,top,width,height);}finally{bitmap.close();}}catch{warnings.push(`Slide ${index+1}: an unsupported or oversized image was omitted.`);}}continue;}
        const body=first(shape,'txBody'),paragraphs=body?children(body,'p'):[],value=paragraphs.map(p=>all(p,'t').map(text).join('')).join('\n');if(!value)continue;textual+=value+'\n';
        const run=first(shape,'rPr')||first(shape,'defRPr'),fontSize=(Number(run?.attrs.sz)||2400)/100*12700*scale;
        drawText(context,value,left,top,width,height,fontSize,color(run,'#17202a'),run?.attrs.b==='1');fallbackY+=height+20;
      }
      const page:Page={id:'',title:`Slide ${index+1}`,body:textual.trim().slice(0,50000),layout:'image',image:await dataUrl(canvas)};
      // PageView renders the image alone for imported raster pages. The body is
      // accessible source text, not a second visual layer on the raster.
      addPage(fields,page,doc.attrs.show==='0');
      if(JSON.stringify(fields).length>32*1024*1024)throw new Error('Flattened deck exceeds 32 MiB; split the source deck first');
    }
  }else if(/\.odp$/i.test(name)){
    const doc=xml(await zipText(zip,'content.xml')),styles=zip.has('styles.xml')?xml(await zipText(zip,'styles.xml')):doc,props=first(styles,'page-layout-properties');
    const cm=(v:string|undefined,defaultValue:number)=>{if(!v)return defaultValue;const m=v.match(/^([0-9.]+)(cm|mm|in|pt|px)$/);if(!m)throw new Error('Unsupported ODP length');return Number(m[1])*({cm:1,mm:.1,in:2.54,pt:2.54/72,px:2.54/96}[m[2]]||1);};
    const width=cm(props?.attrs['fo:page-width'],33.867),height=cm(props?.attrs['fo:page-height'],19.05);if(width<=0||height<=0||width/height<.5||width/height>3)throw new Error('Invalid slide dimensions');fields.aspect=width/height;const scale=1200/width,pages=all(doc,'page');if(!pages.length||pages.length>300)throw new Error('A deck must contain 1–300 slides');
    for(let index=0;index<pages.length;index++){const page=pages[index],canvas=new OffscreenCanvas(1200,Math.round(height*scale)),context=canvas.getContext('2d');if(!context)throw new Error('Slide rendering is unavailable');context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);let textual='';
      for(const frame of all(page,'frame')){const left=cm(frame.attrs['svg:x'],1)*scale,top=cm(frame.attrs['svg:y'],1)*scale,w=cm(frame.attrs['svg:width'],width-2)*scale,h=cm(frame.attrs['svg:height'],4)*scale;if(![left,top,w,h].every(Number.isFinite)||w<0||h<0||w>10000||h>10000)throw new Error('Invalid ODP frame');
        const image=first(frame,'image'),href=image?.attrs['xlink:href'];if(href){try{const bitmap=await imagePart(zip,partPath('content.xml',href));try{context.drawImage(bitmap,left,top,w,h);}finally{bitmap.close();}}catch{warnings.push(`Slide ${index+1}: an unsupported or external image was omitted.`);}}
        const box=first(frame,'text-box');if(box){const value=all(box,'p').map(text).join('\n');textual+=value+'\n';drawText(context,value,left,top,w,h,26,'#17202a',frame.attrs['presentation:class']==='title');}
      }
      addPage(fields,{id:'',title:page.attrs['draw:name']||`Slide ${index+1}`,body:textual.trim().slice(0,50000),layout:'image',image:await dataUrl(canvas)});
      if(JSON.stringify(fields).length>32*1024*1024)throw new Error('Flattened deck exceeds 32 MiB; split the source deck first');
    }
  }else throw new Error('Unsupported Office deck container');
  return {fields,warnings:[...new Set(warnings)]};
}
function slideText(id:number,title:string,value:string,left:number,top:number,width:number,height:number,size:number,color:string){return `<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${x(title)}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${left}" y="${top}"/><a:ext cx="${width}" cy="${height}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>${value.split('\n').map(line=>`<a:p><a:r><a:rPr lang="en-US" sz="${size}" dirty="0"><a:solidFill><a:srgbClr val="${color}"/></a:solidFill><a:latin typeface="Arial"/></a:rPr><a:t xml:space="preserve">${x(line)}</a:t></a:r><a:endParaRPr lang="en-US" sz="${size}"/></a:p>`).join('')}</p:txBody></p:sp>`;}
const treeStart='<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>';
export function exportDeckBytes(fields:Fields,format:'pptx'|'odp'|'html'):DeckExport{
  const pages=audiencePages(fields);if(!pages.length)throw new Error('No visible slides to export');const aspect=Number(fields.aspect)||16/9,warnings=['Only visible audience slides are exported. Speaker notes, hidden slides, comments, and history are excluded. Native Wabi backup preserves the editable source separately.'];
  if(format==='html'){
    const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data:; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'"><title>'+x(fields.title)+'</title><style>body{margin:0;font-family:Arial,sans-serif;background:#e5e7eb}section{box-sizing:border-box;max-width:1200px;aspect-ratio:'+aspect+';margin:24px auto;padding:5%;background:white;overflow:hidden;break-after:page}h1{font-size:32pt;margin:0 0 22px}p{font-size:20pt;white-space:pre-wrap;margin:0}img{max-width:100%;max-height:75%;object-fit:contain}.image{padding:0;position:relative}.image img{width:100%;height:100%;max-height:100%}.image h1,.image p{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}@media print{@page{size:'+ (aspect>1?'landscape':'portrait')+';margin:0}body{background:white}section{margin:0;max-width:none;height:100vh;width:100%;page-break-after:always}}</style>'+pages.map(p=>`<section class="${p.layout==='image'?'image':''}"><h1>${x(p.title)}</h1>${p.image?`<img src="${x(p.image)}" alt="${x(p.body||p.title)}">`:''}<p>${x(p.body)}</p></section>`).join('')+'</html>';
    return {name:safeName(fields.title,'html'),bytes:new TextEncoder().encode(html),mime:'text/html;charset=utf-8',warnings:[...warnings,'Use your browser’s print dialog to produce PDF. Inspect page scaling before saving.']};
  }
  const parts:Record<string,string|Uint8Array>={},images:Record<number,{path:string;mime:string}>={};
  pages.forEach((p,i)=>{if(p.image){const image=dataImage(p.image);if(image.extension==='webp')throw new Error('PPTX/ODP export needs PNG/JPEG images. Reinsert the image as PNG or export audience HTML.');const path=(format==='pptx'?'ppt/media/':'Pictures/')+`image${i+1}.`+image.extension;parts[path]=image.bytes;images[i]={path,mime:image.mime};}});
  if(format==='pptx'){
    const width=12192000,height=Math.round(width/aspect),slideTags:string[]=[],contentTypes:string[]=[],presentationRels:string[]=[];
    pages.forEach((p,i)=>{const index=i+1,bg=p.theme==='night'?'141927':p.theme==='sage'?'E8EEE4':'FFFFFF',ink=p.theme==='night'?'F1F5F9':'17202A',rels:string[]=[`<Relationship Id="layout" Type="${R}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>`];let shapes='';
      if(p.layout!=='image'){shapes+=slideText(2,'Title',p.title,600000,400000,width-1200000,1100000,3200,ink);shapes+=slideText(3,'Body',p.body,600000,1700000,p.image?Math.round(width*.45):width-1200000,height-2100000,2200,ink);}
      if(images[i]){const full=p.layout==='image';rels.push(`<Relationship Id="image" Type="${R}/image" Target="../media/${images[i].path.split('/').at(-1)}"/>`);const left=full?0:Math.round(width*.53),top=full?0:1700000,cx=full?width:Math.round(width*.42),cy=full?height:height-2100000;shapes+=`<p:pic><p:nvPicPr><p:cNvPr id="4" name="Slide image" descr="${x(p.body||p.title)}"/><p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="image"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="${left}" y="${top}"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>`;}
      parts[`ppt/slides/slide${index}.xml`]=DEC+`<p:sld xmlns:a="${A}" xmlns:r="${R}" xmlns:p="${P}"><p:cSld name="${x(p.title)}"><p:bg><p:bgPr><a:solidFill><a:srgbClr val="${bg}"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree>${treeStart}${shapes}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`;
      parts[`ppt/slides/_rels/slide${index}.xml.rels`]=DEC+`<Relationships xmlns="${PKG}">${rels.join('')}</Relationships>`;slideTags.push(`<p:sldId id="${255+index}" r:id="slide${index}"/>`);presentationRels.push(`<Relationship Id="slide${index}" Type="${R}/slide" Target="slides/slide${index}.xml"/>`);contentTypes.push(`<Override PartName="/ppt/slides/slide${index}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`);
    });
    parts['ppt/presentation.xml']=DEC+`<p:presentation xmlns:a="${A}" xmlns:r="${R}" xmlns:p="${P}"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="master"/></p:sldMasterIdLst><p:sldIdLst>${slideTags.join('')}</p:sldIdLst><p:sldSz cx="${width}" cy="${height}"/><p:notesSz cx="6858000" cy="9144000"/><p:defaultTextStyle/></p:presentation>`;
    parts['ppt/_rels/presentation.xml.rels']=DEC+`<Relationships xmlns="${PKG}"><Relationship Id="master" Type="${R}/slideMaster" Target="slideMasters/slideMaster1.xml"/>${presentationRels.join('')}</Relationships>`;
    parts['_rels/.rels']=DEC+`<Relationships xmlns="${PKG}"><Relationship Id="office" Type="${R}/officeDocument" Target="ppt/presentation.xml"/></Relationships>`;
    const map='<p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/>';
    parts['ppt/slideMasters/slideMaster1.xml']=DEC+`<p:sldMaster xmlns:a="${A}" xmlns:r="${R}" xmlns:p="${P}"><p:cSld><p:spTree>${treeStart}</p:spTree></p:cSld>${map}<p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="layout"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`;
    parts['ppt/slideMasters/_rels/slideMaster1.xml.rels']=DEC+`<Relationships xmlns="${PKG}"><Relationship Id="layout" Type="${R}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="theme" Type="${R}/theme" Target="../theme/theme1.xml"/></Relationships>`;
    parts['ppt/slideLayouts/slideLayout1.xml']=DEC+`<p:sldLayout xmlns:a="${A}" xmlns:r="${R}" xmlns:p="${P}" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree>${treeStart}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`;
    parts['ppt/slideLayouts/_rels/slideLayout1.xml.rels']=DEC+`<Relationships xmlns="${PKG}"><Relationship Id="master" Type="${R}/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`;
    const colors={dk1:'000000',lt1:'FFFFFF',dk2:'17202A',lt2:'F3F4F6',accent1:'476A56',accent2:'436A92',accent3:'967146',accent4:'7A6091',accent5:'4D8585',accent6:'A15C64',hlink:'0563C1',folHlink:'954F72'};
    parts['ppt/theme/theme1.xml']=DEC+`<a:theme xmlns:a="${A}" name="Wabi"><a:themeElements><a:clrScheme name="Wabi">${Object.entries(colors).map(([k,v])=>`<a:${k}><a:srgbClr val="${v}"/></a:${k}>`).join('')}</a:clrScheme><a:fontScheme name="Wabi"><a:majorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="Wabi"><a:fillStyleLst>${'<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'.repeat(3)}</a:fillStyleLst><a:lnStyleLst>${'<a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln>'.repeat(3)}</a:lnStyleLst><a:effectStyleLst>${'<a:effectStyle><a:effectLst/></a:effectStyle>'.repeat(3)}</a:effectStyleLst><a:bgFillStyleLst>${'<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'.repeat(3)}</a:bgFillStyleLst></a:fmtScheme></a:themeElements><a:objectDefaults/><a:extraClrSchemeLst/></a:theme>`;
    parts['[Content_Types].xml']=DEC+`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="jpg" ContentType="image/jpeg"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>${contentTypes.join('')}</Types>`;
  }else{
    // ODF requires its uncompressed mimetype part first in the ZIP.
    const imageParts={...parts};for(const k of Object.keys(parts))delete parts[k];parts.mimetype='application/vnd.oasis.opendocument.presentation';Object.assign(parts,imageParts);
    const width=33.867,height=width/aspect;
    const paragraphs=(value:string)=>value.split('\n').map(line=>'<text:p>'+x(line)+'</text:p>').join('');
    parts['content.xml']=DEC+`<office:document-content ${ODF} office:version="1.3"><office:automatic-styles><style:style style:name="title" style:family="graphic"><style:text-properties fo:font-size="32pt" fo:font-weight="bold"/></style:style><style:style style:name="body" style:family="graphic"><style:text-properties fo:font-size="22pt"/></style:style></office:automatic-styles><office:body><office:presentation>${pages.map((p,i)=>`<draw:page draw:name="${x(p.title||'Slide '+(i+1))}" draw:master-page-name="Default">${p.layout==='image'?'':`<draw:frame draw:style-name="title" svg:x="1.5cm" svg:y="1cm" svg:width="${width-3}cm" svg:height="3cm"><draw:text-box>${paragraphs(p.title)}</draw:text-box></draw:frame><draw:frame draw:style-name="body" svg:x="1.5cm" svg:y="4.5cm" svg:width="${p.image?width*.43:width-3}cm" svg:height="${height-6}cm"><draw:text-box>${paragraphs(p.body)}</draw:text-box></draw:frame>`}${images[i]?`<draw:frame svg:x="${p.layout==='image'?0:width*.53}cm" svg:y="${p.layout==='image'?0:4.5}cm" svg:width="${p.layout==='image'?width:width*.42}cm" svg:height="${p.layout==='image'?height:height-6}cm"><draw:image xlink:href="${images[i].path}" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"/></draw:frame>`:''}</draw:page>`).join('')}</office:presentation></office:body></office:document-content>`;
    parts['styles.xml']=DEC+`<office:document-styles ${ODF} office:version="1.3"><office:styles/><office:automatic-styles><style:page-layout style:name="PM1"><style:page-layout-properties fo:page-width="${width}cm" fo:page-height="${height}cm" style:print-orientation="landscape"/></style:page-layout></office:automatic-styles><office:master-styles><style:master-page style:name="Default" style:page-layout-name="PM1"/></office:master-styles></office:document-styles>`;
    parts['META-INF/manifest.xml']=DEC+`<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.presentation"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/><manifest:file-entry manifest:full-path="styles.xml" manifest:media-type="text/xml"/>${Object.values(images).map(image=>`<manifest:file-entry manifest:full-path="${image.path}" manifest:media-type="${image.mime}"/>`).join('')}</manifest:manifest>`;
    warnings.push('ODP export uses a plain background and basic text/image layout; theme colours may differ.');
  }
  return {name:safeName(fields.title,format),bytes:writeZip(parts),mime:format==='pptx'?'application/vnd.openxmlformats-officedocument.presentationml.presentation':'application/vnd.oasis.opendocument.presentation',warnings};
}
