#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
FRONTEND_ENV_FILE="$ROOT_DIR/frontend/.env"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.yml}"

RECONFIGURE=false
USE_TURN_PROFILE="${USE_TURN_PROFILE:-true}"
USE_SRT_GATEWAY_PROFILE="${USE_SRT_GATEWAY_PROFILE:-auto}"
PRUNE_DANGLING_IMAGES="${PRUNE_DANGLING_IMAGES:-true}"
PRUNE_STOPPED_CONTAINERS="${PRUNE_STOPPED_CONTAINERS:-false}"

usage() {
  cat <<'EOF'
Usage: scripts/launch.sh [options]

Single command for first-run setup + normal deployment updates.

Options:
  --mode <normal|community>   Override WABI_MODE.
  --runtime <node|bun>        Override WABI_RUNTIME.
  --reconfigure            Regenerate .env and frontend/.env using setup defaults.
  --no-turn-profile        Do not deploy coturn profile.
  --srt-gateway            Force deploy media-gateway profile.
  --no-srt-gateway         Force skip media-gateway profile.
  --no-prune-images        Skip dangling image prune.
  --prune-stopped          Also prune all stopped containers.
  -h, --help               Show help.

Advanced environment overrides:
  WABI_MODE=normal|community           (default: normal)
  WABI_RUNTIME=node|bun                (default: node)
  WABI_DOMAIN=<domain|localhost|no>    (default: localhost)
  TURN_EXTERNAL_IP=<ip>                (default: auto-detect or 127.0.0.1)
  GIPHY_KEY=<key>                      (default: empty)
  USE_TURN_PROFILE=true|false          (default: true)
  USE_SRT_GATEWAY_PROFILE=auto|true|false (default: auto; true when MEDIA_SRT_GATEWAY_ENABLED=true)
  PRUNE_DANGLING_IMAGES=true|false     (default: true)
  PRUNE_STOPPED_CONTAINERS=true|false  (default: false)
EOF
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n'
  else
    printf '%s' "$(date +%s)-$$-wabi-secret-$(od -An -N8 -tx1 /dev/urandom 2>/dev/null | tr -d ' \n' || echo fallback)"
  fi
}

generate_hex_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    generate_secret | tr -dc 'A-Za-z0-9' | cut -c1-48
  fi
}

validate_prereqs() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "[launch] Docker is required but not found on PATH." >&2
    exit 1
  fi
  if ! docker compose version >/dev/null 2>&1; then
    echo "[launch] Docker Compose plugin is required but not available." >&2
    exit 1
  fi
}

normalize_domain() {
  local raw="${1:-localhost}"
  local lowered="${raw,,}"
  if [[ -z "$raw" || "$lowered" == "no" ]]; then
    echo "localhost"
    return
  fi
  raw="${raw#http://}"
  raw="${raw#https://}"
  raw="${raw%%/*}"
  echo "${raw:-localhost}"
}

configure_defaults() {
  local domain mode runtime public_ip frontend_url public_url turn_realm turn_secret jwt_secret
  local db_mode postgres_db postgres_user postgres_password database_url giphy_key

  domain="$(normalize_domain "${WABI_DOMAIN:-localhost}")"
  mode="${WABI_MODE:-normal}"
  runtime="${WABI_RUNTIME:-node}"
  giphy_key="${GIPHY_KEY:-${VITE_GIPHY_API_KEY:-}}"

  if [[ "$mode" != "normal" && "$mode" != "community" ]]; then
    echo "[launch] Invalid WABI_MODE: $mode (expected normal|community)" >&2
    exit 1
  fi
  if [[ "$runtime" != "node" && "$runtime" != "bun" ]]; then
    echo "[launch] Invalid WABI_RUNTIME: $runtime (expected node|bun)" >&2
    exit 1
  fi

  if [[ "$domain" == "localhost" ]]; then
    frontend_url="http://localhost:3000"
    public_url="http://localhost:3000"
  else
    frontend_url="https://$domain"
    public_url="https://$domain"
  fi

  public_ip="${TURN_EXTERNAL_IP:-$(curl -fsS https://api.ipify.org 2>/dev/null || true)}"
  public_ip="${public_ip:-127.0.0.1}"
  turn_realm="$domain"

  if [[ "$mode" == "community" ]]; then
    db_mode="postgres"
    postgres_db="wabi"
    postgres_user="wabi"
    postgres_password="$(generate_hex_secret)"
    database_url="postgres://${postgres_user}:${postgres_password}@postgres:5432/${postgres_db}"
  else
    db_mode="sqlite"
    postgres_db=""
    postgres_user=""
    postgres_password=""
    database_url=""
  fi

  jwt_secret="$(generate_secret)"
  turn_secret="$(generate_secret)"

  cat > "$ENV_FILE" <<EOF
FRONTEND_URL=$frontend_url
PUBLIC_URL=$public_url
NODE_ENV=production
PORT=8080

# Generated by scripts/launch.sh
WABI_MODE=$mode
WABI_RUNTIME=$runtime
DB_MODE=$db_mode
DATABASE_PATH=/app/data/chat.db
DATABASE_URL=$database_url
POSTGRES_DB=$postgres_db
POSTGRES_USER=$postgres_user
POSTGRES_PASSWORD=$postgres_password

JWT_SECRET=$jwt_secret

DATA_DIR=/app/data
PLUGINS_DIR=/app/plugins
STATIC_DIR=/app/frontend/build

TURN_EXTERNAL_IP=$public_ip
TURN_REALM=$turn_realm
TURN_SHARED_SECRET=$turn_secret
TURN_CREDENTIAL_TTL_SECONDS=3600

MEDIA_LOCAL_ENHANCED_ENABLED=true
MEDIA_SRT_GATEWAY_ENABLED=false
MEDIA_SRT_GATEWAY_URL=
MEDIA_GATEWAY_HEARTBEAT_TIMEOUT_MS=45000
MEDIA_GATEWAY_KEY=
MEDIA_SRT_SESSION_TTL_SECONDS=900
MEDIA_SRT_BASE_PORT=7000
MEDIA_GATEWAY_ORIGIN_URL=http://backend:8080
MEDIA_GATEWAY_REGION=local
MEDIA_GATEWAY_HEARTBEAT_INTERVAL_MS=15000
MEDIA_GATEWAY_SESSION_SYNC_INTERVAL_MS=10000

OPENMOJI_VERSION=15.1.0
EOF

  cat > "$FRONTEND_ENV_FILE" <<EOF
VITE_SOCKET_URL=
VITE_GIPHY_API_KEY=$giphy_key
VITE_TURN_SERVER=$public_ip
VITE_TURN_PORT=3478
VITE_USE_TURNS=false
VITE_ENABLE_GOOGLE_STUN=true
VITE_ENABLE_RELAYS=false
EOF

  echo "[launch] Generated config:"
  echo "  - $ENV_FILE"
  echo "  - $FRONTEND_ENV_FILE"
}

is_config_missing() {
  [[ ! -s "$ENV_FILE" || ! -s "$FRONTEND_ENV_FILE" ]]
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      if [[ $# -lt 2 || -z "${2:-}" ]]; then
        echo "Missing value for --mode (expected normal|community)" >&2
        usage
        exit 1
      fi
      WABI_MODE="$2"
      shift 2
      continue
      ;;
    --runtime)
      if [[ $# -lt 2 || -z "${2:-}" ]]; then
        echo "Missing value for --runtime (expected node|bun)" >&2
        usage
        exit 1
      fi
      WABI_RUNTIME="$2"
      shift 2
      continue
      ;;
    --reconfigure)
      RECONFIGURE=true
      ;;
    --no-turn-profile)
      USE_TURN_PROFILE=false
      ;;
    --srt-gateway)
      USE_SRT_GATEWAY_PROFILE=true
      ;;
    --no-srt-gateway)
      USE_SRT_GATEWAY_PROFILE=false
      ;;
    --no-prune-images)
      PRUNE_DANGLING_IMAGES=false
      ;;
    --prune-stopped)
      PRUNE_STOPPED_CONTAINERS=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
  shift
done

validate_prereqs

if [[ "$RECONFIGURE" == "true" ]] || is_config_missing; then
  echo "[launch] First run or reconfigure requested. Bootstrapping defaults..."
  configure_defaults
fi

# Preserve caller-provided overrides instead of letting .env overwrite them.
CLI_WABI_MODE="${WABI_MODE-}"
CLI_WABI_RUNTIME="${WABI_RUNTIME-}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

if [[ -n "$CLI_WABI_MODE" ]]; then
  WABI_MODE="$CLI_WABI_MODE"
fi
if [[ -n "$CLI_WABI_RUNTIME" ]]; then
  WABI_RUNTIME="$CLI_WABI_RUNTIME"
fi

WABI_MODE="${WABI_MODE:-normal}"
WABI_RUNTIME="${WABI_RUNTIME:-node}"

if [[ "$WABI_MODE" != "normal" && "$WABI_MODE" != "community" ]]; then
  echo "[launch] Invalid WABI_MODE: $WABI_MODE (expected normal|community)" >&2
  exit 1
fi

if [[ "$WABI_RUNTIME" != "node" && "$WABI_RUNTIME" != "bun" ]]; then
  echo "[launch] Invalid WABI_RUNTIME: $WABI_RUNTIME (expected node|bun)" >&2
  exit 1
fi

compose_files=("$COMPOSE_FILE")
if [[ "$WABI_MODE" == "community" ]]; then
  compose_files+=("docker-compose.community.yml")
fi
if [[ "$WABI_RUNTIME" == "bun" ]]; then
  compose_files+=("docker-compose.bun.yml")
fi

compose=(docker compose)
for file in "${compose_files[@]}"; do
  compose+=(-f "$file")
done

echo "[launch] Mode: $WABI_MODE"
echo "[launch] Runtime: $WABI_RUNTIME"
echo "[launch] Compose files: ${compose_files[*]}"

echo "[launch] Validating compose config..."
"${compose[@]}" config >/dev/null

echo "[launch] Building and updating backend/frontend..."
"${compose[@]}" up -d --build --remove-orphans backend frontend

if [[ "$USE_TURN_PROFILE" == "true" ]]; then
  echo "[launch] Updating coturn profile service..."
  "${compose[@]}" --profile turn up -d --build --remove-orphans coturn
fi

effective_srt_profile="$USE_SRT_GATEWAY_PROFILE"
if [[ "$effective_srt_profile" == "auto" ]]; then
  if [[ "${MEDIA_SRT_GATEWAY_ENABLED:-false}" == "true" ]]; then
    effective_srt_profile="true"
  else
    effective_srt_profile="false"
  fi
fi

if [[ "$effective_srt_profile" == "true" ]]; then
  echo "[launch] Updating media-gateway profile service..."
  "${compose[@]}" --profile srt-gateway up -d --build --remove-orphans media-gateway
fi

if [[ "$PRUNE_DANGLING_IMAGES" == "true" ]]; then
  echo "[launch] Pruning dangling images..."
  docker image prune -f >/dev/null
fi

if [[ "$PRUNE_STOPPED_CONTAINERS" == "true" ]]; then
  echo "[launch] Pruning stopped containers..."
  docker container prune -f >/dev/null
fi

echo "[launch] Done."
