<script lang="ts">
  import {onMount,onDestroy,tick} from 'svelte';
  import {get} from 'svelte/store';
  import type {ArtifactSession} from '../../workspaceArtifacts/client';
  import {equal,newId,type Fields,type Json} from '../../workspaceArtifacts/model';
  import {downloadBlob,saveOriginal} from '../../workspaceArtifacts/storage';
  import {openWorkspace} from '../../workspaceArtifacts/navigation';
  import {cellKey,sheetKey,sheetIds,getSheet,getCell,columnName,rawText,shiftFormula,createSheet,asJson,type Cell} from './model';
  import {makeCell,literal,SUPPORTED_FUNCTIONS,createCalculator} from './formula';
  import {parseDelimited,writeDelimited} from './csv';
  import Charts from './Charts.svelte';
  const filesAbort=new AbortController();
  onDestroy(()=>filesAbort.abort());
  let {session,readonly=false,onfield=()=>{},onreview=()=>{}}=$props<{session:ArtifactSession;readonly?:boolean;onfield?:(field:string)=>void;onreview?:(field:string)=>void}>();
  const store=session.state;
  let sid=$state(sheetIds($store.draft.fields)[0]||''),selectedRow=$state(0),selectedColumn=$state(0),anchorRow=$state(0),anchorColumn=$state(0);
  let scrollTop=$state(0),editing=$state(false),entry=$state(''),error=$state(''),filter=$state(''),sort=$state<'none'|'ascending'|'descending'>('none'),showCharts=$state(false);
  let importRows=$state<string[][]|null>(null),delimiter=$state(','),importText=$state(''),importName=$state(''),originalId=$state(''),textOnly=$state(true);
  let notices=$state<string[]>([]),values=$state<Record<string,unknown>>({}),grid:HTMLDivElement|undefined,cellInput:HTMLInputElement|undefined;
  let worker:Worker|undefined,workerRevision=0,previousFields:Fields|null=null,calcTimer:ReturnType<typeof setTimeout>|undefined,disposed=false;
  let history=$state<{before:Record<string,Json|undefined>;after:Record<string,Json|undefined>}[]>([]),future=$state<typeof history>([]);
  const fields:Fields=$derived($store.draft.fields);
  const ids=$derived(sheetIds(fields));
  const sheet=$derived.by(()=>{try{return getSheet(fields,sid);}catch{return {name:'Unavailable sheet',rows:[],columns:[]};}});
  const selectedKey=$derived(cellKey(sid,sheet.rows[selectedRow]||'',sheet.columns[selectedColumn]||''));
  const selected=$derived(getCell(fields,sid,sheet.rows[selectedRow]||'',sheet.columns[selectedColumn]||''));
  const currentRaw=$derived(rawText(fields,sid,selected));
  const rowView=$derived.by(()=>{
    const column=sheet.columns[selectedColumn];let rows=sheet.rows.filter(r=>!filter||getCell(fields,sid,r,column).raw.toLowerCase().includes(filter.toLowerCase()));
    if(sort!=='none')rows=[...rows].sort((a,b)=>{const av=literal(getCell(fields,sid,a,column).raw),bv=literal(getCell(fields,sid,b,column).raw);const cmp=typeof av==='number'&&typeof bv==='number'?av-bv:String(av??'').localeCompare(String(bv??''),undefined,{numeric:true});return sort==='ascending'?cmp:-cmp;});
    return rows;
  });
  const start=$derived(Math.max(0,Math.floor(scrollTop/32)-5));
  const shown=$derived(rowView.slice(start,start+40));
  const range=$derived({r0:Math.min(anchorRow,selectedRow),r1:Math.max(anchorRow,selectedRow),c0:Math.min(anchorColumn,selectedColumn),c1:Math.max(anchorColumn,selectedColumn)});
  $effect(()=>{if(!ids.includes(sid)&&ids.length){sid=ids[0];selectedRow=0;selectedColumn=0;}if(selectedRow>=sheet.rows.length)selectedRow=Math.max(0,sheet.rows.length-1);if(selectedColumn>=sheet.columns.length)selectedColumn=Math.max(0,sheet.columns.length-1);});
  $effect(()=>{fields;shown;sid;sheet.columns;clearTimeout(calcTimer);calcTimer=setTimeout(calculate,60);});
  $effect(()=>{onfield(selectedKey);if(!editing)entry=currentRaw;});
  onMount(()=>{worker=new Worker(new URL('./calculation.worker.ts',import.meta.url),{type:'module'});worker.onmessage=e=>{if(disposed||!session.scope.current()||e.data.revision!==workerRevision)return;if(e.data.error)error=e.data.error;else values=e.data.values;};worker.onerror=()=>error='Calculation worker failed. Values are not being fabricated; reopen the sheet to retry.';calculate();});
  onDestroy(()=>{disposed=true;clearTimeout(calcTimer);worker?.terminate();previousFields=null;});
  function calculate(){
    if(!worker||disposed||!sid)return;
    const cells=shown.flatMap(row=>sheet.columns.map(col=>({key:cellKey(sid,row,col),sheet:sid,row,col})));
    const set:Fields={},remove:string[]=[];
    if(previousFields){for(const [k,v] of Object.entries(fields))if(!equal(previousFields[k],v))set[k]=v;for(const k of Object.keys(previousFields))if(!Object.hasOwn(fields,k))remove.push(k);}
    worker.postMessage({revision:++workerRevision,...(previousFields?{set,remove}:{fields}),cells});previousFields=fields;
  }
  function apply(set:Fields,remove:string[]=[],remember=true){
    if(readonly)return;const keys=new Set([...Object.keys(set),...remove]);if(keys.size>4096){error='This operation exceeds 4,096 cells. Use smaller selections; the workbook has not changed.';return;}
    if(remember){const before:Record<string,Json|undefined>={},after:Record<string,Json|undefined>={};for(const k of keys){before[k]=fields[k]===undefined?undefined:structuredClone(fields[k]);after[k]=Object.hasOwn(set,k)?structuredClone(set[k]):undefined;}history=[...history.slice(-99),{before,after}];future=[];}
    session.editMany(set,remove);error='';
  }
  function undo(redo=false){const stack=redo?future:history,operation=stack.at(-1);if(!operation)return;const expected=redo?operation.before:operation.after,target=redo?operation.after:operation.before;if(Object.keys(expected).some(k=>!equal(fields[k],expected[k]))){error='Another edit changed these cells. Undo was not allowed to overwrite it.';return;}const set:Fields={},remove:string[]=[];for(const [k,v] of Object.entries(target)){if(v===undefined)remove.push(k);else set[k]=v;}apply(set,remove,false);if(redo){future=future.slice(0,-1);history=[...history,operation];}else{history=history.slice(0,-1);future=[...future,operation];}}
  function commit(){if(readonly||!editing)return;try{apply({[selectedKey]:asJson(makeCell(fields,sid,entry))});editing=false;session.note('sheet-pending-cell','');}catch(e){error=String(e);}}
  function stash(value:string){entry=value;if(!readonly)session.note('sheet-pending-cell',JSON.stringify({key:selectedKey,raw:value,sid,row:selectedRow,column:selectedColumn}));}
  function recoverCell(){try{const pending=JSON.parse($store.draft.privateNotes['sheet-pending-cell']||'null');if(!pending||typeof pending.raw!=='string'||typeof pending.sid!=='string')return;const target=getSheet(fields,pending.sid);if(cellKey(pending.sid,target.rows[pending.row],target.columns[pending.column])!==pending.key)throw new Error('The original cell was removed. The text remains in Private backup.');sid=pending.sid;selectedRow=pending.row;selectedColumn=pending.column;editing=true;entry=pending.raw;}catch(e){error=String(e);}}
  async function edit(value?:string){if(readonly)return;editing=true;stash(value??currentRaw);await tick();cellInput?.focus();}
  function choose(r:number,c:number,extend=false){commit();selectedRow=r;selectedColumn=c;if(!extend){anchorRow=r;anchorColumn=c;}entry=rawText(fields,sid,getCell(fields,sid,sheet.rows[r],sheet.columns[c]));}
  function keyboard(e:KeyboardEvent){
    if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);return;}
    if(e.key==='Enter'||e.key==='F2'){e.preventDefault();void edit();return;}
    if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();const remove:string[]=[];for(let r=range.r0;r<=range.r1;r++)for(let c=range.c0;c<=range.c1;c++)remove.push(cellKey(sid,sheet.rows[r],sheet.columns[c]));apply({},remove);return;}
    if(e.key.startsWith('Arrow')){e.preventDefault();let r=selectedRow,c=selectedColumn;if(e.key==='ArrowUp')r--;if(e.key==='ArrowDown')r++;if(e.key==='ArrowLeft')c--;if(e.key==='ArrowRight')c++;choose(Math.max(0,Math.min(sheet.rows.length-1,r)),Math.max(0,Math.min(sheet.columns.length-1,c)),e.shiftKey);return;}
    if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();void edit(e.key);}
  }
  async function copy(cut=false){try{const rows:string[][]=[];for(let r=range.r0;r<=range.r1;r++){const row:string[]=[];for(let c=range.c0;c<=range.c1;c++)row.push(rawText(fields,sid,getCell(fields,sid,sheet.rows[r],sheet.columns[c])));rows.push(row);}await navigator.clipboard.writeText(writeDelimited(rows,'\t'));if(cut){const keys=rows.flatMap((row,r)=>row.map((_,c)=>cellKey(sid,sheet.rows[range.r0+r],sheet.columns[range.c0+c])));apply({},keys);}}catch(e){error='Clipboard unavailable: '+String(e);}}
  function paste(e:ClipboardEvent){if(readonly||e.target instanceof HTMLInputElement)return;e.preventDefault();try{const rows=parseDelimited(e.clipboardData?.getData('text/plain')||'','\t');if(rows.length*(rows.reduce((n,r)=>Math.max(n,r.length),0))>4096)throw new Error('Paste exceeds 4,096 cells.');const set:Fields={};rows.forEach((row,r)=>row.forEach((value,c)=>{const rid=sheet.rows[selectedRow+r],cid=sheet.columns[selectedColumn+c];if(!rid||!cid)throw new Error('Paste extends beyond this sheet. Add rows or columns first.');set[cellKey(sid,rid,cid)]=asJson(makeCell(fields,sid,value));}));apply(set);}catch(e){error=String(e);}}
  function insert(axis:'rows'|'columns'){const list=[...sheet[axis]],position=axis==='rows'?selectedRow:selectedColumn;if(list.length>=(axis==='rows'?100000:256)){error='Sheet dimension limit reached';return;}list.splice(position,0,newId());apply({[sheetKey(sid)]:asJson({...sheet,[axis]:list})});}
  function removeAxis(axis:'rows'|'columns'){const list=[...sheet[axis]],position=axis==='rows'?selectedRow:selectedColumn;if(list.length<=1)return;const [id]=list.splice(position,1),remove=Object.keys(fields).filter(k=>(k.startsWith(`c:${sid}:`)||k.startsWith(`f:${sid}:`))&&k.split(':')[axis==='rows'?2:3]===id);apply({[sheetKey(sid)]:asJson({...sheet,[axis]:list})},remove);}
  function fillDown(){try{const set:Fields={};for(let r=range.r0+1;r<=range.r1;r++)for(let c=range.c0;c<=range.c1;c++){const source=getCell(fields,sid,sheet.rows[range.r0],sheet.columns[c]),value:Cell={...structuredClone(source)};if(value.ast)value.ast=shiftFormula(fields,value.ast,r-range.r0,0);set[cellKey(sid,sheet.rows[r],sheet.columns[c])]=asJson(value);}apply(set);}catch(e){error=String(e);}}
  function format(update:Record<string,Json>){const set:Fields={};for(let r=range.r0;r<=range.r1;r++)for(let c=range.c0;c<=range.c1;c++){const k=`f:${sid}:${sheet.rows[r]}:${sheet.columns[c]}`;set[k]={...(fields[k] as Record<string,Json>||{}),...update};}apply(set);}
  function display(row:string,col:string):string{const key=cellKey(sid,row,col),value=values[key],cell=getCell(fields,sid,row,col);if(cell.unsupported)return '#UNSUPPORTED!';if(cell.ast&&value===undefined)return 'Calculating…';const v=cell.ast?value:literal(cell.raw),f=fields[`f:${sid}:${row}:${col}`] as Record<string,Json>|undefined;if(typeof v==='number'&&f){const decimals=typeof f.decimals==='number'?f.decimals:2;if(f.format==='percent')return (v*100).toFixed(decimals)+'%';if(f.format==='number'||f.format==='currency')return (f.format==='currency'?'$':'')+v.toLocaleString(undefined,{minimumFractionDigits:decimals,maximumFractionDigits:decimals});if(f.format==='date'){if(v===60&&fields.dateSystem!=='1904')return '1900-02-29 (Excel)';const epoch=fields.dateSystem==='1904'?Date.UTC(1904,0,1):Date.UTC(1899,11,v<60?31:30);const date=new Date(epoch+v*86400000);return Number.isFinite(date.getTime())?date.toISOString().slice(0,10):'#VALUE!';}}return String(v??'');}
  function style(row:string,col:string):string{const f=fields[`f:${sid}:${row}:${col}`] as Record<string,Json>|undefined;if(!f)return '';const out:string[]=[];if(f.bold)out.push('font-weight:700');if(f.italic)out.push('font-style:italic');if(typeof f.align==='string'&&['left','center','right'].includes(f.align))out.push('text-align:'+f.align);for(const [key,css] of [['color','color'],['fill','background-color']])if(typeof f[key]==='string'&&/^#[0-9a-f]{6}$/i.test(f[key] as string))out.push(`${css}:${f[key]}`);return out.join(';');}
  function newTab(){if(readonly)return;const next=createSheet(`Sheet ${ids.length+1}`);apply({...next.fields,sheets:[...ids,next.id]});sid=next.id;selectedRow=selectedColumn=anchorRow=anchorColumn=0;}
  function rename(){const name=prompt('Sheet name',sheet.name)?.trim();if(!name)return;if(ids.some(id=>id!==sid&&getSheet(fields,id).name.toLowerCase()===name.toLowerCase())){error='Sheet names must be unique';return;}apply({[sheetKey(sid)]:asJson({...sheet,name})});}
  function chart(type:'bar'|'line'|'pie'){if(range.r1-range.r0>999||range.c1-range.c0>19){error='Charts support at most 1,000 selected rows and 20 columns';return;}apply({[`chart:${newId()}`]:{title:`${sheet.name} chart`,type,sheet:sid,rows:sheet.rows.slice(range.r0,range.r1+1),columns:sheet.columns.slice(range.c0,range.c1+1)}});showCharts=true;}
  async function file(event:Event){const input=event.currentTarget as HTMLInputElement,f=input.files?.[0];input.value='';if(!f)return;try{error='';const source=await saveOriginal(session.scope.key,f);if(!session.scope.current())return;originalId=source;importName=f.name;if(/\.(csv|tsv)$/i.test(f.name)){importText=await f.text();delimiter=f.name.toLowerCase().endsWith('.tsv')?'\t':',';importRows=parseDelimited(importText,delimiter);}else{const adapter=await import('./files');const result=await adapter.importWorkbook(f,filesAbort.signal);if(!session.scope.current())return;notices=result.warnings;pendingWorkbook=result.fields;}}catch(e){error=String(e);}}
  let pendingWorkbook=$state<Fields|null>(null);
  async function acceptImport(){try{if(importRows){const {workbookFromRows}=await import('./files');const next=workbookFromRows(importRows,importName,textOnly);openWorkspace({kind:'sheet',seed:next,originalId});}else if(pendingWorkbook)openWorkspace({kind:'sheet',seed:pendingWorkbook,originalId});}catch(e){error=String(e);}}
  async function exportFile(format:'csv'|'tsv'|'xlsx'|'ods'){try{const adapter=await import('./files');await session.flush();const output=await adapter.exportWorkbook(fields,sid,format,filesAbort.signal);if(session.scope.current()){downloadBlob(output.name,output.blob);notices=output.warnings;}}catch(e){error=String(e);}}
</script>
<div class="sheets">
  <div class="workspace-bar">
    <button onclick={()=>undo()} disabled={readonly||!history.length}>Undo</button><button onclick={()=>undo(true)} disabled={readonly||!future.length}>Redo</button>
    <button onclick={()=>copy()}>Copy range</button><button onclick={()=>copy(true)} disabled={readonly}>Cut</button><button onclick={fillDown} disabled={readonly||range.r0===range.r1}>Fill down</button>
    <button onclick={()=>format({bold:true})} disabled={readonly}>Bold</button><button onclick={()=>format({bold:false,italic:false})} disabled={readonly}>Plain</button>
    <select aria-label="Number format" disabled={readonly} onchange={e=>format({format:e.currentTarget.value})}><option value="general">General</option><option value="number">Number</option><option value="currency">USD currency</option><option value="percent">Percent</option><option value="date">Date serial</option><option value="text">Text</option></select>
    <button onclick={()=>onreview(selectedKey)}>Comment on cell</button>
    <details><summary>Rows, columns and charts</summary><div class="workspace-bar"><button disabled={readonly} onclick={()=>insert('rows')}>Insert row</button><button disabled={readonly} onclick={()=>removeAxis('rows')}>Delete row</button><button disabled={readonly} onclick={()=>insert('columns')}>Insert column</button><button disabled={readonly} onclick={()=>removeAxis('columns')}>Delete column</button><button disabled={readonly} onclick={()=>chart('bar')}>Bar chart</button><button disabled={readonly} onclick={()=>chart('line')}>Line chart</button><button disabled={readonly} onclick={()=>chart('pie')}>Pie chart</button></div></details>
    <details><summary>Import / export</summary><label>Open workbook<input type="file" accept=".csv,.tsv,.xlsx,.ods" onchange={file} /></label><div class="workspace-bar">{#each ['csv','tsv','xlsx','ods'] as fmt}<button onclick={()=>exportFile(fmt as 'csv'|'tsv'|'xlsx'|'ods')}>Export {fmt.toUpperCase()}</button>{/each}</div></details>
  </div>
  <div class="formula-bar"><strong>{columnName(selectedColumn)}{selectedRow+1}</strong><input aria-label="Formula or cell value" value={entry} readonly={readonly} onfocus={()=>{if(!readonly){editing=true;entry=currentRaw;}}} oninput={e=>stash(e.currentTarget.value)} onkeydown={e=>{if(e.key==='Enter'){e.preventDefault();commit();grid?.focus();}if(e.key==='Escape'){editing=false;entry=currentRaw;session.note('sheet-pending-cell','');grid?.focus();}}} onblur={commit} /><button disabled={readonly} onclick={commit}>Apply</button></div>
  <div class="workspace-bar"><input aria-label="Filter selected column in my view" bind:value={filter} placeholder="Filter this column · my view only" /><select aria-label="Sort selected column in my view" bind:value={sort}><option value="none">Original order</option><option value="ascending">My view: ascending</option><option value="descending">My view: descending</option></select><button disabled={readonly||sort==='none'||Boolean(filter)} onclick={()=>{if(confirm('Reorder whole rows for all collaborators? Formulas and comments keep their stable targets.')){apply({[sheetKey(sid)]:asJson({...sheet,rows:rowView})});sort='none';}}}>Apply order to shared sheet</button><button onclick={()=>showCharts=!showCharts}>Charts</button></div>
  {#if !editing&&$store.draft.privateNotes['sheet-pending-cell']}<div class="workspace-message">Unfinished cell input is saved privately.<button onclick={recoverCell}>Recover input</button><button onclick={()=>session.note('sheet-pending-cell','')}>Discard input</button></div>{/if}
  {#if error}<div class="workspace-message" role="alert">{error}</div>{/if}
  {#if notices.length&&!pendingWorkbook}<details class="workspace-message" open><summary>Compatibility report</summary>{#each notices as note}<p>{note}</p>{/each}</details>{/if}
  {#if importRows||pendingWorkbook}
    <section class="import-preview"><h3>Import a new private working copy</h3><p>The original file is preserved on this device. This will not overwrite the open workbook.</p>
      {#if importRows}<label>Delimiter<select bind:value={delimiter} onchange={()=>{try{importRows=parseDelimited(importText,delimiter);}catch(e){error=String(e);}}}><option value=",">Comma</option><option value={'\t'}>Tab</option><option value=";">Semicolon</option></select></label><label><input type="checkbox" bind:checked={textOnly} />Import cells as text (preserves leading zeros and ambiguous dates)</label><p>{importRows.length.toLocaleString()} rows · {importRows.reduce((n,r)=>Math.max(n,r.length),0)} columns</p><pre>{writeDelimited(importRows.slice(0,5),'\t')}</pre>{/if}
      {#each notices as note}<p>{note}</p>{/each}<button onclick={acceptImport}>Create private sheet</button><button onclick={()=>{importRows=null;pendingWorkbook=null;}}>Cancel</button>
    </section>
  {:else}
    {#if showCharts}<div class="chart-list">{#each Object.entries(fields).filter(([k])=>k.startsWith('chart:')) as [key,c]}<Charts {fields} chart={c as any} />{#if !readonly}<button onclick={()=>apply({},[key])}>Remove chart</button>{/if}{/each}</div>{/if}
    <div class="sheet-scroll" bind:this={grid} role="grid" aria-label={sheet.name} aria-rowcount={sheet.rows.length+1} aria-colcount={sheet.columns.length+1} tabindex="0" onscroll={e=>scrollTop=e.currentTarget.scrollTop} onkeydown={keyboard} onpaste={paste}>
      <table><thead><tr><th class="row-number">#</th>{#each sheet.columns as col,c}<th scope="col"><button onclick={()=>choose(selectedRow,c)}>{columnName(c)}</button></th>{/each}</tr></thead>
        <tbody>{#if start>0}<tr aria-hidden="true"><td colspan={sheet.columns.length+1} style:height={`${start*32}px`}></td></tr>{/if}
          {#each shown as row (row)}{@const r=sheet.rows.indexOf(row)}<tr aria-rowindex={r+2}><th scope="row" class="row-number">{r+1}</th>{#each sheet.columns as col,c}<td class:selected={r>=range.r0&&r<=range.r1&&c>=range.c0&&c<=range.c1} style={style(row,col)}>{#if editing&&r===selectedRow&&c===selectedColumn}<input bind:this={cellInput} aria-label={`${columnName(c)}${r+1}`} value={entry} oninput={e=>stash(e.currentTarget.value)} onblur={commit} onkeydown={e=>{if(e.key==='Enter'||e.key==='Tab'){e.preventDefault();commit();choose(Math.min(r+(e.key==='Enter'?1:0),sheet.rows.length-1),Math.min(c+(e.key==='Tab'?1:0),sheet.columns.length-1));grid?.focus();}else if(e.key==='Escape'){editing=false;entry=currentRaw;session.note('sheet-pending-cell','');grid?.focus();}}} />{:else}<button aria-label={`${columnName(c)}${r+1}: ${display(row,col)}`} title={getCell(fields,sid,row,col).unsupported?'Unsupported formula. Any imported cached result is not a Wabi calculation.':rawText(fields,sid,getCell(fields,sid,row,col))} onclick={e=>choose(r,c,e.shiftKey)} ondblclick={()=>edit()}>{display(row,col)||' '}</button>{/if}</td>{/each}</tr>{/each}
          {#if rowView.length>start+shown.length}<tr aria-hidden="true"><td colspan={sheet.columns.length+1} style:height={`${(rowView.length-start-shown.length)*32}px`}></td></tr>{/if}
        </tbody>
      </table>
    </div>
    <footer class="workspace-bar">{#each ids as id}<button aria-pressed={sid===id} onclick={()=>{commit();sid=id;selectedRow=selectedColumn=anchorRow=anchorColumn=0;scrollTop=0;if(grid)grid.scrollTop=0;}}>{getSheet(fields,id).name}</button>{/each}<button disabled={readonly} onclick={newTab}>+ Sheet</button><button disabled={readonly} onclick={rename}>Rename sheet</button><small>{sheet.rows.length.toLocaleString()} rows × {sheet.columns.length} columns · saved independently of the original file</small></footer>
  {/if}
  <details class="formula-help"><summary>Supported formulas and limits</summary><p>{SUPPORTED_FUNCTIONS.join(', ')}. Arithmetic, comparisons, relative/absolute references, and cross-sheet references. Unsupported formulas are preserved, not calculated. Concurrent cell changes require explicit conflict resolution. Up to 256 columns, 100,000 rows, 250,000 populated fields, and 32 MiB per shared workbook; batches are limited to 4,096 changed fields.</p></details>
</div>
<style>
.sheets{height:100%;min-height:0;display:flex;flex-direction:column;overflow:hidden}.formula-bar{display:flex;gap:10px;align-items:center;padding:8px 12px;border-bottom:1px solid var(--border-color)}.formula-bar strong{min-width:64px}.formula-bar input{flex:1;min-width:80px}.sheet-scroll{flex:1;min-height:100px;overflow:auto;outline:none;position:relative}table{border-collapse:separate;border-spacing:0;table-layout:fixed;width:max-content;min-width:100%}th,td{padding:0;border-right:1px solid var(--border-color);border-bottom:1px solid var(--border-color);height:32px;box-sizing:border-box;min-width:110px;max-width:160px}thead{position:sticky;top:0;z-index:3;background:var(--bg-secondary,var(--surface-base))}.row-number{position:sticky;left:0;z-index:2;background:var(--bg-secondary,var(--surface-base));min-width:50px;width:50px;max-width:50px;text-align:center;font-size:12px}td button,th button{width:100%;height:31px;min-height:31px!important;max-width:160px;min-width:110px;padding:4px 8px!important;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:0!important;border-radius:0!important;background:transparent!important;text-align:inherit;color:inherit}td input{width:160px;min-width:110px;height:31px;min-height:31px!important;border-radius:0!important;padding:4px!important}td.selected{outline:2px solid var(--accent,var(--text-primary));outline-offset:-2px}.import-preview{padding:18px;overflow:auto}.import-preview pre{white-space:pre-wrap}.import-preview label{display:block;margin:12px 0}.chart-list{max-height:350px;overflow:auto}.formula-help{padding:8px 12px;font-size:12px}.formula-help p{max-width:900px;line-height:1.5}.sheets details .workspace-bar{padding:6px}.formula-help[open]{max-height:150px;overflow:auto}
</style>
