<script lang="ts">
    import { onMount,onDestroy } from 'svelte';
    import { captureScope,request,targets,presentationLink,type AudienceState,type AudienceSlide,type Scope } from './bridge';
    import AudienceSlideView from './AudienceSlide.svelte';
    import './workspace.css';
    let scope=$state<Scope|null>(null);let sessionId=$state('');let presentationState=$state<AudienceState|null>(null);let slides=$state<AudienceSlide[]>([]);let follow=$state(true);let independentId=$state('');let error=$state('');let busy=$state(false);let handoff=$state('');let panel:HTMLDivElement;let timer:ReturnType<typeof setTimeout>|undefined;let abort=new AbortController();let disposed=false;let loading=false;let epoch=0;let address=$state('');let previous:unknown;
    const selected=$derived(slides.find(s=>s.id===(follow?presentationState?.slideId:independentId))||slides[0]||null);
    const selectedIndex=$derived(slides.findIndex(s=>s.id===selected?.id));
    function apply(next:AudienceState){if(presentationState&&next.sequence<presentationState.sequence)return;if(next.slides)slides=next.slides;presentationState=next;if(!slides.some(s=>s.id===independentId))independentId=next.slideId;}
    async function refresh(){if(!scope||!sessionId||loading||disposed)return;loading=true;const current=epoch;try{const suffix=presentationState?`?edition=${encodeURIComponent(presentationState.edition)}`:'';const next=await request<AudienceState>(scope,`/presentations/${sessionId}${suffix}`,undefined,undefined,abort.signal);if(current!==epoch||disposed)return;apply(next);error='';}catch(e){if(current===epoch&&!disposed)error=e instanceof Error?e.message:String(e);}finally{loading=false;if(current===epoch&&!disposed&&sessionId)timer=setTimeout(()=>void refresh(),document.hidden?4000:1200);}}
    function open(id:string){if(!/^[0-9a-f-]{36}$/i.test(id)){error='Invalid presentation ID';return;}epoch++;if(timer)clearTimeout(timer);abort.abort();abort=new AbortController();loading=false;presentationState=null;slides=[];follow=true;sessionId=id;void refresh();}
    function fromAddress(){try{let id=address.trim();if(id.includes('://')){const url=new URL(id);if(!scope||new URL(scope.server).origin!==url.origin)throw new Error('Switch to the server in this presentation link first.');id=url.searchParams.get('workspaceSession')||'';}open(id);}catch(e){error=e instanceof Error?e.message:String(e);}}
    async function command(action:string,extra:Record<string,unknown>={}){if(!scope||!presentationState||busy)return;busy=true;try{const result=await request<AudienceState>(scope,`/presentations/${sessionId}`,{action,generation:presentationState.generation,sequence:presentationState.sequence,...extra},undefined,abort.signal);apply(result);error='';}catch(e){error=e instanceof Error?e.message:String(e);if(timer)clearTimeout(timer);void refresh();}finally{busy=false;}}
    function move(direction:number){const index=Math.max(0,Math.min(slides.length-1,selectedIndex+direction));const slide=slides[index];if(!slide)return;if(presentationState?.canControl&&follow)void command('slide',{slideId:slide.id});else{follow=false;independentId=slide.id;}}
    function key(event:KeyboardEvent){if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement||event.target instanceof HTMLTextAreaElement)return;if(event.key==='ArrowRight'||event.key==='PageDown'){event.preventDefault();move(1);}if(event.key==='ArrowLeft'||event.key==='PageUp'){event.preventDefault();move(-1);}}
    async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await panel.requestFullscreen();}catch(e){error='Fullscreen was not permitted; the presentation remains available in this panel.';}}
    onMount(()=>{let unsubscribe=()=>{};void captureScope().then(value=>{if(disposed)return;scope=value;unsubscribe=targets.subscribe(value=>{if(value.audience&&value.audience!==previous){previous=value.audience;if(value.audience.sessionId)open(value.audience.sessionId);}});}).catch(e=>error=e.message);return()=>unsubscribe();});
    onDestroy(()=>{disposed=true;epoch++;abort.abort();if(timer)clearTimeout(timer);});
</script>
<svelte:window onkeydown={key}/>
<section class="wabi-workspace">
    <header class="workspace-bar"><strong>Presentation</strong>{#if presentationState}<span>{selectedIndex+1} / {slides.length}</span><button onclick={()=>{follow=!follow;independentId=presentationState!.slideId;}}>{follow?'Browse independently':'Back to presenter'}</button><button onclick={()=>void fullscreen()}>Fullscreen</button><button onclick={()=>{if(scope)void navigator.clipboard.writeText(presentationLink(scope.server,sessionId)).catch(()=>error='Clipboard access was denied.');}}>Copy presentation link</button><span role="status">{presentationState.ended?'Ended':presentationState.paused?'Paused':follow?'Following presenter':'Browsing independently'}</span>{/if}</header>
    {#if !sessionId}<form class="workspace-home-note workspace-toolbar" onsubmit={event=>{event.preventDefault();fromAddress();}}><input aria-label="Presentation link or ID" placeholder="Presentation link or ID" bind:value={address}/><button disabled={!scope}>Join presentation</button></form>{/if}
    {#if error}<div class="workspace-notice" role="alert">{error} — cached slides remain available; they may no longer match the presenter.</div>{/if}
    <div class="audience-display" bind:this={panel}>{#if selected}<AudienceSlideView slide={selected} aspect={presentationState?.aspect} blank={follow&&presentationState?.blank}/>{:else if sessionId}<p role="status">Loading approved presentation slides…</p>{/if}</div>
    {#if presentationState}<footer class="workspace-bar"><button disabled={busy||selectedIndex<=0} onclick={()=>move(-1)}>Previous</button><button disabled={busy||selectedIndex>=slides.length-1} onclick={()=>move(1)}>Next</button><select aria-label="Browse a slide" value={selected?.id||''} onchange={event=>{follow=false;independentId=event.currentTarget.value;}}>{#each slides as slide,i(slide.id)}<option value={slide.id}>{i+1}. {slide.title||'Untitled slide'}</option>{/each}</select>
        {#if presentationState.canControl&&!presentationState.ended}<button disabled={busy} onclick={()=>void command('blank')}>{presentationState.blank?'Show slides':'Blank screen'}</button><button disabled={busy} onclick={()=>void command(presentationState!.paused?'resume':'pause')}>{presentationState.paused?'Resume':'Pause'}</button><input aria-label="New presenter account ID" placeholder="Account ID for handoff" inputmode="numeric" bind:value={handoff}/><button disabled={busy||!/^[1-9]\d*$/.test(handoff)} onclick={()=>void command('handoff',{targetUserId:Number(handoff)})}>Pass control</button><button disabled={busy} onclick={()=>void command('end')}>End presentation</button>{/if}
    </footer><p class="audience-note">Viewing slides does not join or end a voice call. Presentation control does not grant access to private notes.</p>{/if}
</section>
<style>.audience-display{flex:1;min-height:0;display:flex;align-items:center;justify-content:center;overflow:auto;padding:1rem;background:#0d1019}.audience-display :global(.audience-slide){max-width:1200px;max-height:100%;width:min(100%,calc((100vh - 230px) * 1.7778))}.audience-display:fullscreen{padding:0}.audience-display:fullscreen :global(.audience-slide){width:100%;max-width:100%;max-height:100vh}.audience-note{font-size:.75rem;margin:.4rem 1rem;color:var(--text-secondary,#b5bad0)}footer input{max-width:150px}</style>
