//! Canonical signed-entry-point source. Signatures are generated by the
//! Authority from its root key; this projection stores the versioned body.

use crate::{
    engine::locks::ProjectionState,
    error::{Result, WabiError},
    projections::handler::{DurableEvent, Projection},
};
use serde::{Deserialize, Serialize};

pub const INDEX: &str = "community_roster";
pub const EVENT: &str = "community_roster_replaced_v1";
pub const KEY: &[u8] = b"v1";

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CommunityRosterRecord {
    pub schema_version: u8,
    pub version: u64,
    pub entries: Vec<RosterEntryRecord>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RosterEntryRecord {
    pub node_id: String,
    pub role: String,
    pub url: String,
}

pub fn decode(bytes: &[u8]) -> Result<CommunityRosterRecord> {
    let bad = || WabiError::Corrupt {
        location: INDEX.into(),
        detail: "invalid community roster v1".into(),
    };
    if bytes.len() > 64 * 1024 {
        return Err(bad());
    }
    let roster: CommunityRosterRecord = serde_json::from_slice(bytes).map_err(|_| bad())?;
    if roster.schema_version != 1
        || roster.version == 0
        || roster.entries.is_empty()
        || roster.entries.len() > 64
    {
        return Err(bad());
    }
    Ok(roster)
}

pub struct CommunityRosterProjection;

impl Projection for CommunityRosterProjection {
    fn event_type(&self) -> &str {
        EVENT
    }

    fn apply(&self, event: &DurableEvent, state: &ProjectionState) -> Result<()> {
        let roster = decode(&event.payload)?;
        if let Some(existing) = state.get(INDEX, KEY) {
            let existing = decode(&existing)?;
            if existing.version.checked_add(1) != Some(roster.version) {
                return Err(WabiError::Corrupt {
                    location: INDEX.into(),
                    detail: "community roster version is not the next version".into(),
                });
            }
        }
        state.insert(INDEX, KEY.to_vec(), event.payload.clone(), event.commit_seq);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roster_payload_has_a_versioned_bounded_shape() {
        let valid = br#"{"schemaVersion":1,"version":1,"entries":[{"nodeId":"a","role":"authority","url":"https://a.example"}]}"#;
        assert_eq!(decode(valid).unwrap().version, 1);
        assert!(decode(b"{}").is_err());
        assert!(decode(&vec![0; 64 * 1024 + 1]).is_err());
        assert!(decode(br#"{"schemaVersion":1,"version":0,"entries":[]}"#).is_err());
    }

    #[test]
    fn roster_projection_rejects_skipped_or_repeated_versions() {
        fn event(commit_seq: u64, version: u64) -> DurableEvent {
            DurableEvent {
                commit_seq,
                stream_id: "community-roster:v1".into(),
                event_type: EVENT.into(),
                payload: serde_json::json!({
                    "schemaVersion": 1,
                    "version": version,
                    "entries": [{
                        "nodeId": "a",
                        "role": "authority",
                        "url": "https://a.example"
                    }]
                })
                .to_string()
                .into_bytes(),
            }
        }

        let state = ProjectionState::new();
        let projection = CommunityRosterProjection;

        // A migrated sidecar can begin above version one.
        projection.apply(&event(1, 4), &state).unwrap();
        assert!(projection.apply(&event(2, 6), &state).is_err());
        assert!(projection.apply(&event(3, 4), &state).is_err());
        assert_eq!(decode(&state.get(INDEX, KEY).unwrap()).unwrap().version, 4);

        projection.apply(&event(4, 5), &state).unwrap();
        assert_eq!(decode(&state.get(INDEX, KEY).unwrap()).unwrap().version, 5);
    }
}
