/**
 * Base Palettes
 * Compact color definitions — ~20 colors per theme instead of 84
 * All other colors and gradients are derived via buildTokens.ts
 *
 * Curated core set (8): a good dark, a good light, high-contrast (a11y),
 * forest, sakura (flower), space, blue, and warm red (ember).
 * Each carries a signature ambient effect.
 */

import type { BasePalette } from './buildTokens';

export const darkPalette: BasePalette = {
	id: 'dark',
	name: 'Nebula',
	description: 'Vibrant space-inspired theme with magenta accents. Perfect for creative, late-night sessions.',
	bgBase: '#1a1a2e',
	bgRaised: '#24243e',
	bgSunken: '#0f0c29',
	bgPrimary: 'linear-gradient(to right, #0f0c29 0%, #302b63 100%)',
	textPrimary: '#e0e0ff',
	textSecondary: '#b3b3ff',
	textMuted: '#9999ff',
	accent: '#a855f7',
	accentSecondary: '#c084fc',
	statusOnline: '#22c55e',
	statusAway: '#f59e0b',
	statusBusy: '#ef4444',
	statusOffline: '#708090',
	success: '#22c55e',
	info: '#3b82f6',
	warning: '#f59e0b',
	danger: '#ef4444',
	ambient: { effect: 'constellations', color: '#a855f7', intensity: 0.3 },
};

export const lightPalette: BasePalette = {
	id: 'light',
	name: 'Daylight',
	description: 'Clean and bright with soft purple accents. Great for daytime use.',
	bgBase: '#ffffff',
	bgRaised: '#f5f5f8',
	bgSunken: '#ffffff',
	bgPrimary: 'linear-gradient(to right, #f0f0f5 0%, #e8e8f0 100%)',
	textPrimary: '#000000',
	textSecondary: '#2a2a4a',
	textMuted: '#4a4a6a',
	accent: '#6200ea',
	accentSecondary: '#7c4dff',
	statusOnline: '#00c853',
	statusAway: '#ffa000',
	statusBusy: '#d32f2f',
	statusOffline: '#757575',
	success: '#00c853',
	info: '#0091ea',
	warning: '#ffa000',
	danger: '#d32f2f',
	ambient: { effect: 'none', intensity: 0 },
};

export const midnightBluePalette: BasePalette = {
	id: 'blue',
	name: 'Midnight Blue',
	description: 'Deep ocean blues with a neon grid. Calm, focused, and unmistakably cyberpunk.',
	bgBase: '#0d1b2a',
	bgRaised: '#1b263b',
	bgSunken: '#0a1929',
	bgPrimary: 'linear-gradient(to right, #0a1929 0%, #1a2332 100%)',
	textPrimary: '#e0f2fe',
	textSecondary: '#bae6fd',
	textMuted: '#7dd3fc',
	accent: '#06b6d4',
	accentSecondary: '#0ea5e9',
	statusOnline: '#10b981',
	statusAway: '#f59e0b',
	statusBusy: '#ef4444',
	statusOffline: '#6b7280',
	success: '#10b981',
	info: '#0ea5e9',
	warning: '#f59e0b',
	danger: '#ef4444',
	ambient: { effect: 'cyberpunk-grid', color: '#06b6d4', intensity: 0.35 },
};

export const vscodeHighContrastPalette: BasePalette = {
	id: 'high-contrast',
	name: 'High Contrast',
	description: 'Pure black with electric blue accents. Maximum contrast for accessibility.',
	bgBase: '#0a0a0a',
	bgRaised: '#000000',
	bgSunken: '#000000',
	bgPrimary: '#000000',
	textPrimary: '#ffffff',
	textSecondary: '#d0d0d0',
	textMuted: '#a0a0a0',
	accent: '#00bfff',
	accentSecondary: '#0099ff',
	statusOnline: '#00ff7f',
	statusAway: '#ffa500',
	statusBusy: '#ff3333',
	statusOffline: '#707070',
	success: '#00ff7f',
	info: '#00bfff',
	warning: '#ffa500',
	danger: '#ff3333',
	ambient: { effect: 'none', intensity: 0 },
};

export const forestPalette: BasePalette = {
	id: 'forest',
	name: 'Forest',
	description: 'Deep greens and earth tones. Calming nature-inspired dark theme.',
	bgBase: '#0d1f0d',
	bgRaised: '#162616',
	bgSunken: '#0a1a0a',
	bgPrimary: 'linear-gradient(to right, #0a1a0a 0%, #0f2a18 100%)',
	textPrimary: '#f0faf2',
	textSecondary: '#c8e6cc',
	textMuted: '#96d4a0',
	accent: '#2ecc71',
	accentSecondary: '#1abc9c',
	statusOnline: '#2ecc71',
	statusAway: '#f39c12',
	statusBusy: '#e74c3c',
	statusOffline: '#55776a',
	success: '#2ecc71',
	info: '#1abc9c',
	warning: '#f39c12',
	danger: '#e74c3c',
	ambient: { effect: 'none', intensity: 0 },
};

export const emberPalette: BasePalette = {
	id: 'ember',
	name: 'Warm Red',
	description: 'Warm oranges and deep reds with rising embers. Fiery dark theme for intense focus.',
	bgBase: '#1f0f00',
	bgRaised: '#2d1800',
	bgSunken: '#1a0a00',
	bgPrimary: 'linear-gradient(to right, #1a0a00 0%, #2a1200 100%)',
	textPrimary: '#fde8cc',
	textSecondary: '#f5c98a',
	textMuted: '#d4924c',
	accent: '#f97316',
	accentSecondary: '#fb923c',
	statusOnline: '#4ade80',
	statusAway: '#fbbf24',
	statusBusy: '#ef4444',
	statusOffline: '#78716c',
	success: '#4ade80',
	info: '#60a5fa',
	warning: '#fbbf24',
	danger: '#ef4444',
	ambient: { effect: 'embers', color: '#f97316', intensity: 0.4, speed: 1.1 },
};

export const sakuraPalette: BasePalette = {
	id: 'sakura',
	name: 'Sakura',
	description: 'Soft falling petals over a twilight plum canvas. Gentle, romantic, and calm.',
	bgBase: '#241a26',
	bgRaised: '#33263a',
	bgSunken: '#1a131c',
	bgPrimary: 'linear-gradient(135deg, #1a131c 0%, #2e2233 60%, #3a2436 100%)',
	textPrimary: '#f6e9ef',
	textSecondary: '#e3c9d6',
	textMuted: '#b78fa3',
	accent: '#f5a0c0',
	accentSecondary: '#ff8cb8',
	statusOnline: '#7ee0a8',
	statusAway: '#f6c453',
	statusBusy: '#f06a8a',
	statusOffline: '#8a6f7e',
	success: '#7ee0a8',
	info: '#8ec5ff',
	warning: '#f6c453',
	danger: '#f06a8a',
	ambient: { effect: 'sakura', color: '#f5a0c0', intensity: 0.55 },
};

export const spacePalette: BasePalette = {
	id: 'space',
	name: 'Space',
	description: 'A deep cosmic void lit by drifting stars that fade in and out.',
	bgBase: '#05060f',
	bgRaised: '#0c1228',
	bgSunken: '#02030a',
	bgPrimary: 'linear-gradient(135deg, #02030a 0%, #0a1030 55%, #0d1638 100%)',
	textPrimary: '#dfe6ff',
	textSecondary: '#aebbe6',
	textMuted: '#7d8bc0',
	accent: '#6ea8ff',
	accentSecondary: '#5fd0ff',
	statusOnline: '#5be0a0',
	statusAway: '#f6c453',
	statusBusy: '#ff6b8a',
	statusOffline: '#5a648f',
	success: '#5be0a0',
	info: '#5fd0ff',
	warning: '#f6c453',
	danger: '#ff6b8a',
	ambient: { effect: 'stars', color: '#9cc3ff', intensity: 0.6 },
};

// ===== ALL PALETTES =====
export const ALL_PALETTES: BasePalette[] = [
	darkPalette,
	lightPalette,
	midnightBluePalette,
	vscodeHighContrastPalette,
	forestPalette,
	emberPalette,
	sakuraPalette,
	spacePalette,
];

export const DEFAULT_PALETTE = darkPalette;
